import type { Question, Step, Level } from '../shared/types'

export const LEVELS: Level[] = [
  { n: 1, name: 'Story foundations', zh: '故事基础', ja: '物語の基礎', blurb: 'Premise, structure, conflict, arcs and suspense.', cats: ['story'] },
  { n: 2, name: 'Camera & composition', zh: '摄影与构图', ja: '撮影と構図', blurb: 'Shot sizes, lenses, depth of field, movement, the 180° rule.', cats: ['camera', 'composition'] },
  { n: 3, name: 'Light & color', zh: '灯光与色彩', ja: '照明と色彩', blurb: 'Three-point light, key/fill ratio, color temperature, color scripts.', cats: ['lighting', 'color'] },
  { n: 4, name: 'Editing & sound', zh: '剪辑与声音', ja: '編集と音響', blurb: 'Kuleshov, continuity, cross-cutting, pacing, Foley and mix.', cats: ['editing', 'sound'] },
  { n: 5, name: 'Directing & pipeline', zh: '导演与制作流程', ja: '演出と制作工程', blurb: 'Vision, blocking, coverage, actors, boards, previs, film history.', cats: ['director', 'preprod', 'history', 'modern'] },
  { n: 6, name: 'Animation', zh: '动画', ja: 'アニメーション', blurb: 'The 12 principles, timing and spacing, blocking to polish, anime terms.', cats: ['anim_principle', 'anim_tech'] },
  { n: 7, name: 'Modeling & rigging', zh: '建模与绑定', ja: 'モデリングとリギング', blurb: 'Topology, subdivision, UVs, sculpt to retopo, bones, IK/FK, shape keys.', cats: ['modeling', 'rigging'] },
  { n: 8, name: 'Blender flow & render', zh: 'Blender流程与渲染', ja: 'Blenderの流れとレンダー', blurb: 'Shading, lights, cameras, EEVEE vs Cycles, compositing, output.', cats: ['blender'] },
]

const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({
  prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why,
})

export const AUTHORED: Question[] = [
  // ───────── L1 Story
  { id: 'l1-01', level: 1, title: 'Build a logline', terms: ['logline', 'protagonist', 'stakes'], tags: ['story'],
    scenario: 'A shy lighthouse keeper finds a stranded mermaid. A storm is coming, and the town wants to sell her to a circus.',
    steps: [
      s('Who is the [[protagonist]]?', [['a', 'The lighthouse keeper'], ['b', 'The town'], ['c', 'The storm']], 'a', 'The protagonist is the one whose choices drive the story.'),
      s('What are the [[stakes]]?', [['a', 'The mermaid is sold and lost'], ['b', 'The lighthouse needs paint'], ['c', 'The weather changes']], 'a', 'Stakes = what is lost if the hero fails.'),
      s('Best [[logline]]?', [['a', 'A shy keeper must stand up to his town to free a mermaid before the storm traps her forever.'], ['b', 'A story about the sea.'], ['c', 'A mermaid and a lighthouse in a storm.']], 'a', 'Hero + goal + obstacle + stakes in one sentence.'),
    ] },
  { id: 'l1-02', level: 1, title: 'Where acts turn', terms: ['three_act', 'inciting_incident', 'midpoint', 'climax'], tags: ['story'],
    scenario: 'A 100-minute film. A courier is hired to deliver a package, learns it is a kidnapped child, and fights to return her home.',
    steps: [
      s('The [[inciting_incident]] is…', [['a', 'The courier takes the job'], ['b', 'The final car chase'], ['c', 'The return home']], 'a', 'It breaks the normal world and starts the story question.'),
      s('The [[midpoint]] (about minute 50) is most likely…', [['a', 'He opens the package and finds the child'], ['b', 'Opening credits'], ['c', 'The epilogue']], 'a', 'The midpoint flips the goal: from delivery to rescue.'),
      s('Act 2 usually takes about how much of the film?', [['a', '50 %'], ['b', '10 %'], ['c', '90 %']], 'a', 'Setup ~25 %, confrontation ~50 %, resolution ~25 %.'),
    ] },
  { id: 'l1-03', level: 1, title: 'Want versus need', terms: ['want_need', 'character_arc', 'theme'], tags: ['story'],
    scenario: 'A chef wants a Michelin star. She pushes her family away to get it. At the end she cooks a simple meal for her father.',
    steps: [
      s('Her want is…', [['a', 'The Michelin star'], ['b', 'Family connection'], ['c', 'A new restaurant']], 'a', 'The want is the conscious external goal.'),
      s('Her need is…', [['a', 'Connection with her family'], ['b', 'A bigger kitchen'], ['c', 'More money']], 'a', 'The need is the inner lesson.'),
      s('What kind of [[character_arc]] is this?', [['a', 'Positive arc'], ['b', 'Flat arc'], ['c', 'Negative arc']], 'a', 'She trades the want for the need and grows.'),
    ] },
  { id: 'l1-04', level: 1, title: 'Suspense or surprise', terms: ['dramatic_irony', 'tension', 'pov'], tags: ['story'],
    scenario: 'Two friends eat lunch. A bomb is under the table, set for 1:00. The clock shows 12:45.',
    steps: [
      s('If the audience sees the bomb first, the scene gives…', [['a', '15 minutes of suspense'], ['b', '1 second of surprise'], ['c', 'No emotion']], 'a', 'Hitchcock: give the audience information and they worry.'),
      s('This tool is called…', [['a', 'Dramatic irony'], ['b', 'MacGuffin'], ['c', 'Montage']], 'a', 'The audience knows more than the characters: [[dramatic_irony]].'),
      s('To make it stronger, cut to…', [['a', 'Close-ups of the clock between lines'], ['b', 'A wide city shot'], ['c', 'The end credits']], 'a', 'Reminders of the clock raise [[tension]].'),
    ] },
  { id: 'l1-05', level: 1, title: 'Plant and pay off', terms: ['setup_payoff', 'foreshadowing', 'chekhov'], tags: ['story'],
    scenario: 'In act one, a girl practices a magic coin trick and fails. In act three, she must distract a guard.',
    steps: [
      s('The coin trick in act one is a…', [['a', 'Setup'], ['b', 'Payoff'], ['c', 'MacGuffin']], 'a', 'An early plant: [[setup_payoff]].'),
      s('Best payoff in act three?', [['a', 'She does the trick perfectly to distract the guard'], ['b', 'A new character helps her'], ['c', 'The guard falls asleep']], 'a', 'The payoff uses the plant and shows growth.'),
    ] },
  { id: 'l1-06', level: 1, title: 'Four-part structure', terms: ['kishotenketsu', 'plot_twist'], tags: ['story'],
    scenario: 'Ki: a girl waits for a bus in the rain. Shō: she shares an umbrella with a stranger. Ten: the stranger is a forest spirit. Ketsu: ?',
    steps: [
      s('This is which structure?', [['a', 'Kishōtenketsu'], ['b', 'Three-act'], ['c', "Hero's journey"]], 'a', 'Ki-shō-ten-ketsu: intro, development, twist, conclusion.'),
      s('A good Ketsu (conclusion)…', [['a', 'Shows the girl changed by the meeting'], ['b', 'Adds a new villain'], ['c', 'Explains the spirit in dialogue']], 'a', 'Ketsu reconciles the twist with the start.'),
    ] },

  // ───────── L2 Camera & composition
  { id: 'l2-01', level: 2, title: 'Pick the shot size', terms: ['shot_size', 'close_up', 'wide_shot'], tags: ['camera'],
    scenario: 'A soldier reads a letter that says his brother died. We must feel it.',
    steps: [
      s('First shot to set the place?', [['a', 'Wide shot of the camp'], ['b', 'Extreme close-up of an eye'], ['c', 'Insert of the stamp']], 'a', 'A [[wide_shot]] shows where we are.'),
      s('Shot for the moment he understands?', [['a', 'Close-up on his face'], ['b', 'Extreme wide shot'], ['c', 'Bird’s-eye of the camp']], 'a', 'A [[close_up]] shows thought and emotion.'),
      s('Shot that tells the audience what the letter says?', [['a', 'Insert of the letter'], ['b', 'Two shot'], ['c', 'Drone shot']], 'a', 'An [[insert]] gives the key detail.'),
    ] },
  { id: 'l2-02', level: 2, title: 'Lens choice', terms: ['focal_length', 'lens_compression', 'dof'], tags: ['camera'],
    scenario: 'A woman walks in a crowded street. You want her isolated, and the crowd stacked tight behind her.',
    steps: [
      s('Which lens?', [['a', '135 mm telephoto, far away'], ['b', '18 mm wide, close'], ['c', 'Fisheye']], 'a', 'Long lens + distance gives [[lens_compression]].'),
      s('Aperture for isolation?', [['a', 'f/2'], ['b', 'f/16'], ['c', 'f/22']], 'a', 'A wide aperture gives shallow [[dof]].'),
    ] },
  { id: 'l2-03', level: 2, title: 'Keep the line', terms: ['180_rule', 'ots', 'shot_reverse_shot'], tags: ['composition'],
    scenario: 'Anna (left) and Ben (right) argue across a table. You shoot coverage.',
    steps: [
      s('For Anna’s close-up, where is the camera?', [['a', 'Same side of the line, looking at Anna over Ben’s shoulder'], ['b', 'Behind Anna, other side of the line'], ['c', 'Anywhere']], 'a', 'Stay on one side of the [[180_rule|action line]].'),
      s('In Anna’s shot, she looks…', [['a', 'Screen right'], ['b', 'Screen left'], ['c', 'Into the lens']], 'a', 'She sits left, so she looks right toward Ben.'),
      s('How can you cross the line legally?', [['a', 'Move the camera across in one shot, or cut to a neutral shot on the line'], ['b', 'Just cut'], ['c', 'Never']], 'a', 'A visible move or neutral shot resets the line.'),
    ] },
  { id: 'l2-04', level: 2, title: 'Motivate the move', terms: ['camera_movement', 'dolly', 'crane'], tags: ['camera'],
    scenario: 'A detective sees the key clue on the floor and realizes who the killer is.',
    steps: [
      s('Best move for the realization?', [['a', 'Slow push-in (dolly in) to his face'], ['b', 'Random handheld shake'], ['c', 'Pan away to the window']], 'a', 'Pushing in focuses attention on thought.'),
      s('End of the film: he walks away alone. Move?', [['a', 'Crane up and pull back'], ['b', 'Extreme close-up'], ['c', 'Dutch tilt']], 'a', 'A rising pull-back isolates and closes the story.'),
    ] },
  { id: 'l2-05', level: 2, title: 'Exposure math', terms: ['shutter', 'frame_rate', 'exposure_triangle'], tags: ['camera'],
    scenario: 'You shoot at 24 fps with a 180° shutter. It is too bright outside.',
    steps: [
      s('Shutter speed?', [['a', '1/48 s (≈1/50)'], ['b', '1/24 s'], ['c', '1/1000 s']], 'a', '180° = 1/(2 × fps).'),
      s('Best way to cut light but keep the shutter and shallow focus?', [['a', 'Add an ND filter'], ['b', 'Shutter 1/2000'], ['c', 'f/22']], 'a', 'ND reduces light without changing motion blur or depth of field.'),
    ] },
  { id: 'l2-06', level: 2, title: 'Frame the lonely', terms: ['negative_space', 'rule_of_thirds', 'headroom'], tags: ['composition'],
    scenario: 'An old man sits on a bench in a big empty park after his wife’s funeral.',
    steps: [
      s('Composition?', [['a', 'Small in frame, lots of negative space'], ['b', 'Tight close-up, no space'], ['c', 'Centered with a crowd']], 'a', '[[negative_space]] reads as loneliness.'),
      s('He looks left. Put him…', [['a', 'On the right third, space in front of him'], ['b', 'On the left edge, facing the frame edge'], ['c', 'Top of frame']], 'a', 'Give lead room in the direction of the look.'),
    ] },

  // ───────── L3 Light & color
  { id: 'l3-01', level: 3, title: 'Light an interview', terms: ['lighting_three_point', 'key_light', 'fill_light', 'rim_light'], tags: ['lighting'],
    scenario: 'You light a calm documentary interview with three lights.',
    steps: [
      s('The main light, 45° to the side, is the…', [['a', 'Key light'], ['b', 'Fill light'], ['c', 'Back light']], 'a', 'The [[key_light]] sets direction and mood.'),
      s('To soften shadows on the other side, add…', [['a', 'Fill light'], ['b', 'Another key'], ['c', 'Nothing']], 'a', 'The [[fill_light]] controls contrast.'),
      s('To separate dark hair from a dark wall, add…', [['a', 'Rim / back light'], ['b', 'More fill'], ['c', 'A practical lamp in front']], 'a', 'A [[rim_light]] outlines the subject.'),
    ] },
  { id: 'l3-02', level: 3, title: 'Contrast ratio', terms: ['contrast_ratio', 'high_key', 'low_key'], tags: ['lighting'],
    scenario: 'Key light measures f/8. Fill measures f/2.8 (3 stops darker).',
    steps: [
      s('The key-to-fill ratio is about…', [['a', '8:1'], ['b', '2:1'], ['c', '1:1']], 'a', 'Each stop doubles light: 2³ = 8.'),
      s('This look suits…', [['a', 'A noir thriller'], ['b', 'A sitcom'], ['c', 'A shampoo advert']], 'a', 'High ratio = [[low_key]] drama.'),
    ] },
  { id: 'l3-03', level: 3, title: 'Mixed color temperature', terms: ['color_temp', 'white_balance', 'color_contrast'], tags: ['lighting'],
    scenario: 'Night interior. A tungsten lamp (3200 K) lights the face; moonlight from the window is blue.',
    steps: [
      s('Set white balance to…', [['a', '3200 K so the face looks natural'], ['b', '10000 K'], ['c', 'Auto every shot']], 'a', 'Balance for the face; the window stays blue.'),
      s('The result is a…', [['a', 'Warm/cool color contrast'], ['b', 'Monochrome image'], ['c', 'Green cast']], 'a', 'Warm face vs cool background creates depth.'),
    ] },
  { id: 'l3-04', level: 3, title: 'Color script', terms: ['color_script', 'color_meaning', 'symbolism'], tags: ['color'],
    scenario: 'Act 1: a happy family farm. Act 2: the war takes the father. Act 3: the daughter rebuilds the farm.',
    steps: [
      s('Act 1 palette?', [['a', 'Warm, saturated golds'], ['b', 'Grey-blue, low saturation'], ['c', 'Neon pink']], 'a', 'Warmth = safety and love.'),
      s('Act 2 palette?', [['a', 'Desaturated, cool'], ['b', 'Same as act 1'], ['c', 'Bright pastel']], 'a', 'Loss drains color.'),
      s('Act 3 palette?', [['a', 'Warmth returns, with a new accent color'], ['b', 'Black and white'], ['c', 'Same grey as act 2']], 'a', 'A [[color_script]] shows the emotional arc.'),
    ] },
  { id: 'l3-05', level: 3, title: 'Hard or soft', terms: ['hard_soft', 'bounce', 'motivated_light'], tags: ['lighting'],
    scenario: 'A romantic scene by a large north-facing window on a cloudy day.',
    steps: [
      s('This window gives…', [['a', 'Soft light'], ['b', 'Hard light'], ['c', 'No light']], 'a', 'A large diffused source gives soft shadows.'),
      s('You add a lamp. Hide it so light seems to come from…', [['a', 'The window (motivated)'], ['b', 'Nowhere'], ['c', 'The floor']], 'a', '[[motivated_light]] keeps it believable.'),
    ] },

  // ───────── L4 Editing & sound
  { id: 'l4-01', level: 4, title: 'Kuleshov test', terms: ['kuleshov', 'reaction_shot'], tags: ['editing'],
    scenario: 'You have one neutral close-up of an actor. You can cut it next to a coffin, a bowl of soup or a child playing.',
    steps: [
      s('With the coffin, the audience reads…', [['a', 'Grief'], ['b', 'Hunger'], ['c', 'Nothing']], 'a', 'Meaning comes from the next shot.'),
      s('This shows that editing…', [['a', 'Creates meaning between shots'], ['b', 'Only removes mistakes'], ['c', 'Must hide all cuts']], 'a', 'The [[kuleshov]] effect.'),
    ] },
  { id: 'l4-02', level: 4, title: 'Build a chase', terms: ['cross_cutting', 'pacing', 'tension'], tags: ['editing'],
    scenario: 'A train approaches. A girl is tied to the track. The hero rides to save her.',
    steps: [
      s('Edit technique?', [['a', 'Cross-cut between train, girl and hero'], ['b', 'One long take of the girl'], ['c', 'Fade to black']], 'a', '[[cross_cutting]] builds suspense.'),
      s('As the train gets closer, shots get…', [['a', 'Shorter'], ['b', 'Longer'], ['c', 'Same length']], 'a', 'Faster cutting raises energy: [[pacing]].'),
    ] },
  { id: 'l4-03', level: 4, title: 'Smooth dialogue', terms: ['l_cut', 'sound_bridge', 'shot_reverse_shot'], tags: ['editing'],
    scenario: 'Two characters talk. Hard cuts on every line feel mechanical.',
    steps: [
      s('Let A’s voice continue over B’s listening face. This is…', [['a', 'An L-cut'], ['b', 'A jump cut'], ['c', 'A wipe']], 'a', 'Sound trails the picture cut.'),
      s('Why does it help?', [['a', 'We see the reaction while we hear the line'], ['b', 'It hides the actor'], ['c', 'It saves render time']], 'a', 'Reactions carry emotion.'),
    ] },
  { id: 'l4-04', level: 4, title: 'Sound world', terms: ['diegetic', 'foley', 'score', 'silence'], tags: ['sound'],
    scenario: 'A soldier in a trench. A radio plays a song. Then a shell lands close.',
    steps: [
      s('The radio song is…', [['a', 'Diegetic'], ['b', 'Non-diegetic']], 'a', 'The characters can hear it.'),
      s('Right after the blast, a strong choice is…', [['a', 'A high ringing tone and near silence'], ['b', 'Loud happy music'], ['c', 'Narrator voice']], 'a', 'Sudden [[silence]] puts us in his head.'),
      s('His boots in mud were recreated by…', [['a', 'Foley'], ['b', 'ADR'], ['c', 'Score']], 'a', '[[foley]] artists perform sync sounds.'),
    ] },
  { id: 'l4-05', level: 4, title: 'Edit stages', terms: ['assembly', 'color_grading', 'mix'], tags: ['editing'],
    scenario: 'You finish a short film. Put the post steps in order.',
    steps: [
      s('First?', [['a', 'Assembly cut'], ['b', 'Color grade'], ['c', 'Final mix']], 'a', 'Assemble all selected takes in story order.'),
      s('After picture lock?', [['a', 'Color grading and sound mix'], ['b', 'Re-shoot every scene'], ['c', 'Write the script']], 'a', 'Lock timing, then finish color and sound.'),
    ] },

  // ───────── L5 Directing & pipeline
  { id: 'l5-01', level: 5, title: 'Plan the day', terms: ['script_breakdown', 'schedule', 'call_sheet'], tags: ['director'],
    scenario: 'Your script has 3 scenes in the kitchen (scenes 2, 9, 15) and 2 in the forest (scenes 5, 12).',
    steps: [
      s('Shoot order?', [['a', 'All kitchen scenes together, then forest'], ['b', 'Story order 2, 5, 9, 12, 15'], ['c', 'Random']], 'a', 'Group by location to save moves.'),
      s('The daily document for cast and crew is the…', [['a', 'Call sheet'], ['b', 'Logline'], ['c', 'Color script']], 'a', 'The [[call_sheet]] says who, where, when.'),
    ] },
  { id: 'l5-02', level: 5, title: 'Direct the actor', terms: ['actor_direction', 'objective', 'subtext'], tags: ['director'],
    scenario: 'A daughter asks her father for money. The take is flat.',
    steps: [
      s('Best note?', [['a', '“You need him to feel guilty, so he pays.”'], ['b', '“Be more emotional.”'], ['c', '“Say it louder.”']], 'a', 'Give a playable [[objective]].'),
      s('She never says “I am desperate”. The desperation is…', [['a', 'Subtext'], ['b', 'Exposition'], ['c', 'A MacGuffin']], 'a', 'Meaning under the words: [[subtext]].'),
    ] },
  { id: 'l5-03', level: 5, title: 'From board to previs', terms: ['storyboard', 'animatic', 'previs', 'layout'], tags: ['preprod'],
    scenario: 'You plan a 2-minute animated chase.',
    steps: [
      s('First visual step?', [['a', 'Thumbnails and storyboard'], ['b', 'Final render'], ['c', 'Rigging']], 'a', 'Explore cheaply first.'),
      s('Next, to test timing with sound?', [['a', 'Animatic'], ['b', 'Color grade'], ['c', 'Retopology']], 'a', 'An [[animatic]] times the boards.'),
      s('Then, rough 3D cameras with real lenses?', [['a', 'Previs / layout'], ['b', 'Foley'], ['c', 'Compositing']], 'a', '[[previs]] locks cameras before animation.'),
    ] },
  { id: 'l5-04', level: 5, title: 'Get coverage', terms: ['coverage', 'master_shot', 'blocking'], tags: ['director'],
    scenario: 'A 3-person dinner argument. You have half a day.',
    steps: [
      s('Shoot first?', [['a', 'The master shot of the whole scene'], ['b', 'Only close-ups'], ['c', 'Inserts of food']], 'a', 'The [[master_shot]] protects the scene.'),
      s('Before the camera rolls, decide where actors move. This is…', [['a', 'Blocking'], ['b', 'Grading'], ['c', 'Foley']], 'a', '[[blocking]] drives camera placement.'),
    ] },
  { id: 'l5-05', level: 5, title: 'Know your movements', terms: ['new_wave', 'film_noir', 'neorealism'], tags: ['history'],
    scenario: 'Match each style to its movement.',
    steps: [
      s('Jump cuts, handheld, street shooting, rule-breaking (1960)?', [['a', 'French New Wave'], ['b', 'Film noir'], ['c', 'Disney Golden Age']], 'a', 'Godard and Truffaut.'),
      s('Non-actors, real ruins, poverty after the war?', [['a', 'Italian Neorealism'], ['b', 'German Expressionism'], ['c', 'New Hollywood']], 'a', 'E.g. Bicycle Thieves (1948).'),
      s('Low-key light, rain, a femme fatale, fate?', [['a', 'Film noir'], ['b', 'Neorealism'], ['c', 'Kishōtenketsu']], 'a', '1940s American crime films.'),
    ] },
  { id: 'l5-06', level: 5, title: 'Prompt like a DP', terms: ['prompt_shot', 'ai_video', 'consistency'], tags: ['modern'],
    scenario: 'You generate an AI shot: a girl finds a lost robot in a junkyard.',
    steps: [
      s('Best prompt?', [['a', 'Medium close-up, 35 mm, low angle, golden hour backlight, slow push-in, girl kneels and touches a rusty robot, quiet wonder'], ['b', 'cool robot girl'], ['c', 'cinematic, 8k, masterpiece']], 'a', 'Prompt like a shot list: size, lens, angle, light, move, action, mood.'),
      s('Her face changes across shots. Fix?', [['a', 'Use a character reference sheet / identity reference'], ['b', 'Add more adjectives'], ['c', 'Use a higher frame rate']], 'a', '[[consistency]] needs strong references.'),
    ] },

  // ───────── L6 Animation
  { id: 'l6-01', level: 6, title: 'Animate a jump', terms: ['anticipation', 'squash_stretch', 'follow_through'], tags: ['anim_principle'],
    scenario: 'A cartoon cat jumps onto a table.',
    steps: [
      s('Before take-off?', [['a', 'Crouch down (anticipation)'], ['b', 'Freeze'], ['c', 'Jump straight up with no prep']], 'a', '[[anticipation]] stores energy.'),
      s('At take-off the body…', [['a', 'Stretches'], ['b', 'Squashes'], ['c', 'Stays rigid']], 'a', 'Stretch on fast motion, squash on impact.'),
      s('After landing, the tail…', [['a', 'Keeps moving, then settles'], ['b', 'Stops on the same frame'], ['c', 'Disappears']], 'a', '[[follow_through]] on loose parts.'),
    ] },
  { id: 'l6-02', level: 6, title: 'Timing a ball', terms: ['timing', 'spacing', 'slow_in_out', 'bouncing_ball'], tags: ['anim_tech'],
    scenario: 'A rubber ball bounces at 24 fps. Each bounce takes 12 frames.',
    steps: [
      s('Near the top of the arc, spacing is…', [['a', 'Close together (slow)'], ['b', 'Far apart (fast)'], ['c', 'Even']], 'a', 'Gravity slows it at the top: ease in/out.'),
      s('Each bounce lasts how long?', [['a', '0.5 s'], ['b', '1 s'], ['c', '0.12 s']], 'a', '12 / 24 = 0.5 s.'),
      s('A bowling ball, same height, should have…', [['a', 'Almost no squash and fewer bounces'], ['b', 'More squash'], ['c', 'Higher bounces']], 'a', 'Heavy, rigid objects deform less and lose energy fast.'),
    ] },
  { id: 'l6-03', level: 6, title: 'Blocking to polish', terms: ['blocking_anim', 'spline_pass', 'graph_editor', 'interpolation'], tags: ['anim_tech'],
    scenario: 'You animate a 5-second acting shot in Blender.',
    steps: [
      s('First pass interpolation?', [['a', 'Constant (stepped)'], ['b', 'Bézier'], ['c', 'Linear']], 'a', 'Stepped keys show only poses and timing.'),
      s('After the director approves timing, you…', [['a', 'Switch to Bézier and spline'], ['b', 'Render final'], ['c', 'Delete keys']], 'a', 'The [[spline_pass]].'),
      s('In the Graph Editor, a steep curve means…', [['a', 'Fast motion'], ['b', 'A hold'], ['c', 'An error']], 'a', 'Slope = speed.'),
    ] },
  { id: 'l6-04', level: 6, title: 'Walk cycle', terms: ['walk_cycle', 'contact_pose', 'cycle'], tags: ['anim_tech'],
    scenario: 'A normal walk: one step every 12 frames at 24 fps.',
    steps: [
      s('Key pose where the heel touches the ground?', [['a', 'Contact'], ['b', 'Passing'], ['c', 'Up']], 'a', 'The [[contact_pose]] defines the stride.'),
      s('Frames for a full cycle (two steps)?', [['a', '24'], ['b', '12'], ['c', '48']], 'a', 'Two steps × 12 frames.'),
      s('The body is highest in the…', [['a', 'Up pose (after passing)'], ['b', 'Down pose'], ['c', 'Contact pose']], 'a', 'Down after contact, up after passing.'),
    ] },
  { id: 'l6-05', level: 6, title: 'Anime production', terms: ['genga', 'inbetween', 'on_twos', 'limited_animation'], tags: ['anim_tech'],
    scenario: 'A TV anime episode with a small budget.',
    steps: [
      s('Senior animators draw…', [['a', 'Genga (key animation)'], ['b', 'Douga only'], ['c', 'Backgrounds only']], 'a', '原画 = key frames.'),
      s('Most motion is animated on…', [['a', 'Threes or twos'], ['b', 'Ones everywhere'], ['c', 'Sixes']], 'a', 'Fewer drawings per second save cost: [[on_twos]].'),
      s('Holding a pose and moving only the mouth is…', [['a', 'Limited animation'], ['b', 'Rotoscoping'], ['c', 'Stop motion']], 'a', '[[limited_animation]].'),
    ] },
  { id: 'l6-06', level: 6, title: 'Acting beats', terms: ['acting_anim', 'moving_hold', 'line_of_action'], tags: ['anim_tech'],
    scenario: 'A boy hears his dog is lost. He must react, think, then run.',
    steps: [
      s('What moves first?', [['a', 'The eyes'], ['b', 'The feet'], ['c', 'The hair']], 'a', 'Thought shows in the eyes before the body acts.'),
      s('While he thinks, keep him alive with a…', [['a', 'Moving hold'], ['b', 'Frozen frame'], ['c', 'Jump cut']], 'a', 'A [[moving_hold]] drifts slightly.'),
    ] },

  // ───────── L7 Modeling & rigging
  { id: 'l7-01', level: 7, title: 'Model a character head', terms: ['topology', 'edge_loop', 'subdivision', 'pole'], tags: ['modeling'],
    scenario: 'You model a head that will talk and blink.',
    steps: [
      s('Polygon type?', [['a', 'Mostly quads'], ['b', 'Mostly N-gons'], ['c', 'Only triangles']], 'a', 'Quads subdivide and deform best.'),
      s('Around the eyes and mouth, place…', [['a', 'Concentric edge loops'], ['b', 'Random triangles'], ['c', 'Poles']], 'a', 'Loops follow the muscles: [[edge_loop]].'),
      s('Smooth the low-poly cage with…', [['a', 'Subdivision Surface modifier'], ['b', 'Boolean'], ['c', 'Decimate']], 'a', '[[subdivision]] keeps editing light.'),
    ] },
  { id: 'l7-02', level: 7, title: 'Sculpt to game asset', terms: ['sculpting', 'retopology', 'baking', 'normal_map'], tags: ['modeling'],
    scenario: 'You sculpt a 6-million-polygon dragon. It must run in a game.',
    steps: [
      s('Step 1 after the sculpt?', [['a', 'Retopology to a low-poly mesh'], ['b', 'Render'], ['c', 'Rig the sculpt directly']], 'a', 'Build clean, light topology.'),
      s('Step 2?', [['a', 'UV unwrap the low-poly'], ['b', 'Delete the sculpt'], ['c', 'Add Subdivision 4']], 'a', 'Textures need UVs.'),
      s('Step 3, to keep the scales detail?', [['a', 'Bake a normal map from the sculpt'], ['b', 'Increase lights'], ['c', 'Use Freestyle']], 'a', '[[baking]] transfers detail.'),
    ] },
  { id: 'l7-03', level: 7, title: 'Hard-surface panel', terms: ['hard_surface', 'bevel', 'support_loop', 'boolean'], tags: ['modeling'],
    scenario: 'A sci-fi crate with a cut-in vent and sharp but not perfect edges.',
    steps: [
      s('Cut the vent with…', [['a', 'A Boolean difference'], ['b', 'Sculpting'], ['c', 'Shape keys']], 'a', 'Then clean the topology.'),
      s('Edges catch light because of a…', [['a', 'Small bevel'], ['b', 'Bigger texture'], ['c', 'Higher ISO']], 'a', 'Real edges are never razor-sharp.'),
    ] },
  { id: 'l7-04', level: 7, title: 'Rig an arm', terms: ['armature', 'ik', 'fk', 'pole_target', 'skinning'], tags: ['rigging'],
    scenario: 'A character pushes against a wall and later throws a ball.',
    steps: [
      s('Hand fixed on the wall: use…', [['a', 'IK'], ['b', 'FK'], ['c', 'Shape keys']], 'a', '[[ik]] keeps the end fixed.'),
      s('Throwing, with a nice arc from the shoulder: use…', [['a', 'FK'], ['b', 'IK'], ['c', 'Drivers']], 'a', '[[fk]] rotations give natural arcs.'),
      s('Elbow points the wrong way. Set…', [['a', 'A pole target'], ['b', 'More weight paint'], ['c', 'Frame rate']], 'a', 'The [[pole_target]] aims the bend.'),
    ] },
  { id: 'l7-05', level: 7, title: 'Face setup', terms: ['shape_keys', 'drivers', 'facial_rig', 'lip_sync'], tags: ['rigging'],
    scenario: 'A cartoon character must talk and smile.',
    steps: [
      s('Store mouth shapes (A, O, M) as…', [['a', 'Shape keys'], ['b', 'Bones only'], ['c', 'Textures']], 'a', 'Blend shapes mix with sliders.'),
      s('A single slider opens the jaw and the mouth together using…', [['a', 'Drivers'], ['b', 'Booleans'], ['c', 'HDRI']], 'a', '[[drivers]] link properties.'),
    ] },

  // ───────── L8 Blender flow
  { id: 'l8-01', level: 8, title: 'First Blender scene', terms: ['grs', 'apply_transform', 'edit_mode', 'modifier'], tags: ['blender'],
    scenario: 'You make a table from a cube and add a bevel.',
    steps: [
      s('Scale the cube flat: press…', [['a', 'S, Z, 0.1'], ['b', 'G, X'], ['c', 'R, Y, 90']], 'a', 'S scales; Z locks the axis.'),
      s('The bevel looks uneven. First…', [['a', 'Apply scale (Ctrl+A)'], ['b', 'Add more samples'], ['c', 'Change the HDRI']], 'a', 'Modifiers read unapplied scale.'),
      s('To move vertices, switch with…', [['a', 'Tab (Edit Mode)'], ['b', 'F12'], ['c', 'Ctrl+Space']], 'a', 'Edit Mode changes the mesh.'),
    ] },
  { id: 'l8-02', level: 8, title: 'A wet metal material', terms: ['principled_bsdf', 'pbr', 'texture_map'], tags: ['blender'],
    scenario: 'A rusty iron pipe in the rain.',
    steps: [
      s('Shader to start with?', [['a', 'Principled BSDF'], ['b', 'Emission only'], ['c', 'Holdout']], 'a', 'One physically based shader.'),
      s('Metallic value for clean iron?', [['a', '1.0'], ['b', '0.0'], ['c', '0.5 always']], 'a', 'Metals are 1; rust parts drop to 0 via a mask.'),
      s('Wet areas need…', [['a', 'Lower roughness'], ['b', 'Higher roughness'], ['c', 'More subdivision']], 'a', 'Water makes surfaces glossy.'),
    ] },
  { id: 'l8-03', level: 8, title: 'Choose the engine', terms: ['render_engine', 'eevee', 'cycles', 'samples_noise'], tags: ['blender'],
    scenario: 'You need a 2-minute anime-style short in 5 days, and one photoreal glass product shot.',
    steps: [
      s('Anime short?', [['a', 'EEVEE with toon shading'], ['b', 'Cycles at 4096 samples'], ['c', 'Workbench']], 'a', 'Real-time, stylized, fast.'),
      s('Glass product shot?', [['a', 'Cycles'], ['b', 'EEVEE only'], ['c', 'Grease Pencil']], 'a', 'Path tracing handles refraction and caustics.'),
      s('Cycles image is grainy. Cheapest fix?', [['a', 'Turn on denoising'], ['b', 'Double resolution'], ['c', 'Add more lights']], 'a', 'Denoise first, then add samples if needed.'),
    ] },
  { id: 'l8-04', level: 8, title: 'Camera like a DP', terms: ['camera_blender', 'dof', 'camera_rig', 'markers'], tags: ['blender'],
    scenario: 'A dialogue scene in Blender with two cameras.',
    steps: [
      s('Get real depth of field in the camera by…', [['a', 'Enable Depth of Field, set focus object and f-stop'], ['b', 'Blur in Photoshop'], ['c', 'Lower samples']], 'a', 'Blender cameras use real f-stops.'),
      s('Cut between the two cameras in one scene with…', [['a', 'Timeline markers bound to cameras (Ctrl+B)'], ['b', 'Two files'], ['c', 'Shape keys']], 'a', '[[markers]] switch the active camera.'),
    ] },
  { id: 'l8-05', level: 8, title: 'Render and deliver', terms: ['output_settings', 'view_layer', 'compositor', 'render_farm'], tags: ['blender'],
    scenario: 'A 1000-frame shot that will be color graded later.',
    steps: [
      s('Output format?', [['a', 'OpenEXR image sequence'], ['b', 'MP4 directly'], ['c', 'GIF']], 'a', 'EXR keeps range; sequences resume after a crash.'),
      s('To adjust the glow later without re-render, render…', [['a', 'Separate passes / view layers'], ['b', 'One flat image'], ['c', 'At 10 % resolution']], 'a', 'Passes feed the [[compositor]].'),
      s('Render without the UI from a terminal:', [['a', 'blender -b file.blend -a'], ['b', 'blender --ui'], ['c', 'ffmpeg -i file.blend']], 'a', 'Background mode for farms and servers.'),
    ] },

  // ───────── Scene checks (single-step)
  { id: "s2-01", level: 2, title: "On set: Camera Angle", terms: ["camera_angle"], tags: ["camera"],
    scenario: "Your hero must look powerful as she enters the throne room. Which angle?",
    steps: [s('What is the best call?', [["a", "High angle"], ["b", "Low angle"], ["c", "Bird's-eye"], ["d", "Dutch angle"]], "b", "A low angle makes the subject look big and strong. See [[camera_angle]].")] },
  { id: "s2-02", level: 2, title: "On set: 180-Degree Rule", terms: ["180_rule"], tags: ["composition"],
    scenario: "Two actors talk at a table. Shot A shows A on the left; in shot B, A now looks from the left too. What broke?",
    steps: [s('What is the best call?', [["a", "Rule of thirds"], ["b", "180-degree rule"], ["c", "Kuleshov effect"], ["d", "Headroom"]], "b", "The camera crossed the action line, so screen sides flipped. See [[180_rule]].")] },
  { id: "s1-01", level: 1, title: "On set: Dramatic Irony / Suspense", terms: ["dramatic_irony"], tags: ["story"],
    scenario: "You need the audience to feel the villain's bomb is ticking while the heroes chat. Best tool?",
    steps: [s('What is the best call?', [["a", "Show the bomb first (dramatic irony)"], ["b", "Hide the bomb until it explodes"], ["c", "Use a jump cut"], ["d", "Use high-key light"]], "a", "Hitchcock: give the audience information, and surprise becomes suspense. See [[dramatic_irony]].")] },
  { id: "s6-01", level: 6, title: "On set: Bouncing Ball Exercise", terms: ["bouncing_ball"], tags: ["anim_tech"],
    scenario: "Your bouncing ball looks floaty. What do you change first?",
    steps: [s('What is the best call?', [["a", "Add more color"], ["b", "Fix timing and spacing (faster fall, ease at top)"], ["c", "Add rim light"], ["d", "Add more polygons"]], "b", "Gravity is a timing/spacing problem: slow at the top, fast at the bottom. See [[bouncing_ball]].")] },
  { id: "s6-02", level: 6, title: "On set: Arcs", terms: ["arcs"], tags: ["anim_principle"],
    scenario: "A character's arm swings in a straight line between keys. Which principle is missing?",
    steps: [s('What is the best call?', [["a", "Arcs"], ["b", "Appeal"], ["c", "Staging"], ["d", "Exaggeration"]], "a", "Natural joints rotate, so motion follows arcs. See [[arcs]].")] },
  { id: "s8-01", level: 8, title: "On set: Noise / Fireflies", terms: ["noise"], tags: ["blender"],
    scenario: "Your Cycles render has bright white dots on dark walls. Fix?",
    steps: [s('What is the best call?', [["a", "Lower resolution"], ["b", "Clamp indirect light / add denoising"], ["c", "Switch to Constant interpolation"], ["d", "Add Mirror modifier"]], "b", "Fireflies come from strong indirect paths; clamp and denoise. See [[noise]].")] },
  { id: "s7-01", level: 7, title: "On set: Topology", terms: ["topology"], tags: ["modeling"],
    scenario: "Model shows dents and pinches after Subdivision. Most likely cause?",
    steps: [s('What is the best call?', [["a", "Bad topology / poles / N-gons"], ["b", "Wrong frame rate"], ["c", "Missing HDRI"], ["d", "Low ISO"]], "a", "Subdivision exposes poor edge flow and N-gons. See [[topology]].")] },
  { id: "s8-02", level: 8, title: "On set: Apply Transform (Ctrl+A)", terms: ["apply_transform"], tags: ["blender"],
    scenario: "You scaled a cube to 3 in Object Mode and the bevel looks stretched. Fix?",
    steps: [s('What is the best call?', [["a", "Apply scale (Ctrl+A)"], ["b", "Add more samples"], ["c", "Use Rack focus"], ["d", "Flip normals"]], "a", "Modifiers read unapplied scale; apply transforms. See [[apply_transform]].")] },
  { id: "s2-03", level: 2, title: "On set: Dolly Zoom (Vertigo Effect)", terms: ["dolly_zoom"], tags: ["camera"],
    scenario: "You want a dream-like scene where background stretches while the face stays the same size.",
    steps: [s('What is the best call?', [["a", "Dolly zoom"], ["b", "Whip pan"], ["c", "Crane up"], ["d", "Jump cut"]], "a", "The Vertigo effect counters dolly and zoom. See [[dolly_zoom]].")] },
  { id: "s4-01", level: 4, title: "On set: Kuleshov Effect", terms: ["kuleshov"], tags: ["editing"],
    scenario: "The editor cuts from a hungry man's neutral face to soup. Viewers say he looks hungry. This is:",
    steps: [s('What is the best call?', [["a", "Kuleshov effect"], ["b", "Match cut"], ["c", "J-cut"], ["d", "Foley"]], "a", "Meaning comes from the juxtaposition of shots. See [[kuleshov]].")] },
  { id: "s4-02", level: 4, title: "On set: Sound Bridge", terms: ["sound_bridge"], tags: ["sound"],
    scenario: "Next scene's music begins under the last line of this scene. Name?",
    steps: [s('What is the best call?', [["a", "Smash cut"], ["b", "Sound bridge / J-cut"], ["c", "Jump cut"], ["d", "Insert"]], "b", "Sound leading picture links scenes smoothly. See [[sound_bridge]].")] },
  { id: "s7-02", level: 7, title: "On set: Inverse Kinematics (IK)", terms: ["ik"], tags: ["rigging"],
    scenario: "Animator wants feet to stay planted while the hips move. Which rig mode?",
    steps: [s('What is the best call?', [["a", "FK"], ["b", "IK"], ["c", "Shape keys"], ["d", "Drivers"]], "b", "IK keeps the end effector fixed while the chain solves. See [[ik]].")] },
  { id: "s7-03", level: 7, title: "On set: Pole Target", terms: ["pole_target"], tags: ["rigging"],
    scenario: "Your knee flips sideways in IK. What controls its direction?",
    steps: [s('What is the best call?', [["a", "Pole target"], ["b", "Bone roll only"], ["c", "Vertex group"], ["d", "Weight paint"]], "a", "A pole target tells the IK chain which way to bend. See [[pole_target]].")] },
  { id: "s2-04", level: 2, title: "On set: Negative Space", terms: ["negative_space"], tags: ["composition"],
    scenario: "The shot is a lonely character in a big empty frame. What technique?",
    steps: [s('What is the best call?', [["a", "Negative space"], ["b", "Deep focus"], ["c", "Insert shot"], ["d", "Over-the-shoulder"]], "a", "Empty space around a subject reads as isolation. See [[negative_space]].")] },
  { id: "s3-01", level: 3, title: "On set: Low-Key Lighting", terms: ["low_key"], tags: ["lighting"],
    scenario: "Noir detective scene: dark room, blinds, hard shadows. Lighting style?",
    steps: [s('What is the best call?', [["a", "High-key"], ["b", "Low-key"], ["c", "Flat"], ["d", "Bounce only"]], "b", "Low-key light with hard shadows is the noir signature. See [[low_key]].")] },
  { id: "s8-03", level: 8, title: "On set: EEVEE", terms: ["eevee"], tags: ["blender"],
    scenario: "You want fast previews with toon shading and outlines. Engine?",
    steps: [s('What is the best call?', [["a", "EEVEE"], ["b", "Cycles"], ["c", "Workbench only"], ["d", "None"]], "a", "EEVEE is real-time and supports Shader to RGB for toon bands. See [[eevee]].")] },
  { id: "s1-02", level: 1, title: "On set: Show, Don't Tell", terms: ["show_dont_tell"], tags: ["story"],
    scenario: "A writer explains the hero's sadness in dialogue: 'I am very sad because my father died.' Advice?",
    steps: [s('What is the best call?', [["a", "Show, don't tell"], ["b", "Add more exposition"], ["c", "Use a montage of text"], ["d", "Use a dutch angle"]], "a", "Show grief through action and image, not a statement. See [[show_dont_tell]].")] },
  { id: "s1-03", level: 1, title: "On set: Chekhov's Gun", terms: ["chekhov"], tags: ["story"],
    scenario: "Gun shown in act one never fires. Which rule did the writer break?",
    steps: [s('What is the best call?', [["a", "Chekhov's gun"], ["b", "Kishōtenketsu"], ["c", "Rule of thirds"], ["d", "Kuleshov"]], "a", "Every planted element must pay off. See [[chekhov]].")] },
  { id: "s1-04", level: 1, title: "On set: Kishōtenketsu", terms: ["kishotenketsu"], tags: ["story"],
    scenario: "A Japanese 4-part story with a twist but no villain. Structure?",
    steps: [s('What is the best call?', [["a", "Three-act"], ["b", "Kishōtenketsu"], ["c", "Hero's journey"], ["d", "Save the Cat"]], "b", "Ki-shō-ten-ketsu turns on a twist, not on conflict. See [[kishotenketsu]].")] },
  { id: "s2-05", level: 2, title: "On set: Shutter Speed / 180° Rule", terms: ["shutter"], tags: ["camera"],
    scenario: "You film at 24 fps. Natural motion blur shutter speed?",
    steps: [s('What is the best call?', [["a", "1/24"], ["b", "1/48"], ["c", "1/500"], ["d", "1/12"]], "b", "180° shutter = 1/(2×fps). See [[shutter]].")] },
  { id: "s6-03", level: 6, title: "On set: Anticipation", terms: ["anticipation"], tags: ["anim_principle"],
    scenario: "Animation of a character jumping without crouching first feels weak. Add?",
    steps: [s('What is the best call?', [["a", "Anticipation"], ["b", "Moving hold"], ["c", "Secondary action"], ["d", "Slow out"]], "a", "Anticipation prepares and sells the force. See [[anticipation]].")] },
  { id: "s6-04", level: 6, title: "On set: Follow Through & Overlapping Action", terms: ["follow_through"], tags: ["anim_principle"],
    scenario: "Hair keeps moving after the head stops. Principle?",
    steps: [s('What is the best call?', [["a", "Follow through & overlap"], ["b", "Solid drawing"], ["c", "Staging"], ["d", "Straight ahead"]], "a", "Loose parts continue and settle after the main body stops. See [[follow_through]].")] },
  { id: "s6-05", level: 6, title: "On set: Twinning", terms: ["twinning"], tags: ["anim_tech"],
    scenario: "Both arms of your pose rise identically at the same time. Problem?",
    steps: [s('What is the best call?', [["a", "Twinning"], ["b", "Smear"], ["c", "Drag"], ["d", "Arc"]], "a", "Mirror symmetry looks stiff; offset and vary. See [[twinning]].")] },
  { id: "s3-02", level: 3, title: "On set: Silhouette", terms: ["silhouette"], tags: ["lighting"],
    scenario: "You want the audience to read a pose even in black silhouette.",
    steps: [s('What is the best call?', [["a", "Strong silhouette / line of action"], ["b", "More texture"], ["c", "More subdivision"], ["d", "Higher ISO"]], "a", "Clear silhouette = clear staging. See [[silhouette]].")] },
  { id: "s5-01", level: 5, title: "On set: Staging in Depth", terms: ["staging"], tags: ["director"],
    scenario: "A dinner scene needs to show three people's tension in one image without cuts.",
    steps: [s('What is the best call?', [["a", "Staging in depth"], ["b", "Insert"], ["c", "Jump cut"], ["d", "Pan only"]], "a", "Foreground/background staging tells relationships in one frame. See [[staging]].")] },
  { id: "s8-04", level: 8, title: "On set: Baking", terms: ["baking"], tags: ["blender"],
    scenario: "Your low-poly game model must show sculpted wrinkles.",
    steps: [s('What is the best call?', [["a", "Bake a normal map"], ["b", "Add Subdivision level 6"], ["c", "Use Freestyle"], ["d", "Use more lights"]], "a", "Normal maps store high-poly detail on low-poly surfaces. See [[baking]].")] },
  { id: "s8-05", level: 8, title: "On set: Texture Maps", terms: ["texture_map"], tags: ["blender"],
    scenario: "Which texture should use Non-Color data?",
    steps: [s('What is the best call?', [["a", "Base color"], ["b", "Roughness"], ["c", "Both"], ["d", "None"]], "b", "Data maps (roughness, normal, metallic) must not be color-managed. See [[texture_map]].")] },
  { id: "s5-02", level: 5, title: "On set: Color Script", terms: ["color_script"], tags: ["preprod"],
    scenario: "Shots in a sequence should feel hot and tense, then cold and lonely. Planning document?",
    steps: [s('What is the best call?', [["a", "Color script"], ["b", "Call sheet"], ["c", "Slate"], ["d", "Stripboard"]], "a", "A color script maps color emotion across the film. See [[color_script]].")] },
  { id: "s5-03", level: 5, title: "On set: Animatic / Story Reel", terms: ["animatic"], tags: ["preprod"],
    scenario: "Your animatic shows the action scene is boring. Cheapest place to fix?",
    steps: [s('What is the best call?', [["a", "In the animatic"], ["b", "After final render"], ["c", "In color grading"], ["d", "During mix"]], "a", "Fix story and pacing early; changes cost more later. See [[animatic]].")] },
  { id: "s5-04", level: 5, title: "On set: Directing Actors", terms: ["actor_direction"], tags: ["director"],
    scenario: "Actor note: 'Be angrier.' Better note?",
    steps: [s('What is the best call?', [["a", "'Make him leave the room.' (action verb)"], ["b", "'Cry more.'"], ["c", "'Be louder.'"], ["d", "'Do it faster.'"]], "a", "Give playable objectives, not result emotions. See [[actor_direction]].")] },
  { id: "s5-05", level: 5, title: "On set: Pillow Shot", terms: ["pillow_shot"], tags: ["history"],
    scenario: "Ozu cuts to an empty street between scenes. Name?",
    steps: [s('What is the best call?', [["a", "Pillow shot"], ["b", "Cutaway insert"], ["c", "Smash cut"], ["d", "Master shot"]], "a", "Pillow shots give rest and atmosphere. See [[pillow_shot]].")] },
  { id: "s6-06", level: 6, title: "On set: On Ones / On Twos / Threes", terms: ["on_twos"], tags: ["anim_tech"],
    scenario: "Spider-Verse animates characters at 12 fps inside 24 fps. Term?",
    steps: [s('What is the best call?', [["a", "On twos"], ["b", "Frame interpolation"], ["c", "Slow motion"], ["d", "Limited budget only"]], "a", "New drawing every 2 frames = on twos. See [[on_twos]].")] },
  { id: "s8-06", level: 8, title: "On set: NLA Editor", terms: ["nla"], tags: ["blender"],
    scenario: "Which Blender editor stacks and blends whole actions like clips?",
    steps: [s('What is the best call?', [["a", "NLA Editor"], ["b", "Graph Editor"], ["c", "Outliner"], ["d", "Compositor"]], "a", "Non-Linear Animation editor works with action strips. See [[nla]].")] },
  { id: "s8-07", level: 8, title: "On set: Timeline Markers & Camera Switching", terms: ["markers"], tags: ["blender"],
    scenario: "Cut between multiple cameras inside one Blender scene by:",
    steps: [s('What is the best call?', [["a", "Binding cameras to timeline markers"], ["b", "Adding a LUT"], ["c", "Using Rigify"], ["d", "Weight painting"]], "a", "Ctrl+B in the timeline binds the active camera to a marker. See [[markers]].")] },
  { id: "s8-08", level: 8, title: "On set: Output Settings", terms: ["output_settings"], tags: ["blender"],
    scenario: "Render failed at frame 800 of 1000 as MP4. Better workflow?",
    steps: [s('What is the best call?', [["a", "Render image sequence (PNG/EXR), then encode"], ["b", "Render lower samples"], ["c", "Use EEVEE only"], ["d", "Use NLA"]], "a", "Image sequences let you resume; encode with ffmpeg after. See [[output_settings]].")] },
  { id: "s4-03", level: 4, title: "On set: Pacing & Rhythm", terms: ["pacing"], tags: ["editing"],
    scenario: "Scene feels too long but each shot is good. Editor's main tool?",
    steps: [s('What is the best call?', [["a", "Pacing — trim shot length"], ["b", "More coverage"], ["c", "Add Foley"], ["d", "Change aspect ratio"]], "a", "Rhythm and length control energy. See [[pacing]].")] },
  { id: "s4-04", level: 4, title: "On set: Rule of Six (Murch)", terms: ["murch_rule"], tags: ["editing"],
    scenario: "The best cut, by Walter Murch, first serves:",
    steps: [s('What is the best call?', [["a", "Emotion"], ["b", "3D space"], ["c", "Eye trace"], ["d", "2D plane"]], "a", "Emotion is 51 % of his Rule of Six. See [[murch_rule]].")] },
  { id: "s3-03", level: 3, title: "On set: Rim / Back Light", terms: ["rim_light"], tags: ["lighting"],
    scenario: "You need a strong separation of a dark-haired actor from a dark background.",
    steps: [s('What is the best call?', [["a", "Rim / back light"], ["b", "More fill"], ["c", "Lower key"], ["d", "Green screen"]], "a", "Back light outlines the subject. See [[rim_light]].")] },
  { id: "s7-04", level: 7, title: "On set: Shape Language", terms: ["shape_language"], tags: ["modeling"],
    scenario: "Friendly round character vs. spiky villain is an example of:",
    steps: [s('What is the best call?', [["a", "Shape language"], ["b", "Topology"], ["c", "Retopology"], ["d", "Value structure"]], "a", "Shapes carry emotional meaning. See [[shape_language]].")] },
  { id: "s7-05", level: 7, title: "On set: Retopology", terms: ["retopology"], tags: ["modeling"],
    scenario: "Your sculpt has 5 million polygons; animator needs a clean mesh. Step?",
    steps: [s('What is the best call?', [["a", "Retopology"], ["b", "Boolean"], ["c", "Inset"], ["d", "Extrude"]], "a", "Build animation-ready low-poly over the sculpt. See [[retopology]].")] },
  { id: "s4-05", level: 4, title: "On set: Cross-Cutting / Parallel Editing", terms: ["cross_cutting"], tags: ["editing"],
    scenario: "Two actions in different places at the same time: rescue and ticking clock.",
    steps: [s('What is the best call?', [["a", "Cross-cutting"], ["b", "Dissolve"], ["c", "Jump cut"], ["d", "Long take"]], "a", "Parallel editing builds suspense. See [[cross_cutting]].")] },
  { id: "s2-06", level: 2, title: "On set: Long Take / Oner", terms: ["long_take"], tags: ["camera"],
    scenario: "A scene plays with no cut for 3 minutes while the camera follows the hero.",
    steps: [s('What is the best call?', [["a", "Long take / oner"], ["b", "Montage"], ["c", "Kuleshov"], ["d", "Insert"]], "a", "An unbroken take builds immersion. See [[long_take]].")] },
  { id: "s1-05", level: 1, title: "On set: MacGuffin", terms: ["macguffin"], tags: ["story"],
    scenario: "The story goal is a briefcase whose content is never shown (Pulp Fiction).",
    steps: [s('What is the best call?', [["a", "MacGuffin"], ["b", "Motif"], ["c", "Leitmotif"], ["d", "Theme"]], "a", "The MacGuffin matters only because characters want it. See [[macguffin]].")] },
  { id: "s6-07", level: 6, title: "On set: 12 Principles of Animation", terms: ["twelve_principles"], tags: ["anim_principle"],
    scenario: "Which one is NOT one of Disney's 12 principles?",
    steps: [s('What is the best call?', [["a", "Appeal"], ["b", "Arcs"], ["c", "Rule of thirds"], ["d", "Timing"]], "c", "Rule of thirds is a composition rule. See [[twelve_principles]].")] },
  { id: "s6-08", level: 6, title: "On set: Blocking (Animation)", terms: ["blocking_anim"], tags: ["anim_tech"],
    scenario: "Keys set in Stepped/Constant interpolation are used during:",
    steps: [s('What is the best call?', [["a", "Blocking pass"], ["b", "Final render"], ["c", "Retopology"], ["d", "Grading"]], "a", "Stepped keys show only poses to judge timing. See [[blocking_anim]].")] },
  { id: "s6-09", level: 6, title: "On set: Graph Editor (F-Curves)", terms: ["graph_editor"], tags: ["anim_tech"],
    scenario: "A flat curve in the Graph Editor means the value is:",
    steps: [s('What is the best call?', [["a", "Not changing (hold)"], ["b", "Very fast"], ["c", "Random"], ["d", "Looping"]], "a", "Slope is speed; flat = no change. See [[graph_editor]].")] },
  { id: "s3-04", level: 3, title: "On set: Color Temperature", terms: ["color_temp"], tags: ["lighting"],
    scenario: "Sunlight at 5600 K and tungsten lamp at 3200 K in one shot. Lamp looks:",
    steps: [s('What is the best call?', [["a", "Orange/warm"], ["b", "Blue"], ["c", "Green"], ["d", "Neutral"]], "a", "Lower Kelvin = warmer light. See [[color_temp]].")] },
  { id: "s3-05", level: 3, title: "On set: High-Key Lighting", terms: ["high_key"], tags: ["lighting"],
    scenario: "For a big comedic musical number, choose lighting:",
    steps: [s('What is the best call?', [["a", "High-key"], ["b", "Low-key"], ["c", "Chiaroscuro"], ["d", "Silhouette"]], "a", "High-key is bright and cheerful. See [[high_key]].")] },
  { id: "s7-06", level: 7, title: "On set: UV Seams", terms: ["seams"], tags: ["modeling"],
    scenario: "Where should you mark UV seams?",
    steps: [s('What is the best call?', [["a", "In hidden areas like under arms"], ["b", "On the face center"], ["c", "Random"], ["d", "Nowhere"]], "a", "Seams show texture breaks; hide them. See [[seams]].")] },
  { id: "s7-07", level: 7, title: "On set: Normals", terms: ["normals"], tags: ["modeling"],
    scenario: "A model's faces render black from one side. Check:",
    steps: [s('What is the best call?', [["a", "Normals"], ["b", "Frame rate"], ["c", "LUT"], ["d", "Aperture"]], "a", "Flipped normals cause dark or missing shading. See [[normals]].")] },
  { id: "s7-08", level: 7, title: "On set: Array / Curve Modifier", terms: ["array_mod"], tags: ["modeling"],
    scenario: "Make a chain of 50 identical links along a path quickly:",
    steps: [s('What is the best call?', [["a", "Array + Curve modifiers"], ["b", "Sculpt each"], ["c", "Boolean"], ["d", "Retopology"]], "a", "Arrays repeat; Curve modifier bends. See [[array_mod]].")] },
  { id: "s5-06", level: 5, title: "On set: Prompting as Shot Design", terms: ["prompt_shot"], tags: ["modern"],
    scenario: "You write a prompt for an AI video shot. Best structure?",
    steps: [s('What is the best call?', [["a", "Subject, action, shot size, lens, light, camera move, mood"], ["b", "Only 'cool scene'"], ["c", "Only the style name"], ["d", "Only the lens"]], "a", "Prompt like a shot list for control. See [[prompt_shot]].")] },
  { id: "s5-07", level: 5, title: "On set: Character Consistency", terms: ["consistency"], tags: ["modern"],
    scenario: "Character's face changes between AI-generated shots. Fix?",
    steps: [s('What is the best call?', [["a", "Use reference sheets / identity conditioning"], ["b", "Raise frame rate"], ["c", "Add Foley"], ["d", "Use dutch angle"]], "a", "Consistency needs strong references. See [[consistency]].")] },
  { id: "s6-10", level: 6, title: "On set: Key Animation (Genga)", terms: ["genga"], tags: ["anim_tech"],
    scenario: "In anime production, who draws the key frames?",
    steps: [s('What is the best call?', [["a", "Genga (key animator)"], ["b", "Douga (in-between)"], ["c", "Shiage (paint)"], ["d", "Satsuei (compositing)"]], "a", "原画 draws keys; 動画 draws in-betweens. See [[genga]].")] },
  { id: "s2-07", level: 2, title: "On set: Crane / Jib", terms: ["crane"], tags: ["camera"],
    scenario: "Which camera move best 'reveals' a whole city at the end?",
    steps: [s('What is the best call?', [["a", "Crane / drone pull up"], ["b", "Insert"], ["c", "Rack focus"], ["d", "Dutch angle"]], "a", "Rising moves reveal scale and close stories. See [[crane]].")] },
  { id: "s4-06", level: 4, title: "On set: Foley", terms: ["foley"], tags: ["sound"],
    scenario: "Footsteps in the film were recorded in a studio with shoes on gravel.",
    steps: [s('What is the best call?', [["a", "Foley"], ["b", "ADR"], ["c", "Score"], ["d", "Room tone"]], "a", "Foley artists recreate sync sounds. See [[foley]].")] },
  { id: "s4-07", level: 4, title: "On set: Ambience / Room Tone", terms: ["ambience"], tags: ["sound"],
    scenario: "Why record 30 seconds of silence on set?",
    steps: [s('What is the best call?', [["a", "Room tone to fill gaps in edit"], ["b", "For the slate"], ["c", "To test ISO"], ["d", "To set white balance"]], "a", "Room tone hides cuts in the dialogue track. See [[ambience]].")] },
  { id: "s5-08", level: 5, title: "On set: Objective / Action Verb", terms: ["objective"], tags: ["director"],
    scenario: "Main action of the hero in a scene: she tries to 'charm' the guard. This verb is the:",
    steps: [s('What is the best call?', [["a", "Objective / action"], ["b", "Logline"], ["c", "Motif"], ["d", "Slugline"]], "a", "Actors play verbs toward another character. See [[objective]].")] },
  { id: "s1-06", level: 1, title: "On set: Want vs Need", terms: ["want_need"], tags: ["story"],
    scenario: "The hero's arc trades getting rich (want) for learning to love (need).",
    steps: [s('What is the best call?', [["a", "Want vs need"], ["b", "MacGuffin"], ["c", "Inciting incident"], ["d", "Midpoint"]], "a", "Strong arcs exchange external want for inner need. See [[want_need]].")] },
  { id: "s1-07", level: 1, title: "On set: Inciting Incident", terms: ["inciting_incident"], tags: ["story"],
    scenario: "Event that ends the hero's normal world and starts the plot:",
    steps: [s('What is the best call?', [["a", "Inciting incident"], ["b", "Climax"], ["c", "Resolution"], ["d", "Denouement"]], "a", "It launches the dramatic question. See [[inciting_incident]].")] },
]
