import type { Scene, Step } from '../shared/types'

// Virtual scenes. Each one is a short story context; the learner builds it department by department.
// `ref` names a real film that uses the same tools, to watch afterwards.
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({
  prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why,
})

export const SCENES: Scene[] = [
  {
    id: 'rooftop-goodbye', title: 'Goodbye on the rooftop', genre: 'Drama',
    setup: 'Night. Mei (17) tells her best friend Ken she moves to another country tomorrow. Ken has loved her for years and never said it. They stand on the school roof; the city lights are behind them.',
    goal: 'The audience must feel what Ken does not say.',
    terms: ['subtext', 'ots', 'close_up', 'motivated_light', 'silence', 'l_cut'], tags: ['dialogue', 'emotion'],
    checkpoints: [
      { label: 'Story beat', dept: 'story', context: 'Ken’s line is written as: “I love you, don’t go.”',
        step: s('How do you rewrite the line?', [['a', 'Ken says “Send me photos of the sea.” and looks away'], ['b', 'Keep it; say the feeling clearly'], ['c', 'Add a narrator who explains his love']], 'a', 'Feeling under the words is [[subtext]]. The audience fills the gap and feels it more.') },
      { label: 'Coverage', dept: 'camera', context: 'Mei stands left, Ken right. You have time for three setups.',
        step: s('Which three setups?', [['a', 'Wide two-shot with the city, then over-the-shoulder on each, same side of the line'], ['b', 'Three drone shots'], ['c', 'Handheld shots from both sides of the line']], 'a', 'A [[master_shot]], then [[ots]] coverage, and keep the [[180_rule]].') },
      { label: 'Key shot', dept: 'camera', context: 'Mei says “I leave tomorrow.”',
        step: s('Whose face do you hold on?', [['a', 'Ken’s, in a slow push to close-up while he does not answer'], ['b', 'Mei’s back'], ['c', 'An insert of her shoes']], 'a', 'The emotion is in the listener: a [[reaction_shot]] and a [[close_up]].') },
      { label: 'Light', dept: 'lighting', context: 'There is no lamp on the roof. The city is far.',
        step: s('Where does the light come from?', [['a', 'A soft cool key from “the city”, a warm rim from a stairwell door'], ['b', 'Bright flat light from the front'], ['c', 'A red light on the floor']], 'a', 'The light must seem real: [[motivated_light]], with [[color_contrast]] between them.') },
      { label: 'Sound', dept: 'sound', context: 'After Mei’s line, the music swells in the temp edit.',
        step: s('What do you do with the sound?', [['a', 'Drop the music; keep distant traffic and wind'], ['b', 'Make the music louder'], ['c', 'Add a laugh track']], 'a', '[[silence]] makes the unsaid line heavy.') },
      { label: 'Edit', dept: 'editing', context: 'Next scene: Mei at the airport the next morning.',
        step: s('How do you go to the airport?', [['a', 'Let the airport announcement start over Ken’s silent face (J-cut)'], ['b', 'Star wipe'], ['c', 'Fade to white for 5 seconds']], 'a', 'Sound leads the cut: [[l_cut]] / [[sound_bridge]].') },
    ],
    outcome: 'Every choice protects the [[subtext]]: the line hides the feeling, the camera stays on the listener, light and sound stay quiet, and the edit pulls us forward before Ken can speak.',
    ref: 'Lost in Translation (2003), the last scene',
  },
  {
    id: 'kitchen-intruder', title: 'Someone in the kitchen', genre: 'Thriller',
    setup: 'A woman lives alone. At 2 a.m. she hears a glass break downstairs. She takes a torch and goes to the kitchen. The intruder is real, but the audience does not know that yet.',
    goal: 'Maximum suspense for 60 seconds, then a shock.',
    terms: ['dramatic_irony', 'low_key', 'pov_shot', 'pacing', 'smash_cut', 'negative_space'], tags: ['suspense'],
    checkpoints: [
      { label: 'Information', dept: 'story', context: 'You can show the intruder to the audience first, or hide him.',
        step: s('For suspense, what do you show first?', [['a', 'A brief shot of a shadow behind the fridge, before she comes down'], ['b', 'Nothing; only a shock at the end'], ['c', 'The intruder’s full backstory']], 'a', 'The audience knows more: [[dramatic_irony]]. Surprise lasts a second; suspense lasts a minute.') },
      { label: 'Light', dept: 'lighting', context: 'The house is dark. She has a torch.',
        step: s('Lighting plan?', [['a', 'Low-key: the torch is the key, dim blue moonlight as fill'], ['b', 'All room lights on'], ['c', 'High-key, soft and even']], 'a', '[[low_key]] light hides most of the frame, so we search it.') },
      { label: 'Frame', dept: 'composition', context: 'She enters the kitchen.',
        step: s('Where do you place her in the frame?', [['a', 'To one side, with a big dark empty space beside her'], ['b', 'Centered, filling the frame'], ['c', 'Tiny in an extreme wide shot with all lights on']], 'a', 'Dark [[negative_space]] makes us look for the threat.') },
      { label: 'Camera', dept: 'camera', context: 'She points the torch into a corner.',
        step: s('What shot?', [['a', 'Her POV: the torch beam moves over the corner'], ['b', 'Bird’s-eye of the house'], ['c', 'Insert of a clock in the living room']], 'a', 'A [[pov_shot]] puts us in her place.') },
      { label: 'Rhythm', dept: 'editing', context: 'The search lasts 60 seconds.',
        step: s('How do you cut the search?', [['a', 'Long, slow shots; hold longer than feels comfortable'], ['b', 'Fast cuts every half second'], ['c', 'A montage with music']], 'a', 'Slow [[pacing]] stretches the wait.') },
      { label: 'Shock', dept: 'editing', context: 'She turns. The intruder is right behind her.',
        step: s('How do you deliver the shock?', [['a', 'Smash cut to his face with a loud sound after near silence'], ['b', 'Slow dissolve'], ['c', 'Fade to black, then a title card']], 'a', 'A [[smash_cut]] after quiet hits hardest.') },
    ],
    outcome: 'Suspense first (the audience knows), then a shock (she does not). Dark space, POV, slow cutting and silence build pressure; the smash cut releases it.',
    ref: 'Hitchcock’s bomb-under-the-table idea; the basement in The Silence of the Lambs (1991)',
  },
  {
    id: 'training-montage', title: 'Six months in two minutes', genre: 'Sports drama',
    setup: 'A shy girl wants to win the city table-tennis cup. She has six months to train. The film is 95 minutes long and you have two minutes for her training.',
    goal: 'Show time passing and her growth without dialogue.',
    terms: ['montage', 'match_cut', 'motif', 'score', 'character_arc', 'show_dont_tell'], tags: ['montage', 'time'],
    checkpoints: [
      { label: 'Structure', dept: 'editing', context: 'Six months must fit in two minutes.',
        step: s('Which tool?', [['a', 'A montage cut to music'], ['b', 'One long take'], ['c', 'A narrator reads her diary']], 'a', 'A [[montage]] compresses time.') },
      { label: 'Progress', dept: 'story', context: 'We must see she gets better.',
        step: s('How do you show progress?', [['a', 'Repeat the same drill: at first she misses, later she hits ten in a row'], ['b', 'She says “I am better now.”'], ['c', 'Show a calendar only']], 'a', 'Repetition with change: [[motif]] and [[show_dont_tell]].') },
      { label: 'Transition', dept: 'editing', context: 'From winter to summer in one cut.',
        step: s('Best cut?', [['a', 'The ball hits the table in snow-light; cut on the bounce to the same shot in summer light'], ['b', 'Jump cut with no link'], ['c', 'Wipe']], 'a', 'A [[match_cut]] on action jumps time smoothly.') },
      { label: 'Music', dept: 'sound', context: 'The music editor offers two tracks.',
        step: s('Which?', [['a', 'A track that starts small and grows, cut on the beat'], ['b', 'A sad track at the same level for two minutes'], ['c', 'No music, only room tone']], 'a', 'The [[score]] carries the rising energy.') },
      { label: 'End point', dept: 'story', context: 'How does the montage end?',
        step: s('Last shot?', [['a', 'She beats her coach for the first time, and she smiles'], ['b', 'She sleeps'], ['c', 'Credits']], 'a', 'End on a visible step in her [[character_arc]].') },
    ],
    outcome: 'Montage compresses time; repetition shows growth; match cuts and rising music give momentum; the last image shows change.',
    ref: 'Rocky (1976) training montage; Up (2009) “Married Life”',
  },
  {
    id: 'forest-spirit', title: 'Meeting the forest spirit', genre: 'Anime fantasy',
    setup: 'A 9-year-old boy gets lost in an old forest. He meets a huge, gentle spirit. It does not speak. This is a 2D anime production with a TV budget.',
    goal: 'Wonder and calm, not fear.',
    terms: ['ma', 'camera_angle', 'on_twos', 'color_script', 'parallax', 'moving_hold'], tags: ['animation', 'wonder'],
    checkpoints: [
      { label: 'Angle', dept: 'camera', context: 'The spirit is ten times taller than the boy.',
        step: s('First shot of the spirit?', [['a', 'Low angle from the boy’s height, looking up'], ['b', 'High angle looking down on it'], ['c', 'Dutch angle']], 'a', 'A low [[camera_angle]] makes it big, and we share his view.') },
      { label: 'Color', dept: 'color', context: 'The lost-in-the-forest part was cold blue-green.',
        step: s('Color when the spirit appears?', [['a', 'Warm light breaks through: soft gold enters the cool palette'], ['b', 'Deep red'], ['c', 'Same cold palette']], 'a', 'Change the palette at the turn: [[color_script]].') },
      { label: 'Pause', dept: 'story', context: 'After the meeting, the producer wants an action beat right away.',
        step: s('What do you put after the meeting?', [['a', 'A quiet moment: wind in leaves, both sit and breathe'], ['b', 'An instant chase'], ['c', 'A long explanation of the spirit']], 'a', 'A meaningful pause: [[ma]].') },
      { label: 'Depth', dept: 'anim_tech', context: 'The camera pans across the forest.',
        step: s('How to show depth in 2D?', [['a', 'Separate layers that move at different speeds'], ['b', 'One flat painting'], ['c', 'Rotate the camera 360°']], 'a', 'Near layers move faster: [[parallax]] ([[multiplane]]).') },
      { label: 'Budget', dept: 'anim_tech', context: 'The spirit is huge and slow. You have few drawings.',
        step: s('How to animate it cheaply but alive?', [['a', 'Mostly on twos/threes, with moving holds and breathing'], ['b', 'Every frame on ones'], ['c', 'Freeze it as a still']], 'a', 'Slow giants read well on [[on_twos]] with a [[moving_hold]].') },
    ],
    outcome: 'Low angle for scale, a color turn for emotion, a pause for wonder, parallax for depth, and economy in drawings: the choice fits the story and the budget.',
    ref: 'My Neighbor Totoro (1988), the bus-stop scene',
  },
  {
    id: 'cg-jump', title: 'The fox’s first jump', genre: 'CG short (Blender)',
    setup: 'You make a 20-second Blender short: a young fox jumps over a stream for the first time. You do the rig, the animation, the camera and the render alone.',
    goal: 'The audience must feel the fox’s fear, then pride.',
    terms: ['anticipation', 'squash_stretch', 'blocking_anim', 'ik', 'eevee', 'dof', 'follow_through'], tags: ['animation', 'blender'],
    checkpoints: [
      { label: 'Rig', dept: 'rigging', context: 'The paws must stay on the ground while the body crouches.',
        step: s('Leg setup?', [['a', 'IK on the legs with pole targets'], ['b', 'FK only'], ['c', 'No rig, sculpt every frame']], 'a', '[[ik]] keeps feet planted.') },
      { label: 'Acting', dept: 'anim_principle', context: 'Before the jump, the fox is afraid.',
        step: s('How do you show fear before the jump?', [['a', 'Two false starts, ears back, then a deep crouch'], ['b', 'It jumps at once'], ['c', 'A text caption “afraid”']], 'a', 'A longer [[anticipation]] shows hesitation.') },
      { label: 'First pass', dept: 'anim_tech', context: 'You start animating.',
        step: s('How do you start?', [['a', 'Key poses in Constant interpolation, check timing'], ['b', 'Polish the tail first'], ['c', 'Render a test with Cycles at 4096 samples']], 'a', '[[blocking_anim]] first, polish later.') },
      { label: 'Landing', dept: 'anim_principle', context: 'The fox lands on the other side.',
        step: s('What happens at landing?', [['a', 'Body squashes, tail keeps moving and settles'], ['b', 'Everything stops on one frame'], ['c', 'The fox stretches upward']], 'a', '[[squash_stretch]] on impact plus [[follow_through]].') },
      { label: 'Camera', dept: 'blender', context: 'The pride moment after landing.',
        step: s('Camera setup in Blender?', [['a', '85 mm, low, f/2 depth of field focused on the fox’s face'], ['b', '12 mm far away, f/22'], ['c', 'Orthographic top view']], 'a', 'A long lens with shallow [[dof]] isolates the emotion.') },
      { label: 'Render', dept: 'blender', context: 'You have one week and one GPU.',
        step: s('Engine?', [['a', 'EEVEE, with a short Cycles test only if needed'], ['b', 'Cycles at maximum samples for every frame'], ['c', 'Workbench']], 'a', '[[eevee]] fits a tight schedule.') },
    ],
    outcome: 'Rig for the action, block the acting first, let the principles carry fear and pride, then pick a lens and engine that serve the moment and the deadline.',
    ref: 'Blender Studio open shorts (e.g. Sprite Fright, Charge) — study their files',
  },
  {
    id: 'market-chase', title: 'Chase through the night market', genre: 'Action',
    setup: 'A thief grabs a bag and runs through a crowded night market. A young cop chases him. The audience must always know where both are.',
    goal: 'Energy without confusion.',
    terms: ['screen_direction', '180_rule', 'cross_cutting', 'handheld', 'pacing', 'action_choreo', 'wide_shot'], tags: ['action'],
    checkpoints: [
      { label: 'Geography', dept: 'camera', context: 'First shot of the chase.',
        step: s('What do you show first?', [['a', 'A wide high shot: the market, the thief, the cop behind'], ['b', 'An extreme close-up of the bag'], ['c', 'Only blurry lights']], 'a', 'A [[wide_shot]] sets geography before the chaos.') },
      { label: 'Direction', dept: 'composition', context: 'The thief runs left to right in shot 1.',
        step: s('In the next shots, both run…', [['a', 'Left to right as well'], ['b', 'Any direction'], ['c', 'Toward the camera only']], 'a', 'Consistent [[screen_direction]] keeps them in the same chase.') },
      { label: 'Camera feel', dept: 'camera', context: 'The cop pushes through people.',
        step: s('Camera for the cop?', [['a', 'Handheld, close, running with him'], ['b', 'Locked-off tripod wide'], ['c', 'Slow crane']], 'a', '[[handheld]] gives energy and effort.') },
      { label: 'Two lines', dept: 'editing', context: 'Thief and cop are in different alleys.',
        step: s('How do you edit them?', [['a', 'Cross-cut, shots getting shorter as the gap closes'], ['b', 'Show the thief for 2 minutes, then the cop'], ['c', 'Split screen for the whole chase']], 'a', '[[cross_cutting]] with faster [[pacing]].') },
      { label: 'Action beat', dept: 'history', context: 'The cop jumps over a food cart.',
        step: s('How do you cover the jump?', [['a', 'One wide enough shot so we see the whole move'], ['b', 'Ten fast close-ups'], ['c', 'Hide it with smoke']], 'a', 'Clear, readable [[action_choreo]].') },
    ],
    outcome: 'Wide shots for geography, fixed screen direction, handheld energy and tighter cross-cutting make a chase that is fast and still clear.',
    ref: 'Police Story (1985) market chase; The Bourne Supremacy (2004)',
  },
  {
    id: 'family-dinner', title: 'The dinner where nobody talks', genre: 'Family drama',
    setup: 'Three generations eat dinner. Grandfather has decided to sell the family shop, but has not told anyone. His son wants to take over the shop. The granddaughter knows the secret.',
    goal: 'Show the power and tension at the table in few cuts.',
    terms: ['staging', 'blocking', 'deep_focus', 'symmetry', 'dramatic_irony', 'insert'], tags: ['staging', 'drama'],
    checkpoints: [
      { label: 'Who knows', dept: 'story', context: 'Only the granddaughter knows the secret.',
        step: s('Whose point of view do you follow?', [['a', 'The granddaughter: we know what she knows'], ['b', 'The son'], ['c', 'Nobody in particular']], 'a', 'Sharing her knowledge gives [[dramatic_irony]].') },
      { label: 'Blocking', dept: 'director', context: 'Where does everyone sit?',
        step: s('Seating plan?', [['a', 'Grandfather at the head, son far end, granddaughter between them'], ['b', 'Everyone in a line facing the camera'], ['c', 'Random']], 'a', '[[blocking]] shows relationships before a word.') },
      { label: 'Frame', dept: 'camera', context: 'You want all three in one shot.',
        step: s('Which approach?', [['a', 'Deep focus, staging in depth: son near, grandfather far, all sharp'], ['b', 'Shallow focus on the rice bowl'], ['c', 'Three separate close-ups only']], 'a', '[[deep_focus]] and [[staging]] let us read all faces at once.') },
      { label: 'Detail', dept: 'camera', context: 'The sale contract is in grandfather’s jacket pocket.',
        step: s('How does the audience learn it?', [['a', 'An insert of the folded contract when he reaches for his glasses'], ['b', 'He reads it aloud'], ['c', 'A caption']], 'a', 'An [[insert]] gives the key fact.') },
    ],
    outcome: 'Blocking and depth staging tell power; one insert gives the secret; the granddaughter’s point of view turns a quiet dinner into suspense.',
    ref: 'Ozu’s family films; the “Kane” window shot (Citizen Kane, 1941)',
  },
  {
    id: 'robot-wakes', title: 'The robot wakes up', genre: 'Sci-fi animation',
    setup: 'In a scrapyard, a small broken robot powers on for the first time. It does not know what it is. No dialogue.',
    goal: 'Curiosity and appeal: the audience must love it in 30 seconds.',
    terms: ['appeal', 'shape_language', 'acting_anim', 'secondary_action', 'volumetric', 'principled_bsdf'], tags: ['animation', 'blender'],
    checkpoints: [
      { label: 'Design', dept: 'modeling', context: 'You design the robot’s shape.',
        step: s('Which shape language?', [['a', 'Round body, big eyes, small soft forms'], ['b', 'Sharp triangles and spikes'], ['c', 'Thin tall blocks']], 'a', 'Round = friendly: [[shape_language]] and [[appeal]].') },
      { label: 'First move', dept: 'anim_tech', context: 'The robot powers on.',
        step: s('What moves first?', [['a', 'The eyes light up and look around'], ['b', 'It runs at once'], ['c', 'Its arms spin']], 'a', 'Thought shows in the eyes first: [[acting_anim]].') },
      { label: 'Life', dept: 'anim_principle', context: 'It looks at a butterfly.',
        step: s('What small extra action helps?', [['a', 'An antenna wobbles and its head tilts'], ['b', 'Nothing should move'], ['c', 'A big explosion']], 'a', '[[secondary_action]] adds personality.') },
      { label: 'Light', dept: 'blender', context: 'A dusty scrapyard at sunrise.',
        step: s('How do you get light beams through dust?', [['a', 'Volume Scatter in the world or a box, with a low sun light'], ['b', 'Paint white lines on the image'], ['c', 'Increase metallic to 1']], 'a', '[[volumetric]] light makes god rays.') },
      { label: 'Material', dept: 'blender', context: 'Old painted metal with scratches.',
        step: s('Material setup?', [['a', 'Principled BSDF: metallic where paint is gone, higher roughness on paint'], ['b', 'Emission shader only'], ['c', 'Glass shader']], 'a', 'Mix metal and paint with a mask in [[principled_bsdf]].') },
    ],
    outcome: 'Appeal starts in design, lives in eye-first acting and secondary actions, and is framed by soft volumetric morning light.',
    ref: 'WALL·E (2008), first act',
  },
  {
    id: 'flashback-letter', title: 'The letter from the past', genre: 'Romance',
    setup: 'An old man finds a letter he wrote 50 years ago and never sent. As he reads it, we must go back to the summer he wrote it.',
    goal: 'Move between past and present clearly and with emotion.',
    terms: ['flashback', 'match_cut', 'color_grading', 'sound_bridge', 'nonlinear', 'motif'], tags: ['time', 'editing'],
    checkpoints: [
      { label: 'Story', dept: 'story', context: 'Do you need the flashback at all?',
        step: s('When is a flashback right?', [['a', 'When the past changes how we see the present scene'], ['b', 'Always, to show more scenery'], ['c', 'Never']], 'a', 'A [[flashback]] must earn its place.') },
      { label: 'Into the past', dept: 'editing', context: 'His old hand holds the letter.',
        step: s('Transition to the past?', [['a', 'Match cut: old hand on the letter → young hand writing the same letter'], ['b', 'A wipe'], ['c', 'A title “50 years earlier” only']], 'a', 'A [[match_cut]] links the two times.') },
      { label: 'Look', dept: 'color', context: 'Past and present must look different.',
        step: s('Grade plan?', [['a', 'Past: warm, soft, more saturated. Present: cooler, muted'], ['b', 'Same grade for both'], ['c', 'Past in neon']], 'a', '[[color_grading]] tells the audience where we are.') },
      { label: 'Back to now', dept: 'sound', context: 'In the past, a girl laughs by the sea.',
        step: s('How do you return?', [['a', 'Her laughter continues over the old man’s face in the present'], ['b', 'Hard cut with silence'], ['c', 'Music stops, title card']], 'a', 'A [[sound_bridge]] carries the memory into now.') },
    ],
    outcome: 'Match cut in, a different grade for each time, and a sound bridge out: the flashback is clear and it changes the present.',
    ref: 'The Notebook (2004); Titanic (1997) old-Rose transitions',
  },
  {
    id: 'interview-doc', title: 'A documentary interview', genre: 'Documentary',
    setup: 'You interview an old fisherman about the last day of his village’s harbor. One camera, one day, a small room with a window.',
    goal: 'Honest, intimate, and good-looking with simple tools.',
    terms: ['lighting_three_point', 'hard_soft', 'rule_of_thirds', 'ambience', 'cutaway', 'color_temp'], tags: ['documentary'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'A window on one side, cloudy day.',
        step: s('Light plan?', [['a', 'Window as soft key, a white board as fill, a small rim light'], ['b', 'On-camera flash'], ['c', 'Ceiling light only']], 'a', 'Soft natural [[lighting_three_point]].') },
      { label: 'Mixed light', dept: 'lighting', context: 'The room also has an orange tungsten lamp.',
        step: s('What do you do with it?', [['a', 'Turn it off, or use it only as a warm background practical'], ['b', 'Use it as the key on his face'], ['c', 'Ignore color']], 'a', 'Control mixed [[color_temp]].') },
      { label: 'Frame', dept: 'composition', context: 'He looks at you, off-camera left.',
        step: s('Frame?', [['a', 'He sits on the right third, looking into the open left side'], ['b', 'Centered and tiny'], ['c', 'Head cut at the top edge']], 'a', '[[rule_of_thirds]] with lead room.') },
      { label: 'Sound', dept: 'sound', context: 'End of the day.',
        step: s('What do you record last?', [['a', '30 seconds of room tone'], ['b', 'Nothing more'], ['c', 'Music on a phone']], 'a', 'Room tone fills edit gaps: [[ambience]].') },
      { label: 'Edit', dept: 'editing', context: 'His answer has a long pause you want to remove.',
        step: s('How do you hide the cut?', [['a', 'Cut away to his hands mending a net'], ['b', 'Jump cut and hope'], ['c', 'Add a glitch effect']], 'a', 'A [[cutaway]] hides the cut and adds meaning.') },
    ],
    outcome: 'Soft window light, clean color, good framing, room tone and cutaways: simple tools, professional result.',
    ref: 'Errol Morris interviews; Jiro Dreams of Sushi (2011)',
  },
  {
    id: 'ai-shot', title: 'An AI-generated establishing shot', genre: 'AI-assisted previs',
    setup: 'Your short film opens on a floating city above the clouds at dawn. You make it with an AI video model, then a Blender previs for the next shots.',
    goal: 'A controlled shot that matches the rest of the film.',
    terms: ['prompt_shot', 'consistency', 'previs', 'crane', 'golden_hour', 'lookbook'], tags: ['ai', 'previs'],
    checkpoints: [
      { label: 'Reference', dept: 'director', context: 'Before prompting.',
        step: s('What do you prepare first?', [['a', 'A lookbook with 5 reference images for color, scale and mood'], ['b', 'Nothing; just try prompts'], ['c', 'The end credits']], 'a', 'A [[lookbook]] keeps the style stable.') },
      { label: 'Prompt', dept: 'modern', context: 'You write the prompt.',
        step: s('Best prompt?', [['a', 'Extreme wide shot, 24 mm, slow crane up from clouds to reveal a floating city, golden-hour backlight, haze, calm wonder'], ['b', 'floating city, epic, 8k'], ['c', 'best quality masterpiece']], 'a', 'Shot size, lens, move, light, mood: [[prompt_shot]].') },
      { label: 'Move', dept: 'camera', context: 'Which camera move for the reveal?',
        step: s('Move?', [['a', 'Crane up from below the clouds'], ['b', 'Fast whip pan'], ['c', 'Static close-up']], 'a', 'A rising [[crane]] reveals scale.') },
      { label: 'Next shots', dept: 'preprod', context: 'Characters walk in the city in the next shots.',
        step: s('How do you plan them?', [['a', 'Blender previs with real lenses, then use it as guide for generation'], ['b', 'Random prompts until something looks good'], ['c', 'Skip planning']], 'a', '[[previs]] gives control and [[consistency]].') },
    ],
    outcome: 'Treat AI like a camera crew: references first, prompt like a shot list, and previs to keep control.',
    ref: 'Compare with classic establishing shots in Castle in the Sky (1986)',
  },
  {
    id: 'comedy-fall', title: 'The pie in the face', genre: 'Comedy',
    setup: 'A proud chef carries a giant cake to a wedding table. A dog runs between his legs. The cake hits the bride’s mother.',
    goal: 'Make the gag land: big laugh, clear timing.',
    terms: ['setup_payoff', 'timing', 'wide_shot', 'high_key', 'exaggeration', 'reaction_shot'], tags: ['comedy'],
    checkpoints: [
      { label: 'Setup', dept: 'story', context: 'Earlier in the scene.',
        step: s('What do you plant earlier?', [['a', 'The dog stealing sausages under tables'], ['b', 'Nothing; surprise is enough'], ['c', 'A long speech about cakes']], 'a', 'Plant the cause: [[setup_payoff]].') },
      { label: 'Shot', dept: 'camera', context: 'The fall itself.',
        step: s('Shot size for physical comedy?', [['a', 'Wide enough to see the whole body and the table'], ['b', 'Extreme close-up of the chef’s eye'], ['c', 'Shaky handheld close-ups']], 'a', 'Comedy reads best in a [[wide_shot]] with full bodies.') },
      { label: 'Light', dept: 'lighting', context: 'A wedding in the daytime.',
        step: s('Lighting style?', [['a', 'High-key, bright, few shadows'], ['b', 'Low-key noir'], ['c', 'Red emergency light']], 'a', '[[high_key]] suits comedy.') },
      { label: 'Timing', dept: 'anim_principle', context: 'After the cake hits.',
        step: s('What next?', [['a', 'Hold a beat, then cut to the mother’s frozen face'], ['b', 'Cut away at once to another scene'], ['c', 'Slow-motion replay three times']], 'a', 'Comic [[timing]]: the pause and the [[reaction_shot]] get the laugh.') },
    ],
    outcome: 'Plant the cause, show it wide and bright, then hold for the reaction. Timing is the joke.',
    ref: 'Buster Keaton and Jackie Chan; Mr. Bean',
  },
]
