import type { Term, Category } from '../shared/types'

export const CATS: Category[] = [
  { id: "story", name: "Story", zh: "故事", ja: "物語", color: "#e0743b" },
  { id: "director", name: "Directing", zh: "导演", ja: "演出", color: "#c77dff" },
  { id: "camera", name: "Camera", zh: "摄影", ja: "撮影", color: "#5b8def" },
  { id: "composition", name: "Composition", zh: "构图", ja: "構図", color: "#2fb5c5" },
  { id: "lighting", name: "Lighting", zh: "灯光", ja: "照明", color: "#e9b949" },
  { id: "color", name: "Color", zh: "色彩", ja: "色彩", color: "#b07cd8" },
  { id: "editing", name: "Editing", zh: "剪辑", ja: "編集", color: "#e0607e" },
  { id: "sound", name: "Sound", zh: "声音", ja: "音響", color: "#8e7cf0" },
  { id: "preprod", name: "Pre-production & Pipeline", zh: "前期与流程", ja: "プリプロと工程", color: "#6dbf4b" },
  { id: "anim_principle", name: "Animation Principles", zh: "动画法则", ja: "アニメの原則", color: "#ef6f5e" },
  { id: "anim_tech", name: "Animation Technique", zh: "动画技术", ja: "アニメ技法", color: "#f08a5d" },
  { id: "modeling", name: "Modeling", zh: "建模", ja: "モデリング", color: "#3dbe8b" },
  { id: "rigging", name: "Rigging", zh: "绑定", ja: "リギング", color: "#2aa198" },
  { id: "blender", name: "Blender Flow", zh: "Blender流程", ja: "Blenderの流れ", color: "#f5a623" },
  { id: "history", name: "Film History", zh: "电影史", ja: "映画史", color: "#93a4be" },
  { id: "modern", name: "AI & Modern Tools", zh: "AI与新工具", ja: "AIと新技術", color: "#7f9cc0" },
]

// [id, category, English, 中文, 日本語, explanation, related ids]
type T = [string, string, string, string, string, string, string[]]

const raw: T[] = [
  // ───────── story
  ["premise", "story", "Premise", "前提 / 故事核心", "前提（プレミス）", "One sentence that says who wants what, and what stops them. Test every scene against it.", ["logline", "theme", "protagonist"]],
  ["logline", "story", "Logline", "一句话梗概", "ログライン", "A 1–2 sentence pitch: protagonist + goal + obstacle + stakes. Producers read it first.", ["premise", "stakes"]],
  ["theme", "story", "Theme", "主题", "テーマ", "The idea the story argues about life, e.g. 'trust costs courage'. Show it through choices, not speeches.", ["premise", "subtext", "motif"]],
  ["protagonist", "story", "Protagonist", "主角", "主人公", "The character whose goal drives the plot. The audience follows their choices.", ["antagonist", "character_arc", "want_need"]],
  ["antagonist", "story", "Antagonist", "反派 / 对手", "敵役（アンタゴニスト）", "The force that opposes the protagonist. It can be a person, nature, society or the hero's own flaw.", ["protagonist", "conflict"]],
  ["conflict", "story", "Conflict", "冲突", "葛藤（コンフリクト）", "Opposition between a want and an obstacle. No conflict means no drama. Types: inner, personal, external.", ["antagonist", "stakes", "scene_goal"]],
  ["stakes", "story", "Stakes", "赌注 / 利害", "賭けられたもの（ステークス）", "What the character loses if they fail. Raise stakes to raise tension.", ["conflict", "tension"]],
  ["want_need", "story", "Want vs Need", "想要与需要", "欲求と必要", "Want = conscious external goal. Need = inner lesson the character must learn. Good arcs trade want for need.", ["character_arc", "protagonist"]],
  ["character_arc", "story", "Character Arc", "人物弧光", "キャラクターアーク", "The inner change of a character from start to end: positive, negative or flat.", ["want_need", "theme"]],
  ["three_act", "story", "Three-Act Structure", "三幕结构", "三幕構成", "Setup (~25 %), Confrontation (~50 %), Resolution (~25 %). The base model of Western screenwriting.", ["inciting_incident", "midpoint", "climax", "kishotenketsu"]],
  ["kishotenketsu", "story", "Kishōtenketsu", "起承转合", "起承転結", "Four-part East Asian structure: introduction, development, twist, conclusion. It can work without direct conflict.", ["three_act", "plot_twist"]],
  ["heros_journey", "story", "Hero's Journey", "英雄之旅", "英雄の旅", "Joseph Campbell's monomyth: call, refusal, mentor, threshold, ordeals, return. Christopher Vogler adapted it for film.", ["three_act", "mentor"]],
  ["save_the_cat", "story", "Save the Cat Beat Sheet", "救猫咪节拍表", "セーブ・ザ・キャット", "Blake Snyder's 15 beats (Opening Image, Catalyst, Midpoint, All Is Lost...). Useful to time a feature script.", ["three_act", "beat"]],
  ["inciting_incident", "story", "Inciting Incident", "激励事件", "きっかけとなる事件", "The event that breaks the normal world and starts the story question.", ["three_act", "dramatic_question"]],
  ["midpoint", "story", "Midpoint", "中点", "ミッドポイント", "Central turn: a false victory or false defeat that changes the hero from reactive to active.", ["three_act", "climax"]],
  ["climax", "story", "Climax", "高潮", "クライマックス", "Highest point of conflict where the dramatic question gets its answer.", ["midpoint", "resolution", "dramatic_question"]],
  ["resolution", "story", "Resolution / Denouement", "结局", "結末（デノウマン）", "After the climax: show the new normal and the cost of change.", ["climax"]],
  ["dramatic_question", "story", "Dramatic Question", "戏剧问题", "ドラマティック・クエスチョン", "The yes/no question the audience waits to answer: 'Will she escape?'", ["inciting_incident", "climax"]],
  ["beat", "story", "Beat", "节拍", "ビート", "The smallest unit of change in a scene: an action and a reaction that shifts value.", ["scene_goal", "save_the_cat"]],
  ["scene_goal", "story", "Scene Goal & Turn", "场景目标与转折", "シーンの目的と転換", "Each scene: a character wants something, meets conflict, and the scene value turns (+ to – or – to +).", ["beat", "conflict"]],
  ["subtext", "story", "Subtext", "潜台词", "サブテキスト", "Meaning under the words. Characters rarely say what they feel directly.", ["theme", "dialogue"]],
  ["dialogue", "story", "Dialogue", "对白", "台詞（ダイアログ）", "Speech that reveals character and moves plot. Cut what only gives information.", ["subtext", "exposition"]],
  ["exposition", "story", "Exposition", "说明性信息", "説明（エクスポジション）", "Background facts the audience needs. Hide it in conflict ('show, don't tell').", ["show_dont_tell", "dialogue"]],
  ["show_dont_tell", "story", "Show, Don't Tell", "展示而非讲述", "語らずに見せる", "Use action and image to give information, not explanation.", ["exposition", "visual_storytelling"]],
  ["setup_payoff", "story", "Setup & Payoff", "铺垫与回收", "伏線と回収", "Plant an object or fact early; use it later. Chekhov's gun is the classic rule.", ["foreshadowing", "chekhov"]],
  ["chekhov", "story", "Chekhov's Gun", "契诃夫之枪", "チェーホフの銃", "If a gun is on the wall in act one, it must fire later. Every detail must earn its place.", ["setup_payoff"]],
  ["foreshadowing", "story", "Foreshadowing", "伏笔 / 预示", "予兆（フォーシャドウ）", "A hint of a later event. It makes twists feel fair.", ["setup_payoff", "plot_twist"]],
  ["plot_twist", "story", "Plot Twist", "情节反转", "どんでん返し", "An unexpected change that re-frames earlier events. It must be surprising yet inevitable.", ["foreshadowing", "kishotenketsu"]],
  ["macguffin", "story", "MacGuffin", "麦格芬", "マクガフィン", "An object everyone chases that matters only because it drives the plot (Hitchcock's term).", ["want_need"]],
  ["pov", "story", "Point of View", "视点", "視点（POV）", "Whose experience the audience shares. Controls what we know and feel.", ["dramatic_irony", "pov_shot"]],
  ["dramatic_irony", "story", "Dramatic Irony / Suspense", "戏剧反讽 / 悬念", "劇的アイロニー / サスペンス", "Audience knows more than the character. Hitchcock's bomb under the table: suspense beats surprise.", ["pov", "tension"]],
  ["tension", "story", "Tension & Release", "张力与释放", "緊張と緩和", "Alternate pressure and relief to keep attention; nonstop tension makes viewers numb.", ["stakes", "pacing"]],
  ["motif", "story", "Motif", "母题 / 主旨意象", "モチーフ", "A repeated image, sound or object that carries the theme.", ["theme", "symbolism"]],
  ["symbolism", "story", "Symbolism", "象征", "象徴", "An object or color that stands for a bigger idea.", ["motif", "color_script"]],
  ["mentor", "story", "Mentor", "导师", "メンター（師）", "A figure who gives the hero a tool, knowledge or push.", ["heros_journey"]],
  ["nonlinear", "story", "Nonlinear Narrative", "非线性叙事", "非線形の語り", "Events shown out of time order (flashback, flash-forward, parallel lines), e.g. Pulp Fiction, Memento.", ["flashback", "cross_cutting"]],
  ["flashback", "story", "Flashback", "闪回", "フラッシュバック", "A jump to an earlier time. Use it only when the past changes the present scene.", ["nonlinear"]],
  ["visual_storytelling", "story", "Visual Storytelling", "视觉叙事", "映像による語り", "Telling the story with images; a good film works with the sound off.", ["show_dont_tell", "storyboard"]],
  ["genre", "story", "Genre & Conventions", "类型与惯例", "ジャンルと約束事", "Audience expectations (horror, comedy, noir). Meet some, break some.", ["tone"]],
  ["tone", "story", "Tone", "基调", "トーン（語り口）", "The emotional attitude of the film: dark, light, ironic. Keep it consistent or shift it on purpose.", ["genre", "color_script"]],
  // ───────── director
  ["director_role", "director", "Director's Role", "导演职责", "監督の役割", "Turns the script into a film: sets the vision, guides actors and departments, decides every shot.", ["vision", "producer", "dp"]],
  ["vision", "director", "Directorial Vision", "导演构想", "演出ビジョン", "A clear idea of what the film feels like. Shared through lookbook, references and talk.", ["lookbook", "tone"]],
  ["lookbook", "director", "Lookbook / Mood Board", "风格手册 / 情绪板", "ルックブック / ムードボード", "A collection of reference images for color, light, costume and framing.", ["vision", "color_script"]],
  ["director_treatment", "director", "Director's Treatment", "导演阐述", "演出意図書", "A document that explains how the director will make the film: style, tone, key scenes.", ["vision", "logline"]],
  ["script_breakdown", "director", "Script Breakdown", "剧本拆解", "台本分解（ブレイクダウン）", "Marking each scene's cast, props, locations, effects to plan the schedule and budget.", ["shot_list", "schedule"]],
  ["shot_list", "director", "Shot List", "分镜表 / 镜头清单", "ショットリスト", "A list of every shot per scene: size, angle, movement, lens, notes.", ["storyboard", "coverage"]],
  ["blocking", "director", "Blocking", "走位调度", "ブロッキング（立ち位置）", "Planning where actors move in the set and where the camera goes.", ["staging", "mise_en_scene"]],
  ["staging", "director", "Staging in Depth", "纵深调度", "奥行きの演出", "Placing actors in foreground, middle and background so one shot tells more.", ["blocking", "deep_focus"]],
  ["mise_en_scene", "director", "Mise-en-scène", "场面调度", "ミザンセーヌ", "Everything inside the frame: set, props, costume, actors, light, composition.", ["blocking", "production_design"]],
  ["coverage", "director", "Coverage", "覆盖镜头", "カバレッジ", "Shooting a scene from several setups (master, mediums, close-ups) so the editor has choices.", ["master_shot", "shot_list"]],
  ["master_shot", "director", "Master Shot", "主镜头", "マスターショット", "One wide shot that records the whole scene. Base for coverage.", ["coverage", "wide_shot"]],
  ["rehearsal", "director", "Rehearsal", "排练", "リハーサル", "Practice before shooting to find blocking and performance.", ["blocking", "actor_direction"]],
  ["actor_direction", "director", "Directing Actors", "指导演员", "俳優演出", "Give actable notes: objectives and actions ('make him stay'), not result words ('be sad').", ["objective", "rehearsal"]],
  ["objective", "director", "Objective / Action Verb", "目标 / 动作动词", "目的 / 行動動詞", "What the character tries to get from the other in the scene, phrased as a verb.", ["actor_direction", "scene_goal"]],
  ["auteur", "director", "Auteur Theory", "作者论", "作家主義", "The idea that the director is the main author of a film, with a personal style (Truffaut, Cahiers du cinéma).", ["new_wave", "vision"]],
  ["producer", "director", "Producer", "制片人", "プロデューサー", "Finds money, hires team, controls schedule and budget, protects delivery.", ["director_role", "schedule"]],
  ["dp", "director", "Director of Photography", "摄影指导", "撮影監督", "Leads camera and lighting teams; designs the image with the director.", ["director_role", "lighting_three_point"]],
  ["production_design", "director", "Production Design", "美术设计", "美術デザイン", "Creates sets, props and the visual world.", ["mise_en_scene", "lookbook"]],
  ["schedule", "director", "Shooting Schedule / Stripboard", "拍摄日程 / 场景条", "撮影スケジュール", "Scenes grouped by location and cast, not story order, to save time.", ["script_breakdown", "call_sheet"]],
  ["call_sheet", "director", "Call Sheet", "通告单", "コールシート", "Daily sheet: who comes where and when, scenes to shoot, weather, safety.", ["schedule"]],
  ["slate", "director", "Slate / Clapperboard", "场记板", "カチンコ", "Marks scene, shot and take; the clap syncs sound and picture.", ["take", "double_system"]],
  ["take", "director", "Take", "条 / 次", "テイク", "One recording of a shot. 'Print' or 'circle' the good takes.", ["slate", "coverage"]],
  ["continuity", "director", "Continuity / Script Supervisor", "场记 / 连戏", "記録（スクリプター）", "Tracks props, eyelines and actions so shots match in the edit.", ["match_cut", "180_rule"]],
  ["sixty_sec_pitch", "director", "Pitch", "提案 / 推销", "ピッチ", "A short spoken sale of the project: logline, why now, why you, comps.", ["logline"]],
  // ───────── camera
  ["shot_size", "camera", "Shot Sizes", "景别", "ショットサイズ", "From wide to close: EWS, WS, FS, MS, MCU, CU, ECU. Closer = more emotion, wider = more context.", ["wide_shot", "close_up", "medium_shot"]],
  ["wide_shot", "camera", "Wide / Establishing Shot", "远景 / 建立镜头", "ロングショット / 状況設定ショット", "Shows the location and where people are. Often opens a scene.", ["shot_size", "master_shot"]],
  ["medium_shot", "camera", "Medium Shot", "中景", "ミディアムショット", "Waist up. Good for dialogue and body language.", ["shot_size", "two_shot"]],
  ["close_up", "camera", "Close-Up", "特写", "クローズアップ", "Face fills the frame. Shows thought and emotion. Use it where it matters most.", ["shot_size", "ecu"]],
  ["ecu", "camera", "Extreme Close-Up", "大特写", "超クローズアップ", "An eye, a hand, an object detail. High intensity.", ["close_up", "insert"]],
  ["insert", "camera", "Insert Shot", "插入镜头", "インサート", "A close shot of a detail (letter, phone) that gives needed information.", ["ecu", "cutaway"]],
  ["two_shot", "camera", "Two Shot", "双人镜头", "ツーショット", "Two characters in frame; shows their relation.", ["medium_shot", "ots"]],
  ["ots", "camera", "Over-the-Shoulder", "过肩镜头", "オーバー・ザ・ショルダー", "Camera behind one person looking at another. Standard dialogue coverage.", ["shot_reverse_shot", "180_rule"]],
  ["pov_shot", "camera", "POV Shot", "主观镜头", "主観ショット", "Camera shows exactly what the character sees.", ["pov", "eyeline_match"]],
  ["camera_angle", "camera", "Camera Angle", "机位角度", "カメラアングル", "High angle makes subject small/weak; low angle makes it strong; eye level is neutral.", ["dutch_angle", "birds_eye"]],
  ["dutch_angle", "camera", "Dutch Angle", "倾斜镜头", "ダッチアングル", "Tilted horizon; shows unease or madness.", ["camera_angle"]],
  ["birds_eye", "camera", "Bird's-Eye / Overhead", "鸟瞰 / 俯拍", "俯瞰（真上）", "Camera straight down. Shows pattern, fate or god view.", ["camera_angle"]],
  ["pan_tilt", "camera", "Pan & Tilt", "摇镜（横摇/纵摇）", "パン・ティルト", "Camera turns left/right (pan) or up/down (tilt) from a fixed point.", ["dolly", "camera_movement"]],
  ["dolly", "camera", "Dolly / Tracking", "推轨 / 跟拍", "ドリー / トラッキング", "Camera moves through space on wheels/track. Push in = focus attention; pull out = reveal or isolate.", ["pan_tilt", "dolly_zoom"]],
  ["crane", "camera", "Crane / Jib", "摇臂", "クレーン / ジブ", "Camera rises or falls; big reveal or ending.", ["dolly", "drone"]],
  ["handheld", "camera", "Handheld", "手持", "手持ち撮影", "Shaky, alive camera; creates realism and anxiety.", ["steadicam"]],
  ["steadicam", "camera", "Steadicam / Gimbal", "斯坦尼康 / 稳定器", "ステディカム / ジンバル", "Smooth floating moves following actors. Famous: The Shining, Goodfellas oner.", ["handheld", "long_take"]],
  ["drone", "camera", "Drone Shot", "航拍", "ドローン撮影", "Aerial view, cheap replacement for helicopters.", ["crane"]],
  ["dolly_zoom", "camera", "Dolly Zoom (Vertigo Effect)", "滑动变焦", "ドリーズーム（めまいショット）", "Dolly in while zooming out (or reverse): background stretches, subject stays same size. Shows shock.", ["dolly", "focal_length"]],
  ["camera_movement", "camera", "Motivated Camera Movement", "有动机的运镜", "動機のあるカメラワーク", "Move the camera only when a character, action or emotion gives a reason.", ["dolly", "pan_tilt"]],
  ["long_take", "camera", "Long Take / Oner", "长镜头 / 一镜到底", "長回し", "A shot that runs a long time with no cut. Builds immersion (1917, Children of Men).", ["steadicam", "pacing"]],
  ["focal_length", "camera", "Focal Length", "焦距", "焦点距離", "Wide lens (≤24 mm) exaggerates depth; normal (~35–50 mm); telephoto (≥85 mm) compresses space.", ["field_of_view", "lens_compression"]],
  ["field_of_view", "camera", "Field of View", "视场角", "画角", "How much of the scene the lens sees; set by focal length and sensor size.", ["focal_length", "sensor_size"]],
  ["lens_compression", "camera", "Lens Compression", "镜头压缩感", "圧縮効果", "Long lenses make far objects look close to near ones (actually caused by camera distance).", ["focal_length"]],
  ["aperture", "camera", "Aperture (f-stop)", "光圈", "絞り（F値）", "Lens opening. Low f-number = more light, shallow depth of field.", ["dof", "exposure_triangle"]],
  ["dof", "camera", "Depth of Field", "景深", "被写界深度", "The zone that is in focus. Shallow DOF isolates the subject; deep DOF shows everything.", ["aperture", "deep_focus", "rack_focus"]],
  ["deep_focus", "camera", "Deep Focus", "深焦摄影", "パンフォーカス", "Foreground and background both sharp (Citizen Kane, Gregg Toland).", ["dof", "staging"]],
  ["rack_focus", "camera", "Rack Focus / Focus Pull", "移焦 / 拉焦", "フォーカス送り", "Shift focus from one subject to another in the shot to move attention.", ["dof"]],
  ["shutter", "camera", "Shutter Speed / 180° Rule", "快门 / 180度快门", "シャッター速度 / 180度ルール", "Shutter = 1/(2×fps) gives natural motion blur (1/48 at 24 fps).", ["frame_rate", "motion_blur"]],
  ["frame_rate", "camera", "Frame Rate", "帧率", "フレームレート", "24 fps = film look; 30 TV; 60+ for slow motion when played at 24.", ["shutter", "on_twos"]],
  ["exposure_triangle", "camera", "Exposure Triangle", "曝光三角", "露出の三角形", "Aperture, shutter, ISO together decide brightness. Change one, compensate another.", ["aperture", "shutter", "iso"]],
  ["iso", "camera", "ISO / Gain", "感光度", "ISO感度", "Sensor sensitivity. Higher ISO = brighter but more noise.", ["exposure_triangle", "noise"]],
  ["sensor_size", "camera", "Sensor Size / Format", "画幅", "センサーサイズ", "Super35, full frame, IMAX. Bigger sensor = wider view and shallower DOF at same framing.", ["field_of_view"]],
  ["aspect_ratio", "camera", "Aspect Ratio", "画幅比", "アスペクト比", "Frame shape: 1.33, 1.85, 2.39 (scope). Wide frames for landscape and groups.", ["composition"]],
  ["anamorphic", "camera", "Anamorphic Lens", "变形宽银幕镜头", "アナモルフィックレンズ", "Squeezes a wide image on the sensor; gives oval bokeh and horizontal flares.", ["aspect_ratio"]],
  // ───────── composition
  ["composition", "composition", "Composition", "构图", "構図", "Arranging elements in the frame to guide the eye and tell meaning.", ["rule_of_thirds", "leading_lines"]],
  ["rule_of_thirds", "composition", "Rule of Thirds", "三分法", "三分割法", "Place key points on the lines that split the frame in thirds.", ["composition", "headroom"]],
  ["leading_lines", "composition", "Leading Lines", "引导线", "誘導線", "Lines (roads, walls) that pull the eye to the subject.", ["composition", "vanishing_point"]],
  ["symmetry", "composition", "Symmetry / Central Framing", "对称 / 中心构图", "シンメトリー / 日の丸構図", "Subject at center, mirrored frame. Formal or uncanny (Kubrick, Wes Anderson).", ["composition"]],
  ["headroom", "composition", "Headroom & Lead Room", "头部空间与视线空间", "ヘッドルーム / リードルーム", "Space above the head and in front of the gaze. Wrong space feels wrong.", ["rule_of_thirds"]],
  ["frame_in_frame", "composition", "Frame within a Frame", "框中框", "フレーム内フレーム", "Doors, windows that frame a character; show trap or isolation.", ["composition", "negative_space"]],
  ["negative_space", "composition", "Negative Space", "负空间 / 留白", "余白（ネガティブスペース）", "Empty area around a subject; shows loneliness or calm.", ["frame_in_frame"]],
  ["vanishing_point", "composition", "Vanishing Point / Perspective", "消失点 / 透视", "消失点 / 遠近法", "Where parallel lines meet; creates depth.", ["leading_lines", "focal_length"]],
  ["visual_weight", "composition", "Visual Weight & Balance", "视觉重量与平衡", "視覚的重さとバランス", "Big, bright, saturated or face elements pull the eye; balance them or unbalance on purpose.", ["composition", "contrast"]],
  ["eye_trace", "composition", "Eye Trace", "视线追踪", "視線誘導", "Where the viewer looks across cuts. Keep the subject near the same spot for smooth cuts.", ["visual_weight", "cut"]],
  ["screen_direction", "composition", "Screen Direction", "银幕方向", "画面の方向性", "Left-to-right movement reads as going forward; keep direction consistent.", ["180_rule"]],
  ["180_rule", "composition", "180-Degree Rule", "180度轴线规则", "イマジナリーライン（180度ルール）", "Keep the camera on one side of the action line so characters keep their screen side.", ["screen_direction", "ots", "continuity"]],
  // ───────── lighting
  ["lighting_three_point", "lighting", "Three-Point Lighting", "三点布光", "三点照明", "Key (main), fill (softens shadows), back/rim (separates from background).", ["key_light", "fill_light", "rim_light"]],
  ["key_light", "lighting", "Key Light", "主光", "キーライト", "The main light; sets direction and mood.", ["lighting_three_point", "motivated_light"]],
  ["fill_light", "lighting", "Fill Light", "辅光 / 补光", "フィルライト", "Lighter light that fills shadows; controls contrast ratio.", ["key_light", "contrast_ratio"]],
  ["rim_light", "lighting", "Rim / Back Light", "轮廓光 / 背光", "リムライト / バックライト", "Light from behind that outlines the subject.", ["lighting_three_point"]],
  ["contrast_ratio", "lighting", "Contrast Ratio", "光比", "照明比（コントラスト比）", "Key vs fill brightness. 2:1 soft comedy, 8:1 dramatic.", ["high_key", "low_key"]],
  ["high_key", "lighting", "High-Key Lighting", "高调照明", "ハイキー", "Bright, few shadows. Comedy, ads, musicals.", ["low_key", "contrast_ratio"]],
  ["low_key", "lighting", "Low-Key Lighting", "低调照明", "ローキー", "Dark, strong shadows. Noir, horror, thriller.", ["chiaroscuro", "high_key"]],
  ["chiaroscuro", "lighting", "Chiaroscuro", "明暗对照法", "キアロスクーロ", "Strong light-dark contrast from Renaissance painting (Caravaggio).", ["low_key", "rembrandt"]],
  ["rembrandt", "lighting", "Rembrandt Lighting", "伦勃朗光", "レンブラントライティング", "Key at 45° high; a light triangle on the shadow cheek.", ["key_light", "chiaroscuro"]],
  ["hard_soft", "lighting", "Hard vs Soft Light", "硬光与软光", "硬い光と柔らかい光", "Small source = hard sharp shadows; big diffused source = soft gradual shadows.", ["key_light", "bounce"]],
  ["bounce", "lighting", "Bounce & Diffusion", "反光与柔光", "レフ板と拡散", "Reflect or diffuse light to make it softer.", ["hard_soft"]],
  ["motivated_light", "lighting", "Motivated Lighting", "有动机的光", "動機付けられた照明", "Light that seems to come from a real source in the scene (window, lamp).", ["practical", "key_light"]],
  ["practical", "lighting", "Practical Light", "实用光源 / 道具灯", "プラクティカルライト", "A visible lamp in the shot that also lights the scene.", ["motivated_light"]],
  ["color_temp", "lighting", "Color Temperature", "色温", "色温度", "Kelvin scale: 3200 K tungsten orange, 5600 K daylight blue-white.", ["white_balance", "color_contrast"]],
  ["white_balance", "lighting", "White Balance", "白平衡", "ホワイトバランス", "Sets which light the camera reads as neutral white.", ["color_temp"]],
  ["golden_hour", "lighting", "Golden / Blue Hour", "黄金时刻 / 蓝调时刻", "マジックアワー / ブルーアワー", "Warm low sun after sunrise / before sunset; blue light just after sunset.", ["color_temp"]],
  ["silhouette", "lighting", "Silhouette", "剪影", "シルエット", "Subject dark against a bright background; shape tells the story.", ["rim_light", "staging_clarity"]],
  ["volumetric", "lighting", "Volumetric Light / God Rays", "体积光 / 丁达尔光", "ボリュメトリックライト / 天使の梯子", "Light visible in smoke or fog. In Blender: Volume Scatter in world or a cube.", ["cycles", "eevee"]],
  // ───────── editing
  ["cut", "editing", "Cut", "切 / 剪切", "カット", "Instant change from one shot to the next. The basic edit.", ["match_cut", "jump_cut", "eye_trace"]],
  ["kuleshov", "editing", "Kuleshov Effect", "库里肖夫效应", "クレショフ効果", "The same neutral face reads as hungry, sad or loving depending on the next shot. Meaning comes from the cut.", ["montage", "reaction_shot"]],
  ["montage", "editing", "Montage", "蒙太奇", "モンタージュ", "Joining shots to create meaning (Eisenstein) or a sequence that compresses time (training montage).", ["kuleshov", "soviet_montage"]],
  ["soviet_montage", "editing", "Soviet Montage / Collision", "苏联蒙太奇 / 冲突蒙太奇", "ソビエト・モンタージュ", "Eisenstein: shot A + shot B collide to make idea C (Battleship Potemkin).", ["montage"]],
  ["continuity_editing", "editing", "Continuity Editing", "连续性剪辑", "継続編集（コンティニュイティ編集）", "Invisible Hollywood style: match action, eyeline and direction so cuts are not noticed.", ["match_cut", "180_rule", "eyeline_match"]],
  ["match_cut", "editing", "Match Cut / Match on Action", "匹配剪辑 / 动作匹配", "マッチカット / アクションつなぎ", "Cut on a matching shape or action (2001's bone to satellite).", ["cut", "continuity_editing"]],
  ["jump_cut", "editing", "Jump Cut", "跳切", "ジャンプカット", "A cut within the same shot that skips time; feels jarring (Breathless).", ["cut", "new_wave"]],
  ["eyeline_match", "editing", "Eyeline Match", "视线匹配", "視線の一致", "Character looks off-screen; next shot shows what they see.", ["pov_shot", "continuity_editing"]],
  ["shot_reverse_shot", "editing", "Shot / Reverse Shot", "正反打", "切り返し", "Alternate between two speakers; base of dialogue editing.", ["ots", "180_rule"]],
  ["cross_cutting", "editing", "Cross-Cutting / Parallel Editing", "交叉剪辑 / 平行剪辑", "クロスカッティング / 平行モンタージュ", "Alternate two actions at the same time to build suspense (Griffith, The Godfather baptism).", ["tension", "nonlinear"]],
  ["cutaway", "editing", "Cutaway", "切出镜头", "カットアウェイ", "Shot away from the main action; hides cuts or adds context.", ["insert"]],
  ["reaction_shot", "editing", "Reaction Shot", "反应镜头", "リアクションショット", "Show the listener; emotion often lives in the reaction.", ["kuleshov", "close_up"]],
  ["l_cut", "editing", "J-Cut & L-Cut", "J剪辑与L剪辑", "J カット / L カット", "Sound leads (J) or trails (L) the picture cut; makes dialogue flow.", ["cut", "diegetic"]],
  ["transitions", "editing", "Dissolve / Fade / Wipe", "叠化 / 淡入淡出 / 划像", "ディゾルブ / フェード / ワイプ", "Soft transitions mark time passing or scene change.", ["cut"]],
  ["smash_cut", "editing", "Smash Cut", "硬切", "スマッシュカット", "Sudden cut from calm to loud (or reverse) for shock or comedy.", ["cut"]],
  ["pacing", "editing", "Pacing & Rhythm", "节奏", "テンポとリズム", "Shot length controls energy. Fast cuts raise excitement; long shots let feeling sink in.", ["tension", "long_take"]],
  ["murch_rule", "editing", "Rule of Six (Murch)", "默奇剪辑六法则", "マーチの6原則", "Walter Murch ranks cuts: emotion 51 %, story, rhythm, eye-trace, 2D plane, 3D space.", ["pacing", "eye_trace"]],
  ["assembly", "editing", "Assembly → Rough → Fine → Lock", "粗剪到定剪流程", "アッセンブル→ラフ→ファイン→ロック", "Edit stages; picture lock means no more timing changes, then sound and color start.", ["post_pipeline"]],
  ["color_grading", "editing", "Color Grading", "调色", "カラーグレーディング", "Shaping color and contrast after the edit for mood and consistency.", ["lut", "color_script"]],
  ["lut", "editing", "LUT / Log Footage", "查找表 / Log素材", "LUT / Log素材", "Log keeps dynamic range flat; a LUT maps it to a look. Blender uses AgX/Filmic view transforms.", ["color_grading", "view_transform"]],
  ["vfx", "editing", "VFX & Compositing", "视觉特效与合成", "VFX / コンポジット", "Combining real and CG layers; green screen keying, tracking, roto.", ["compositor", "chroma_key"]],
  ["chroma_key", "editing", "Chroma Key (Green Screen)", "色键抠像（绿幕）", "クロマキー（グリーンバック）", "Remove a solid color to replace the background.", ["vfx"]],
  // ───────── sound
  ["diegetic", "sound", "Diegetic vs Non-diegetic", "有源声与无源声", "劇中音 / 劇伴", "Diegetic = sound inside the story world; non-diegetic = score, narrator.", ["score", "l_cut"]],
  ["score", "sound", "Score", "配乐", "劇伴（スコア）", "Original music that guides emotion.", ["leitmotif", "diegetic"]],
  ["leitmotif", "sound", "Leitmotif", "主导动机", "ライトモチーフ", "A musical theme tied to a character or idea (Jaws, Star Wars).", ["score", "motif"]],
  ["foley", "sound", "Foley", "拟音", "フォーリー", "Recreating everyday sounds (steps, cloth) in a studio.", ["sound_design"]],
  ["sound_design", "sound", "Sound Design", "声音设计", "サウンドデザイン", "Creating the whole sound world, including invented sounds (lightsaber).", ["foley", "ambience"]],
  ["ambience", "sound", "Ambience / Room Tone", "环境声 / 房间底噪", "環境音 / ルームトーン", "Background sound of a place; record 30 s of room tone at every location.", ["sound_design"]],
  ["adr", "sound", "ADR / Dubbing", "自动对白替换 / 配音", "ADR / アフレコ", "Re-recording dialogue in studio. In animation, voices are often recorded first (pre-scoring).", ["lip_sync"]],
  ["double_system", "sound", "Double-System Sound", "双系统录音", "別録り（ダブルシステム）", "Sound recorded on a separate recorder; synced with the slate clap.", ["slate"]],
  ["sound_bridge", "sound", "Sound Bridge", "声音桥", "サウンドブリッジ", "Sound from the next scene starts early, linking scenes.", ["l_cut"]],
  ["silence", "sound", "Silence", "静默", "無音", "Sudden silence is one of the strongest sound tools.", ["tension"]],
  ["mix", "sound", "Mix (Dialogue / Music / Effects)", "混音", "ミックス（D/M/E）", "Balance the three stems; dialogue usually wins.", ["score", "foley"]],
  // ───────── preprod
  ["screenplay_format", "preprod", "Screenplay Format", "剧本格式", "脚本フォーマット", "Slugline (INT. ROOM – NIGHT), action, character, dialogue. ~1 page = 1 minute.", ["slugline"]],
  ["slugline", "preprod", "Slugline / Scene Heading", "场景标题", "柱（シーン見出し）", "INT./EXT., location, time of day.", ["screenplay_format"]],
  ["storyboard", "preprod", "Storyboard", "故事板 / 分镜", "絵コンテ", "Drawn panels of each shot with notes. Anime uses e-konte with timing.", ["animatic", "shot_list", "thumbnail"]],
  ["thumbnail", "preprod", "Thumbnails", "缩略草图", "サムネイル", "Tiny fast sketches to explore many ideas before a full board.", ["storyboard"]],
  ["animatic", "preprod", "Animatic / Story Reel", "动态分镜", "ビデオコンテ（アニマティック）", "Storyboards timed to sound; tests pacing before animation.", ["storyboard", "previs", "layout"]],
  ["previs", "preprod", "Previs", "预演 / 预可视化", "プリビズ", "Rough 3D version of shots with real lenses and timing (blocking in Blender).", ["animatic", "layout", "blocking_anim"]],
  ["concept_art", "preprod", "Concept Art", "概念设计", "コンセプトアート", "Paintings that define the look of characters, sets and mood.", ["lookbook", "model_sheet"]],
  ["color_script", "preprod", "Color Script", "色彩剧本", "カラースクリプト", "Small color keys for every sequence that map emotion over the film (Pixar).", ["tone", "symbolism", "color_contrast"]],
  ["model_sheet", "preprod", "Model Sheet / Turnaround", "角色设定图 / 三视图", "設定画 / 三面図", "Character from front, side, back with proportions; reference for modelers.", ["concept_art", "reference_image"]],
  ["layout", "preprod", "Layout", "布局", "レイアウト", "Placing camera, set and character poses for each shot; bridges board and animation.", ["previs", "animatic"]],
  ["pipeline", "preprod", "CG Production Pipeline", "CG制作流程", "CG制作パイプライン", "Story → design → modeling → rigging → layout → animation → FX → lighting → render → comp → edit.", ["modeling_overview", "rigging", "render_engine"]],
  ["post_pipeline", "preprod", "Post-Production", "后期制作", "ポストプロダクション", "Edit, VFX, sound, color, deliverables.", ["assembly", "color_grading", "mix"]],
  ["budget_triangle", "preprod", "Fast / Cheap / Good", "快、省、好三选二", "早い・安い・良い", "You can get only two. Choose with the producer.", ["producer", "schedule"]],
  // ───────── anim_principle
  ["twelve_principles", "anim_principle", "12 Principles of Animation", "动画十二法则", "アニメーションの12原則", "From Thomas & Johnston's 'The Illusion of Life' (1981). Base of all character animation.", ["squash_stretch", "anticipation", "timing"]],
  ["squash_stretch", "anim_principle", "Squash & Stretch", "挤压与拉伸", "つぶしと伸ばし", "Shape deforms with force; volume stays constant. Gives weight and flexibility.", ["twelve_principles", "bouncing_ball"]],
  ["anticipation", "anim_principle", "Anticipation", "预备动作", "予備動作（アンティシペーション）", "A small opposite move before the main action (crouch before jump).", ["twelve_principles", "follow_through"]],
  ["staging_clarity", "anim_principle", "Staging", "演出 / 布局清晰", "演出（ステージング）", "Present one idea clearly: pose, camera and silhouette all point at it.", ["silhouette", "composition"]],
  ["straight_pose", "anim_principle", "Straight Ahead vs Pose to Pose", "顺序动画与关键姿势法", "ストレートアヘッドとポーズトゥポーズ", "Draw frame after frame (fluid, chaotic) or plan key poses first (controlled).", ["keyframe", "blocking_anim"]],
  ["follow_through", "anim_principle", "Follow Through & Overlapping Action", "跟随与重叠动作", "フォロースルーとオーバーラップ", "Parts keep moving after the body stops; parts move at different times (hair, cloth, tail).", ["drag", "secondary_action"]],
  ["slow_in_out", "anim_principle", "Slow In & Slow Out (Ease)", "缓入缓出", "スローイン・スローアウト", "More frames near the start and end of a move; it accelerates and decelerates.", ["easing", "graph_editor"]],
  ["arcs", "anim_principle", "Arcs", "弧线运动", "アーク（弧）", "Natural motion follows curved paths. Check with motion paths.", ["motion_path"]],
  ["secondary_action", "anim_principle", "Secondary Action", "次要动作", "二次動作", "A smaller action that supports the main one (whistling while walking).", ["follow_through"]],
  ["timing", "anim_principle", "Timing", "时间节奏", "タイミング", "Number of frames for an action; sets weight, mood and speed.", ["spacing", "frame_rate"]],
  ["spacing", "anim_principle", "Spacing", "间距", "スペーシング", "Distance an object moves between frames. Same timing, different spacing = different feel.", ["timing", "slow_in_out"]],
  ["exaggeration", "anim_principle", "Exaggeration", "夸张", "誇張", "Push poses and timing beyond reality to make them read clearly.", ["appeal"]],
  ["solid_drawing", "anim_principle", "Solid Drawing", "扎实的绘画 / 立体感", "ソリッドドローイング", "Forms have volume, weight and balance in 3D space; avoid twinning (mirror poses).", ["twinning"]],
  ["appeal", "anim_principle", "Appeal", "吸引力", "アピール（魅力）", "Design and motion that the audience wants to watch; charisma, not only cuteness.", ["exaggeration", "shape_language"]],
  // ───────── anim_tech
  ["keyframe", "anim_tech", "Keyframe", "关键帧", "キーフレーム", "A frame where you set a value; the computer interpolates between keys.", ["interpolation", "breakdown"]],
  ["breakdown", "anim_tech", "Breakdown Pose", "中间关键姿势", "ブレイクダウン（中割りの要）", "The pose between two keys that defines how the move happens (arc, overlap).", ["keyframe", "inbetween"]],
  ["inbetween", "anim_tech", "In-between / Tweening", "中间画 / 补间", "中割り（動画）", "Frames between keys. In anime, 動画 artists draw them after 原画 (key animation).", ["breakdown", "genga"]],
  ["genga", "anim_tech", "Key Animation (Genga)", "原画", "原画", "Anime term: senior animator draws key frames; checked by the animation director (作画監督).", ["inbetween", "sakuga"]],
  ["sakuga", "anim_tech", "Sakuga", "作画（精彩作画）", "作画（サクガ）", "Fans' term for especially well-animated scenes in anime.", ["genga"]],
  ["on_twos", "anim_tech", "On Ones / On Twos / Threes", "一拍一 / 一拍二 / 一拍三", "1コマ / 2コマ / 3コマ打ち", "New drawing every 1, 2 or 3 frames at 24 fps. Anime often uses 3s; Spider-Verse mixes 1s and 2s.", ["frame_rate", "limited_animation"]],
  ["limited_animation", "anim_tech", "Limited Animation", "有限动画", "リミテッドアニメーション", "Reuse cels, hold frames, animate only mouths. Pioneered by UPA, used by TV anime.", ["on_twos"]],
  ["blocking_anim", "anim_tech", "Blocking (Animation)", "动画粗排 / 卡关键", "ブロッキング（アニメ）", "First pass with key poses in stepped/constant mode to judge timing.", ["spline_pass", "straight_pose", "previs"]],
  ["spline_pass", "anim_tech", "Splining & Polish", "曲线化与精修", "スプライン化とポリッシュ", "Switch to Bézier interpolation, clean curves, add overlap and details.", ["blocking_anim", "graph_editor"]],
  ["interpolation", "anim_tech", "Interpolation (Constant/Linear/Bézier)", "插值（常量/线性/贝塞尔）", "補間（コンスタント/リニア/ベジェ）", "How values change between keys. Press T in Blender to set it.", ["keyframe", "easing"]],
  ["easing", "anim_tech", "Easing Curves", "缓动曲线", "イージング", "Curve shape that controls acceleration: ease in, ease out, ease in-out.", ["slow_in_out", "graph_editor"]],
  ["graph_editor", "anim_tech", "Graph Editor (F-Curves)", "曲线编辑器", "グラフエディター（Fカーブ）", "Shows animation curves; slope = speed. Flat = hold, steep = fast.", ["easing", "dope_sheet"]],
  ["dope_sheet", "anim_tech", "Dope Sheet / X-Sheet", "摄影表", "ドープシート / タイムシート", "Grid of keys over time. Traditional exposure sheet (タイムシート) in 2D.", ["graph_editor", "nla"]],
  ["motion_path", "anim_tech", "Motion Path", "运动路径", "モーションパス", "A displayed line of where a point travels; checks arcs and spacing.", ["arcs"]],
  ["bouncing_ball", "anim_tech", "Bouncing Ball Exercise", "弹跳球练习", "ボールバウンス", "First animation exercise: timing, spacing, squash & stretch, decay.", ["squash_stretch", "timing"]],
  ["walk_cycle", "anim_tech", "Walk Cycle", "走路循环", "歩きのサイクル", "Contact, down, passing, up poses repeated; a key test of weight and character.", ["cycle", "contact_pose"]],
  ["contact_pose", "anim_tech", "Contact / Passing Pose", "接触姿势 / 交错姿势", "接地ポーズ / パッシングポーズ", "Contact: heel touches ground. Passing: legs cross, body high.", ["walk_cycle"]],
  ["cycle", "anim_tech", "Cycle / Loop", "循环动画", "ループ（サイクル）", "Animation that repeats seamlessly. Blender: Cycles F-modifier.", ["walk_cycle", "nla"]],
  ["drag", "anim_tech", "Drag / Offset", "拖拽 / 偏移", "ドラッグ / オフセット", "Shift keys of child parts a few frames later to get overlapping action.", ["follow_through"]],
  ["moving_hold", "anim_tech", "Moving Hold", "动态保持", "ムービングホールド", "Pose holds but drifts slightly so the character stays alive.", ["keyframe"]],
  ["twinning", "anim_tech", "Twinning", "对称僵硬（孪生姿势）", "ツイニング", "Both arms/legs do the same thing at the same time; looks stiff. Break symmetry.", ["solid_drawing"]],
  ["line_of_action", "anim_tech", "Line of Action", "动态线", "アクションライン", "One curved line through the pose; strong pose = clear line.", ["silhouette", "appeal"]],
  ["lip_sync", "anim_tech", "Lip Sync / Phonemes", "口型同步 / 音素", "リップシンク / 口パク", "Mouth shapes (visemes) timed to recorded dialogue; animate jaw first, then shapes.", ["adr", "shape_keys"]],
  ["acting_anim", "anim_tech", "Acting for Animation", "动画表演", "アニメーションの演技", "Think, then act: the eyes move first, thoughts show before actions (Ed Hooks).", ["anticipation", "objective"]],
  ["reference_video", "anim_tech", "Video Reference", "参考视频", "参考動画", "Film yourself acting the shot; study timing, then exaggerate.", ["acting_anim"]],
  ["mocap", "anim_tech", "Motion Capture", "动作捕捉", "モーションキャプチャ", "Record real performance onto a rig; still needs cleanup and exaggeration.", ["retarget", "rigging"]],
  ["retarget", "anim_tech", "Retargeting", "动作重定向", "リターゲット", "Transfer animation from one skeleton to another of different proportions.", ["mocap", "armature"]],
  ["stop_motion", "anim_tech", "Stop Motion", "定格动画", "ストップモーション", "Move physical puppets frame by frame (Laika, Aardman).", ["on_twos"]],
  ["rotoscope", "anim_tech", "Rotoscoping", "转描", "ロトスコープ", "Tracing over live action frames (Fleischer, A Scanner Darkly).", ["reference_video"]],
  ["npr", "anim_tech", "NPR / Toon Shading", "非真实感渲染 / 卡通着色", "NPR / トゥーンシェーディング", "Make 3D look 2D or painted (Arcane, Spider-Verse, Guilty Gear). Blender: Shader to RGB + ColorRamp, Line Art, Freestyle.", ["shader_to_rgb", "grease_pencil"]],
  ["grease_pencil", "anim_tech", "Grease Pencil", "蜡笔工具", "グリースペンシル", "Blender's 2D drawing and animation tool inside 3D space.", ["npr", "storyboard"]],
  ["smear", "anim_tech", "Smear Frames", "拖影帧", "スメア（オバケ）", "A stretched frame that fakes motion blur in fast moves.", ["squash_stretch", "on_twos"]],
  // ───────── modeling
  ["modeling_overview", "modeling", "3D Modeling Overview", "三维建模概述", "3Dモデリング概要", "Build shapes from vertices, edges and faces. Methods: box/poly, sculpting, curves, procedural.", ["vertex_edge_face", "sculpting", "geometry_nodes"]],
  ["vertex_edge_face", "modeling", "Vertex / Edge / Face", "顶点 / 边 / 面", "頂点 / 辺 / 面", "The 3 mesh elements. Blender keys 1, 2, 3 in Edit Mode switch selection mode.", ["polygon", "edit_mode"]],
  ["polygon", "modeling", "Polygon: Tri / Quad / N-gon", "多边形：三角/四边/多边", "ポリゴン：三角 / 四角 / Nゴン", "Quads deform and subdivide best; triangles for games; avoid N-gons on deforming parts.", ["topology", "subdivision"]],
  ["topology", "modeling", "Topology", "拓扑", "トポロジー", "How the edges flow over the mesh. Good flow follows muscles and deforms cleanly.", ["edge_loop", "pole", "retopology"]],
  ["edge_loop", "modeling", "Edge Loop / Ring", "循环边 / 并排边", "エッジループ / リング", "A connected line of edges around a form. Alt+click selects; Ctrl+R adds one.", ["topology", "loop_cut"]],
  ["pole", "modeling", "Pole", "极点", "ポール（極点）", "A vertex with 3 or 5+ edges. Place them where they do not deform badly.", ["topology"]],
  ["loop_cut", "modeling", "Loop Cut (Ctrl+R)", "环切", "ループカット", "Adds an edge loop to add detail or support edges.", ["edge_loop", "support_loop"]],
  ["extrude", "modeling", "Extrude (E)", "挤出", "押し出し", "Pulls new geometry from selection. Core of box modeling.", ["inset", "box_modeling"]],
  ["inset", "modeling", "Inset (I)", "内插面", "面を差し込む（インセット）", "Makes a smaller face inside a face.", ["extrude"]],
  ["bevel", "modeling", "Bevel (Ctrl+B)", "倒角", "ベベル", "Rounds sharp edges; real objects never have perfect edges, so bevels catch light.", ["support_loop", "hard_surface"]],
  ["box_modeling", "modeling", "Box Modeling", "盒子建模", "ボックスモデリング", "Start from a cube, extrude and cut to shape.", ["extrude", "blockout"]],
  ["blockout", "modeling", "Blockout", "白模 / 体块草模", "ブロックアウト", "Rough shapes with primitives to check scale and composition before detail.", ["box_modeling", "previs"]],
  ["subdivision", "modeling", "Subdivision Surface", "细分曲面", "サブディビジョンサーフェス", "Modifier that smooths a low-poly cage (Ctrl+1..3).", ["support_loop", "modifier"]],
  ["support_loop", "modeling", "Support / Holding Edges", "支撑边 / 保护线", "サポートエッジ", "Extra loops near edges that keep them sharp under subdivision.", ["subdivision", "bevel"]],
  ["hard_surface", "modeling", "Hard-Surface Modeling", "硬表面建模", "ハードサーフェス", "Mechanical objects: booleans, bevels, weighted normals.", ["boolean", "bevel"]],
  ["boolean", "modeling", "Boolean", "布尔运算", "ブーリアン", "Union, difference, intersect of meshes. Clean topology after use.", ["hard_surface"]],
  ["sculpting", "modeling", "Digital Sculpting", "数字雕刻", "デジタルスカルプト", "Shape high-res mesh with brushes (clay, grab, crease) like clay. Use Dyntopo or Multires.", ["retopology", "normal_map"]],
  ["retopology", "modeling", "Retopology", "重新拓扑", "リトポロジー", "Build a clean low-poly mesh over a sculpt for animation.", ["sculpting", "topology", "baking"]],
  ["uv_unwrap", "modeling", "UV Unwrapping", "UV展开", "UV展開", "Flatten 3D surface to 2D so textures map onto it. Mark seams, then unwrap (U).", ["seams", "texture_map", "texel_density"]],
  ["seams", "modeling", "UV Seams", "UV接缝", "UVシーム", "Cut lines where the mesh opens; hide them in less visible places.", ["uv_unwrap"]],
  ["texel_density", "modeling", "Texel Density", "纹素密度", "テクセル密度", "Texture pixels per unit; keep it even so details look consistent.", ["uv_unwrap"]],
  ["normals", "modeling", "Normals", "法线", "法線", "Direction a face points. Flipped normals render wrong; Shift+N recalculates.", ["shade_smooth", "normal_map"]],
  ["shade_smooth", "modeling", "Shade Smooth / Auto Smooth", "平滑着色 / 自动平滑", "スムーズシェード / 自動スムーズ", "Interpolates normals for smooth look; auto smooth keeps hard angles sharp.", ["normals"]],
  ["modifier", "modeling", "Modifier Stack", "修改器堆栈", "モディファイアースタック", "Non-destructive operations applied in order (Mirror → Subdivision → Bevel). Order matters.", ["mirror_mod", "subdivision", "array_mod"]],
  ["mirror_mod", "modeling", "Mirror Modifier", "镜像修改器", "ミラーモディファイアー", "Model half; the other half mirrors. Enable clipping at the center.", ["modifier"]],
  ["array_mod", "modeling", "Array / Curve Modifier", "阵列 / 曲线修改器", "配列 / カーブモディファイアー", "Repeat an object; bend it along a curve (chains, fences).", ["modifier", "geometry_nodes"]],
  ["geometry_nodes", "modeling", "Geometry Nodes", "几何节点", "ジオメトリーノード", "Blender's procedural node system for scatter, generate and deform geometry.", ["procedural", "modifier"]],
  ["procedural", "modeling", "Procedural Modeling", "程序化建模", "プロシージャルモデリング", "Create with rules and parameters, not by hand; easy to change.", ["geometry_nodes"]],
  ["lod", "modeling", "LOD & Poly Budget", "细节层级与面数预算", "LODとポリゴン予算", "Fewer polys for far objects; key for games and big scenes.", ["topology"]],
  ["kitbash", "modeling", "Kitbashing", "拼装建模", "キットバッシュ", "Combine premade parts to build fast.", ["hard_surface", "asset_library"]],
  ["shape_language", "modeling", "Shape Language", "形状语言", "シェイプランゲージ", "Circle = friendly, square = stable, triangle = danger. Drives character design.", ["appeal", "silhouette"]],
  ["reference_image", "modeling", "Reference Images", "参考图", "リファレンス画像", "Load front/side images as background (Add > Image > Reference) before modeling.", ["model_sheet"]],
  ["scale_units", "modeling", "Real-World Scale", "真实尺度", "実寸スケール", "Model in meters with applied scale (Ctrl+A). Physics, light and DOF depend on it.", ["apply_transform"]],
  // ───────── rigging
  ["rigging", "rigging", "Rigging", "绑定", "リギング", "Building a control skeleton so animators can pose a model.", ["armature", "skinning", "ik_fk"]],
  ["armature", "rigging", "Armature / Bones", "骨架 / 骨骼", "アーマチュア / ボーン", "Blender's skeleton object. Bones have head, tail, roll and parent.", ["rigging", "bone_hierarchy"]],
  ["bone_hierarchy", "rigging", "Bone Hierarchy / Parenting", "骨骼层级 / 父子关系", "ボーン階層 / 親子関係", "Child bones follow parent bones (hand follows forearm).", ["armature", "fk"]],
  ["skinning", "rigging", "Skinning / Weight Painting", "蒙皮 / 权重绘制", "スキニング / ウェイトペイント", "Assign how much each vertex follows each bone (0–1). Ctrl+P > With Automatic Weights starts it.", ["armature", "vertex_group"]],
  ["vertex_group", "rigging", "Vertex Group", "顶点组", "頂点グループ", "Named set of vertices with weights; used by bones and modifiers.", ["skinning"]],
  ["fk", "rigging", "Forward Kinematics (FK)", "正向运动学", "フォワードキネマティクス（FK）", "Rotate each bone from root to tip. Good for arcs and swings.", ["ik_fk", "ik"]],
  ["ik", "rigging", "Inverse Kinematics (IK)", "反向运动学", "インバースキネマティクス（IK）", "Move the end (hand/foot); the chain solves itself. Good for planted feet.", ["ik_fk", "pole_target"]],
  ["ik_fk", "rigging", "IK/FK Switch", "IK/FK切换", "IK/FK切り替え", "Rig feature to blend between IK and FK per limb.", ["fk", "ik"]],
  ["pole_target", "rigging", "Pole Target", "极向目标", "ポールターゲット", "Controls which way a knee or elbow points in IK.", ["ik"]],
  ["constraints", "rigging", "Constraints", "约束", "コンストレイント", "Rules like Copy Rotation, Track To, Child Of that link objects or bones.", ["rigging", "camera_rig"]],
  ["rigify", "rigging", "Rigify", "Rigify自动绑定", "Rigify", "Blender add-on that generates a full production rig from a metarig.", ["rigging", "armature"]],
  ["shape_keys", "rigging", "Shape Keys / Blend Shapes", "形态键 / 混合变形", "シェイプキー / ブレンドシェイプ", "Stored mesh deformations mixed with sliders; used for faces and lip sync.", ["lip_sync", "facial_rig"]],
  ["facial_rig", "rigging", "Facial Rig", "面部绑定", "フェイシャルリグ", "Bones + shape keys + drivers for brows, eyes, mouth. FACS is a common reference.", ["shape_keys", "drivers"]],
  ["drivers", "rigging", "Drivers", "驱动器", "ドライバー", "A property controlled by another property or expression (slider opens jaw).", ["facial_rig", "constraints"]],
  ["pose_mode", "rigging", "Pose Mode / Rest Pose", "姿态模式 / 静止姿态", "ポーズモード / レストポーズ", "Pose Mode animates bones; rest pose (often T or A pose) is the bind state.", ["armature"]],
  // ───────── blender
  ["blender_ui", "blender", "Blender Interface & Workspaces", "Blender界面与工作区", "Blenderのインターフェースとワークスペース", "Tabs like Layout, Modeling, Sculpting, Shading, Animation, Compositing set editor layouts.", ["edit_mode", "outliner"]],
  ["edit_mode", "blender", "Object vs Edit Mode (Tab)", "物体模式与编辑模式", "オブジェクトモードと編集モード", "Object Mode moves whole objects; Edit Mode changes vertices.", ["vertex_edge_face", "blender_ui"]],
  ["grs", "blender", "G / R / S Transform", "移动 / 旋转 / 缩放", "移動 / 回転 / 拡大縮小（G/R/S）", "G grab, R rotate, S scale; then X/Y/Z to lock an axis, type a number.", ["apply_transform"]],
  ["apply_transform", "blender", "Apply Transform (Ctrl+A)", "应用变换", "トランスフォームの適用", "Bake scale/rotation into mesh so modifiers and physics work correctly.", ["scale_units", "grs"]],
  ["outliner", "blender", "Outliner & Collections", "大纲视图与集合", "アウトライナーとコレクション", "Scene tree. Group objects in collections; toggle visibility for render/viewport.", ["view_layer", "link_append"]],
  ["link_append", "blender", "Link vs Append", "链接与追加", "リンクとアペンド", "Append copies data in; Link references another .blend (good for shared assets, library overrides).", ["asset_library", "outliner"]],
  ["asset_library", "blender", "Asset Browser", "资产浏览器", "アセットブラウザー", "Drag-and-drop library of materials, objects, poses.", ["link_append", "kitbash"]],
  ["shader_editor", "blender", "Shader Editor (Nodes)", "着色器编辑器（节点）", "シェーダーエディター（ノード）", "Build materials by connecting nodes into the Material Output.", ["principled_bsdf", "texture_map"]],
  ["principled_bsdf", "blender", "Principled BSDF", "原理化BSDF", "プリンシプルBSDF", "One physically based shader with base color, metallic, roughness, IOR, transmission, emission.", ["pbr", "shader_editor"]],
  ["pbr", "blender", "PBR (Physically Based Rendering)", "基于物理的渲染", "PBR（物理ベースレンダリング)", "Materials obey energy conservation; metal/rough workflow.", ["principled_bsdf", "texture_map"]],
  ["texture_map", "blender", "Texture Maps", "贴图", "テクスチャマップ", "Base color, roughness, metallic, normal, height. Non-color data for all except color.", ["normal_map", "uv_unwrap", "pbr"]],
  ["normal_map", "blender", "Normal / Bump Map", "法线贴图 / 凹凸贴图", "ノーマルマップ / バンプマップ", "Fakes small detail by changing shading normals, not geometry.", ["baking", "texture_map"]],
  ["baking", "blender", "Baking", "烘焙", "ベイク", "Render high-poly detail, light or AO into textures for a low-poly mesh.", ["normal_map", "retopology"]],
  ["texture_paint", "blender", "Texture Painting", "纹理绘制", "テクスチャペイント", "Paint color directly on the model; Substance Painter is the industry tool.", ["texture_map"]],
  ["hdri", "blender", "HDRI World Lighting", "HDRI环境光照", "HDRI環境照明", "360° high-dynamic image lights the scene realistically. Poly Haven gives free ones.", ["world", "key_light"]],
  ["world", "blender", "World Settings", "世界环境", "ワールド設定", "Background color/HDRI and volume for the whole scene.", ["hdri", "volumetric"]],
  ["light_types", "blender", "Light Types", "灯光类型", "ライトの種類", "Point, Sun, Spot, Area. Area lights give soft light; Sun for daylight.", ["hard_soft", "lighting_three_point"]],
  ["camera_blender", "blender", "Blender Camera Settings", "Blender相机设置", "Blenderカメラ設定", "Focal length, sensor, DOF (focus object, f-stop), clip range. Ctrl+Numpad0 sets active camera.", ["focal_length", "dof", "camera_rig"]],
  ["camera_rig", "blender", "Camera Rig / Track To", "相机绑定 / 追踪约束", "カメラリグ / トラックトゥ", "Parent camera to empties or a path; Track To keeps aim on target. Add-on: Camera Rigs (dolly, crane).", ["constraints", "dolly"]],
  ["markers", "blender", "Timeline Markers & Camera Switching", "时间线标记与相机切换", "タイムラインマーカーとカメラ切替", "Bind cameras to markers (Ctrl+B) to cut between cameras in one scene.", ["cut", "vse"]],
  ["nla", "blender", "NLA Editor", "非线性动画编辑器", "NLAエディター", "Stack and blend actions (walk + wave) like clips in a video editor.", ["dope_sheet", "cycle"]],
  ["render_engine", "blender", "Render Engines: EEVEE vs Cycles", "渲染引擎：EEVEE与Cycles", "レンダーエンジン：EEVEEとCycles", "EEVEE: real-time raster, fast previews. Cycles: path tracer, realistic light, slower.", ["eevee", "cycles"]],
  ["eevee", "blender", "EEVEE", "EEVEE实时渲染", "EEVEE", "Real-time engine; EEVEE Next adds better GI and shadows. Good for stylized and previs.", ["render_engine", "npr"]],
  ["cycles", "blender", "Cycles", "Cycles路径追踪", "Cycles", "Path tracer; set samples, denoise (OIDN/OptiX), light paths bounces.", ["render_engine", "samples_noise"]],
  ["samples_noise", "blender", "Samples & Denoising", "采样与降噪", "サンプル数とノイズ除去", "More samples = less noise but longer render. Denoiser cleans remaining grain.", ["cycles", "noise"]],
  ["noise", "blender", "Noise / Fireflies", "噪点 / 萤火虫噪点", "ノイズ / ファイアフライ", "Grain from too few samples; bright dots from caustics. Clamp indirect light.", ["samples_noise", "iso"]],
  ["view_transform", "blender", "View Transform (AgX / Filmic)", "视图变换（AgX/Filmic）", "ビュー変換（AgX / Filmic）", "Maps scene light to screen like film; AgX is default since Blender 4.0.", ["lut", "color_grading"]],
  ["view_layer", "blender", "View Layers & Render Passes", "视图层与渲染通道", "ビューレイヤーとレンダーパス", "Split render into layers and passes (diffuse, AO, Z, cryptomatte) for compositing.", ["compositor"]],
  ["compositor", "blender", "Compositor", "合成器", "コンポジター", "Node editor that combines passes: glare, color balance, defocus, lens distortion.", ["view_layer", "vfx"]],
  ["vse", "blender", "Video Sequencer (VSE)", "视频序列编辑器", "ビデオシーケンサー", "Blender's built-in editor to cut shots and sound.", ["markers", "assembly"]],
  ["output_settings", "blender", "Output Settings", "输出设置", "出力設定", "Resolution, frame rate, frame range; render to PNG/EXR image sequence, then encode with ffmpeg.", ["frame_rate", "render_farm"]],
  ["render_farm", "blender", "Render Farm / Command-Line Render", "渲染农场 / 命令行渲染", "レンダーファーム / コマンドラインレンダー", "blender -b file.blend -a renders in background; farms split frames across machines.", ["output_settings"]],
  ["physics_sim", "blender", "Physics Simulations", "物理模拟", "物理シミュレーション", "Rigid body, cloth, fluid (Mantaflow), smoke, particles, hair. Bake before render.", ["cloth_hair", "geometry_nodes"]],
  ["cloth_hair", "blender", "Cloth & Hair", "布料与毛发", "布と髪", "Cloth sim for costumes; hair curves with Geometry Nodes groom tools.", ["physics_sim", "follow_through"]],
  ["shader_to_rgb", "blender", "Shader to RGB (EEVEE)", "Shader转RGB", "シェーダーからRGBへ", "Converts lighting to color so a ColorRamp can make toon bands. EEVEE only.", ["npr", "eevee"]],
  ["freestyle_lineart", "blender", "Freestyle / Line Art", "Freestyle描线 / 线稿修改器", "Freestyle / ラインアート", "Draw outline strokes on 3D renders for comic or anime look.", ["npr", "grease_pencil"]],
  ["blend_shortcuts", "blender", "Key Shortcuts", "常用快捷键", "主要ショートカット", "F3 search, Shift+A add, Ctrl+Space maximize, Numpad . frame selected, I insert key.", ["blender_ui"]],
  ["python_api", "blender", "Python Scripting (bpy)", "Python脚本（bpy）", "Pythonスクリプト（bpy）", "Automate Blender: bpy.data, bpy.ops, bpy.context. Use for pipelines and AI tools (MCP).", ["render_farm"]],
  // ───────── color
  ["color_wheel", "color", "Color Wheel & Harmony", "色环与配色", "色相環と配色", "Complementary, analogous, triadic schemes create balance or tension.", ["color_contrast", "teal_orange"]],
  ["color_contrast", "color", "Warm vs Cool Contrast", "冷暖对比", "暖色と寒色の対比", "Warm colors advance and feel emotional; cool colors recede and feel calm or cold.", ["color_wheel", "color_temp"]],
  ["teal_orange", "color", "Teal & Orange", "青橙色调", "ティール＆オレンジ", "Skin tones (orange) against complementary teal shadows; common blockbuster look.", ["color_wheel", "color_grading"]],
  ["hsv", "color", "Hue, Saturation, Value", "色相、饱和度、明度", "色相・彩度・明度", "Three parts of color. Value (brightness) reads first; test pictures in grayscale.", ["value_structure"]],
  ["value_structure", "color", "Value Structure / Notan", "明暗结构 / 浓淡", "明暗構成（ノータン）", "Simplify image into 2–3 values; strong value design reads at thumbnail size.", ["hsv", "silhouette"]],
  ["color_meaning", "color", "Color Psychology", "色彩心理", "色彩心理", "Red danger/love, blue calm/sad, green nature/sickness. Meaning depends on context and culture.", ["symbolism", "color_script"]],
  ["dynamic_range", "color", "Dynamic Range / HDR", "动态范围 / 高动态范围", "ダイナミックレンジ / HDR", "Range from darkest to brightest recorded. Expose to keep highlights.", ["lut", "view_transform"]],
  // ───────── history
  ["lumiere", "history", "Lumière & Méliès", "卢米埃尔与梅里爱", "リュミエールとメリエス", "1895 first screenings (real life) vs Méliès trick films (fantasy, A Trip to the Moon).", ["griffith"]],
  ["griffith", "history", "D.W. Griffith & Classic Grammar", "格里菲斯与经典电影语法", "グリフィスと古典的文法", "Built cross-cutting, close-ups and continuity in early feature films.", ["cross_cutting", "continuity_editing"]],
  ["german_exp", "history", "German Expressionism", "德国表现主义", "ドイツ表現主義", "Distorted sets and hard shadows show inner states (Caligari, Metropolis). Led to noir.", ["film_noir", "low_key"]],
  ["film_noir", "history", "Film Noir", "黑色电影", "フィルム・ノワール", "1940s American crime films: low-key light, femme fatale, fate, rain.", ["low_key", "german_exp"]],
  ["neorealism", "history", "Italian Neorealism", "意大利新现实主义", "イタリア・ネオレアリズモ", "Real locations, non-actors, poor people's lives (Bicycle Thieves).", ["new_wave"]],
  ["new_wave", "history", "French New Wave", "法国新浪潮", "ヌーヴェル・ヴァーグ", "Godard, Truffaut: handheld, jump cuts, breaking rules, auteur spirit.", ["jump_cut", "auteur"]],
  ["japanese_masters", "history", "Kurosawa, Ozu, Mizoguchi", "黑泽明、小津安二郎、沟口健二", "黒澤明・小津安二郎・溝口健二", "Kurosawa: weather, movement, telephoto action. Ozu: low 'tatami' camera, pillow shots. Mizoguchi: long takes.", ["pillow_shot", "long_take"]],
  ["pillow_shot", "history", "Pillow Shot", "枕镜头 / 空镜", "枕ショット（空ショット）", "Ozu's empty shots of places between scenes; give rest and meaning.", ["japanese_masters", "pacing"]],
  ["hk_wuxia", "history", "Hong Kong & Chinese Cinema", "香港与华语电影", "香港・中華圏映画", "Wuxia choreography, Wong Kar-wai's step-printing and mood, Zhang Yimou's color.", ["color_meaning", "action_choreo"]],
  ["action_choreo", "history", "Action Choreography", "动作设计", "アクション振付", "Clear geography, wide enough shots, rhythm of hits; Jackie Chan's one-two-three cutting.", ["180_rule", "pacing"]],
  ["new_hollywood", "history", "New Hollywood", "新好莱坞", "アメリカン・ニューシネマ", "1967–80: director power, gritty realism (The Godfather, Taxi Driver).", ["auteur"]],
  ["disney_golden", "history", "Disney Golden Age", "迪士尼黄金时代", "ディズニー黄金期", "Snow White (1937) to Bambi: multiplane camera, Nine Old Men, 12 principles.", ["twelve_principles", "multiplane"]],
  ["multiplane", "history", "Multiplane Camera", "多层摄影台", "マルチプレーンカメラ", "Layers of art at different distances create parallax depth in 2D.", ["disney_golden", "parallax"]],
  ["parallax", "history", "Parallax", "视差", "視差（パララックス）", "Near things move faster than far things when the camera moves; key to depth.", ["multiplane", "dolly"]],
  ["anime_history", "history", "Anime: Tezuka to Ghibli to Today", "日本动画：从手冢到吉卜力", "アニメ史：手塚からジブリ、現代へ", "Tezuka's limited TV anime, Miyazaki/Takahata's Ghibli, Oshii, Kon, Shinkai, Trigger.", ["limited_animation", "ma"]],
  ["ma", "history", "Ma (間) – Pause", "间（停顿美学）", "間（ま）", "Japanese concept of meaningful pause. Miyazaki keeps quiet moments between action.", ["pillow_shot", "silence"]],
  ["pixar_cg", "history", "Pixar & CG Animation", "皮克斯与CG动画", "ピクサーとCGアニメ", "Toy Story (1995) first CG feature. Pixar's story rules and Braintrust notes.", ["pipeline", "pixar_rules"]],
  ["pixar_rules", "history", "Pixar's 22 Rules / Story Spine", "皮克斯22条法则 / 故事脊柱", "ピクサーの22のルール / ストーリースパイン", "'Once upon a time... Every day... One day... Because of that... Until finally...'", ["three_act", "premise"]],
  ["spiderverse", "history", "Spider-Verse Style", "蜘蛛侠：平行宇宙风格", "スパイダーバース様式", "Mixed frame rates, halftone, comic lines in CG; opened the stylized CG wave.", ["npr", "on_twos"]],
  ["blender_open_movies", "history", "Blender Open Movies", "Blender开放电影", "Blenderオープンムービー", "Studio films (Big Buck Bunny, Sprite Fright, Charge) with free source files to study.", ["pipeline", "blender_ui"]],
  // ───────── modern
  ["virtual_production", "modern", "Virtual Production / LED Volume", "虚拟制片 / LED影棚", "バーチャルプロダクション / LEDボリューム", "Real-time engine backgrounds on LED walls (The Mandalorian); in-camera VFX.", ["vfx", "previs"]],
  ["ai_video", "modern", "AI Video Generation", "AI视频生成", "AI動画生成", "Text/image-to-video models make shots from prompts; control with keyframes, references and previs.", ["previs", "shot_list"]],
  ["prompt_shot", "modern", "Prompting as Shot Design", "以提示词设计镜头", "プロンプトによるショット設計", "Write prompts like a shot list: subject, action, shot size, lens, light, movement, mood.", ["ai_video", "shot_size"]],
  ["consistency", "modern", "Character Consistency", "角色一致性", "キャラクターの一貫性", "Keep the same face, costume and proportions between shots; use reference sheets and LoRA.", ["model_sheet", "ai_video"]],
  ["realtime_engine", "modern", "Real-time Engines (Unreal, Godot)", "实时引擎", "リアルタイムエンジン", "Game engines used for previs, cinematics and animated series.", ["virtual_production", "eevee"]],
  // ───────── camera
  ["motion_blur", "camera", "Motion Blur", "运动模糊", "モーションブラー", "Streaks from movement during the exposure. It makes motion look smooth; too little looks choppy, too much looks smeared.", ["shutter", "frame_rate", "smear"]],
  // ───────── composition
  ["contrast", "composition", "Contrast", "对比", "コントラスト", "Difference in brightness, color, size or motion. The eye goes to the area of highest contrast first.", ["visual_weight", "value_structure", "contrast_ratio"]],
]

export const TERMS: Term[] = raw.map(([id, cat, name, zh, ja, short, related]) => ({ id, cat, name, zh, ja, short, related }))
export const TERM_MAP: Record<string, Term> = Object.fromEntries(TERMS.map((t) => [t.id, t]))
export const CAT_MAP: Record<string, Category> = Object.fromEntries(CATS.map((c) => [c.id, c]))
