import type { Scene, Step } from '../../shared/types'
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({ prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why })

// Batch B1: drama, romance, family, coming-of-age, slice-of-life. Live action and anime.
export const SCENES_B1: Scene[] = [
  {
    id: 'b1-empty-chair-dinner', title: 'The empty chair at dinner', genre: 'Family drama',
    setup: 'Three months after their father died, a mother and two teenage sons eat dinner. Nobody sits in his chair. Nobody talks about him. The younger son puts a fourth plate on the table by habit.',
    goal: 'The audience must feel the missing person in every frame.',
    terms: ['negative_space', 'show_dont_tell', 'ambience', 'long_take', 'symmetry'], tags: ['grief', 'family'],
    checkpoints: [
      { label: 'Story beat', dept: 'story', context: 'The draft has the mother say: “We all miss your father so much.”',
        step: s('What do you do with the line?', [['a', 'Keep it and add music under it'], ['b', 'Cut it; the mother quietly takes the fourth plate away'], ['c', 'Give the line to the younger son instead']], 'b', 'An action can carry the feeling: [[show_dont_tell]].') },
      { label: 'Frame', dept: 'composition', context: 'The table is square. The empty chair faces the camera.',
        step: s('How do you frame the wide shot?', [['a', 'Tight on the mother only'], ['b', 'A high angle on the food'], ['c', 'Centered on the empty chair, the family at the edges'], ['d', 'Dutch angle from under the table']], 'c', 'The empty chair in the middle is [[negative_space]] that carries the weight.') },
      { label: 'Shot length', dept: 'camera', context: 'The family eats for 90 seconds without words.',
        step: s('How do you shoot it?', [['a', 'One static long take; let the silence play'], ['b', 'Twenty fast cuts on forks'], ['c', 'A spinning crane move'], ['d', 'Handheld whip pans']], 'a', 'A static [[long_take]] makes the audience sit in the discomfort.') },
      { label: 'Sound', dept: 'sound', context: 'The room is very quiet.',
        step: s('What do we hear?', [['a', 'A sad piano score'], ['b', 'Nothing at all, full mute'], ['c', 'Cutlery on plates, a clock, the fridge hum']], 'c', 'Small room sounds are [[ambience]]; they make the silence feel loud and real.') },
    ],
    outcome: 'The film never names the father. The [[negative_space]] of the chair, the [[long_take]] and the plain [[ambience]] say it for us.',
    ref: 'Ordinary People (1980)',
  },
  {
    id: 'b1-first-day-office', title: 'First day at the office', genre: 'Slice of life',
    setup: 'Yuki (22) starts her first job at a big design firm. She does not know where to sit, and everyone looks busy. Her boss forgets she is coming.',
    goal: 'The audience must feel small and lost with her, then smile at a tiny win.',
    terms: ['wide_shot', 'pov_shot', 'high_key', 'jump_cut', 'shot_size'], tags: ['first job', 'humor'],
    checkpoints: [
      { label: 'Shot size', dept: 'camera', context: 'Yuki steps out of the lift into an open office of 80 desks.',
        step: s('Which shot first?', [['a', 'An extreme close-up on her badge'], ['b', 'A very wide shot: she is tiny at the edge of the room'], ['c', 'A two-shot with her boss']], 'b', 'A small figure in a big [[wide_shot]] shows she feels lost.') },
      { label: 'Light', dept: 'lighting', context: 'It is a modern office with big windows.',
        step: s('What light style fits this light comedy?', [['a', 'Bright, soft, even high-key light'], ['b', 'Hard low-key light with deep shadows'], ['c', 'Only red practicals']], 'a', 'A light, friendly mood suits [[high_key]] light.') },
      { label: 'Edit', dept: 'editing', context: 'She tries five desks in one morning; each person says “That seat is taken.”',
        step: s('How do you cut the five tries?', [['a', 'Show each try in full, 2 minutes each'], ['b', 'A slow dissolve between each'], ['c', 'Quick jump cuts, same framing, she moves desk to desk']], 'c', 'Same frame, time skips: a [[jump_cut]] makes the repeat funny.') },
      { label: 'Key shot', dept: 'camera', context: 'At last a coworker slides a coffee to her.',
        step: s('How do you show the coffee?', [['a', 'From her eyes as the cup arrives'], ['b', 'From the ceiling'], ['c', 'A drone outside the window']], 'a', 'A [[pov_shot]] puts us in her seat for the small win.') },
    ],
    outcome: 'The [[wide_shot]] makes her small, the [[jump_cut]] makes it funny, and the [[pov_shot]] gives us her relief.',
    ref: 'The Intern (2015)',
  },
  {
    id: 'b1-anime-cherry-confession', title: 'Letter under the cherry tree', genre: 'Anime romance',
    setup: 'In a TV anime, Haru (16) waits under a cherry tree to give a letter to his classmate Sora. The budget is small. The scene must still feel like the peak of the episode.',
    goal: 'A big emotional moment on a TV anime budget.',
    terms: ['limited_animation', 'moving_hold', 'sakuga', 'genga', 'color_script'], tags: ['anime', 'romance'],
    checkpoints: [
      { label: 'Plan', dept: 'preprod', context: 'You must decide the color mood for the whole episode.',
        step: s('What do you make first?', [['a', 'A color script with small frames for each scene'], ['b', 'Final 3D renders'], ['c', 'The poster'], ['d', 'The sound mix']], 'a', 'A [[color_script]] plans the color arc so the cherry scene can peak.') },
      { label: 'Budget', dept: 'anim_tech', context: 'Haru waits for 20 seconds before Sora comes.',
        step: s('How do you animate the wait cheaply?', [['a', 'Full animation on ones for every frame'], ['b', 'Hold Haru still, but drift petals and move his hair a little'], ['c', 'Cut to black']], 'b', 'Few drawings, but life stays: [[limited_animation]] with a [[moving_hold]].') },
      { label: 'Key moment', dept: 'anim_principle', context: 'Sora turns and the wind lifts her hair as she takes the letter.',
        step: s('Where do you spend your best animator?', [['a', 'On the walk to school'], ['b', 'On the credits'], ['c', 'On this turn: rich, fluid key drawings'], ['d', 'Spread evenly over every shot']], 'c', 'Save money elsewhere and spend it on one [[sakuga]] moment.') },
      { label: 'Drawings', dept: 'anim_tech', context: 'A lead animator draws the main poses of the turn.',
        step: s('What are these drawings called in Japanese studios?', [['a', 'Genga (key animation)'], ['b', 'Douga (inbetweens)'], ['c', 'Shiage (paint)']], 'a', 'The key drawings are the [[genga]]; others draw the inbetweens.') },
    ],
    outcome: 'The [[color_script]] builds to the peak, [[limited_animation]] saves money, and the budget goes into one [[sakuga]] turn.',
    ref: 'Your Lie in April (2014)',
  },
  {
    id: 'b1-hospital-hallway', title: 'News in the hospital hallway', genre: 'Drama',
    setup: 'A doctor tells Ana (30) that her father will not wake up. They stand in a long hallway. Ana must sign a form to stop the machines.',
    goal: 'The audience must feel the world drop away from Ana.',
    terms: ['dolly_zoom', 'dof', 'sound_design', 'close_up', 'reaction_shot'], tags: ['grief'],
    checkpoints: [
      { label: 'Focus', dept: 'camera', context: 'The doctor talks. Ana does not hear him any more.',
        step: s('What do you do with focus?', [['a', 'Deep focus on the whole hallway'], ['b', 'Use a wide aperture: Ana sharp, the doctor soft behind her'], ['c', 'Everything out of focus']], 'b', 'A shallow [[dof]] cuts Ana off from the world around her.') },
      { label: 'Move', dept: 'camera', context: 'The moment she understands.',
        step: s('Which camera move shows the world shift?', [['a', 'Dolly in while zooming out, so the hall stretches behind her'], ['b', 'A fast pan to the window'], ['c', 'A crane up to the ceiling'], ['d', 'Lock off and do nothing']], 'a', 'Background warps while she stays the same size: the [[dolly_zoom]].') },
      { label: 'Sound', dept: 'sound', context: 'The doctor keeps talking.',
        step: s('What does the audience hear?', [['a', 'Every word, clear and loud'], ['b', 'A happy pop song'], ['c', 'His voice fades to a muffled hum; her breath gets loud']], 'c', 'Subjective sound is a [[sound_design]] choice that puts us inside her head.') },
      { label: 'Edit', dept: 'editing', context: 'The doctor gives the news.',
        step: s('Whose face do you cut to?', [['a', 'The doctor, for the whole speech'], ['b', 'A nurse in the background'], ['c', 'Ana, as she hears it']], 'c', 'The scene lives in the listener: the [[reaction_shot]].') },
    ],
    outcome: 'Shallow [[dof]], the [[dolly_zoom]] and muffled [[sound_design]] all show one thing: Ana is alone inside the news.',
    ref: 'Manchester by the Sea (2016)',
  },
  {
    id: 'b1-dorm-move-in', title: 'Dorm move-in day', genre: 'Coming-of-age',
    setup: 'Leo (18) moves into a college dorm. His dad carries boxes, makes bad jokes and does not want to leave. Leo wants him gone, then misses him the moment the car drives off.',
    goal: 'Show the shift from embarrassment to loss in one scene.',
    terms: ['character_arc', 'blocking', 'frame_in_frame', 'score', 'want_need'], tags: ['family', 'college'],
    checkpoints: [
      { label: 'Story', dept: 'story', context: 'Leo says he wants freedom.',
        step: s('What does he really need here?', [['a', 'More boxes'], ['b', 'To know his dad is still there for him'], ['c', 'A new roommate'], ['d', 'A better room']], 'b', 'The gap between what he says and what he lacks is [[want_need]].') },
      { label: 'Blocking', dept: 'director', context: 'Dad stands in the doorway for the goodbye.',
        step: s('How do you block the goodbye?', [['a', 'Leo stays at his desk, back to Dad; Dad lingers, then leaves'], ['b', 'They hug in the middle for a minute'], ['c', 'Both face the camera and talk']], 'a', 'Where actors stand and move tells the story: [[blocking]].') },
      { label: 'Frame', dept: 'composition', context: 'From inside, we see Dad walk to the car.',
        step: s('How do you frame him?', [['a', 'Small, through the dorm window frame'], ['b', 'A tight close-up from the car'], ['c', 'A bird’s-eye from a drone']], 'a', 'A window around Dad is a [[frame_in_frame]]: he is now outside Leo’s world.') },
      { label: 'Music', dept: 'sound', context: 'The car drives off; Leo turns to the empty room.',
        step: s('When does the score come in?', [['a', 'Under the bad jokes at the start'], ['b', 'Never, not even later'], ['c', 'Only now, soft, as Leo sits on the bare bed']], 'c', 'Hold the [[score]] back so it lands on the turn of his [[character_arc]].') },
    ],
    outcome: 'The [[blocking]] keeps them apart, the [[frame_in_frame]] pushes Dad out, and the late [[score]] marks Leo’s change.',
    ref: 'Lady Bird (2017)',
  },
  {
    id: 'b1-anime-summer-bike', title: 'Last summer bike ride', genre: 'Anime slice of life',
    setup: 'In an anime film, two friends (14) ride bikes down a hill on the last day of summer. One of them moves away next week. The scene is mostly hand-drawn with a 3D background town.',
    goal: 'Freedom and joy, with a small shadow of the end.',
    terms: ['multiplane', 'parallax', 'on_twos', 'golden_hour', 'smear'], tags: ['anime', 'friendship'],
    checkpoints: [
      { label: 'Depth', dept: 'anim_tech', context: 'The camera tracks with the bikes past houses, poles and far hills.',
        step: s('How do you make the background feel deep?', [['a', 'One flat painting that slides as a block'], ['b', 'Separate layers that slide at different speeds'], ['c', 'Blur the whole frame']], 'b', 'Near layers move faster than far ones: [[parallax]] from a [[multiplane]] setup.') },
      { label: 'Timing', dept: 'anim_tech', context: 'The characters are hand-drawn at 24 fps.',
        step: s('What is the common rate for the riders?', [['a', 'One drawing every two frames, 12 per second'], ['b', '60 new drawings per second'], ['c', 'One drawing per second']], 'a', 'Animating [[on_twos]] is the standard for anime character motion.') },
      { label: 'Fast move', dept: 'anim_principle', context: 'One boy whips his arm up to wave, very fast.',
        step: s('How do you sell the fast wave in one frame?', [['a', 'Add more inbetweens'], ['b', 'Draw a stretched, blurred arm for one frame'], ['c', 'Freeze the frame']], 'b', 'A stretched in-between drawing is a [[smear]].') },
      { label: 'Light', dept: 'color', context: 'The ride is the last day of summer.',
        step: s('Which light and color?', [['a', 'Cold blue noon'], ['b', 'Grey overcast'], ['c', 'Low warm sun, long shadows, an orange sky'], ['d', 'Pure black night']], 'c', 'The warm low sun of [[golden_hour]] feels happy and ending at once.') },
    ],
    outcome: '[[parallax]] gives speed, [[on_twos]] and [[smear]] give the hand-drawn snap, and [[golden_hour]] adds the bittersweet end.',
    ref: 'The Girl Who Leapt Through Time (2006)',
  },
  {
    id: 'b1-video-call-breakup', title: 'Breakup on a video call', genre: 'Romance',
    setup: 'Jin (24) and Clara (24) live in two countries. On a late video call, Clara ends the relationship. Jin is in a dark kitchen; Clara is in a bright morning room.',
    goal: 'Show the distance between them, inside one call.',
    terms: ['color_contrast', 'color_temp', 'cross_cutting', 'practical', 'subtext'], tags: ['romance', 'distance'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'Jin’s kitchen is dark at night.',
        step: s('What lights Jin’s face?', [['a', 'The laptop screen, seen in frame'], ['b', 'A big soft box from nowhere'], ['c', 'A spotlight from above']], 'a', 'A light source in the shot is a [[practical]]; the screen glow is real and lonely.') },
      { label: 'Color', dept: 'color', context: 'Clara is in warm morning sun; Jin is at night.',
        step: s('How do you grade the two sides?', [['a', 'Same neutral grade for both'], ['b', 'Clara warm amber, Jin cool blue'], ['c', 'Both black and white'], ['d', 'Both bright green']], 'b', 'Warm against cool is [[color_contrast]]; it shows two worlds.') },
      { label: 'White balance', dept: 'camera', context: 'On Jin’s set, the screen is about 6500 K.',
        step: s('To keep the blue look in camera, set white balance to…', [['a', 'About 3200 K, so the screen reads blue'], ['b', 'About 6500 K, so the screen reads white'], ['c', 'Auto white balance']], 'a', 'A lower setting than the light makes it look cooler: [[color_temp]].') },
      { label: 'Edit', dept: 'editing', context: 'You have both sides of the call.',
        step: s('How do you cut between them?', [['a', 'Split screen for the whole scene'], ['b', 'Only Clara'], ['c', 'Cut between the two rooms as they talk']], 'c', 'Moving between two places is [[cross_cutting]]; each cut shows the gap.') },
    ],
    outcome: 'The screen [[practical]], the warm/cool [[color_contrast]] and the [[cross_cutting]] keep them apart even while they talk.',
    ref: 'Like Crazy (2011)',
  },
  {
    id: 'b1-exam-results', title: 'Exam results on the wall', genre: 'Coming-of-age',
    setup: 'Students crowd a school wall where exam results hang. Mina (18) finds she passed. Her best friend Dae did not. Mina must hide her joy.',
    goal: 'Two opposite feelings in one frame.',
    terms: ['rack_focus', 'two_shot', 'dramatic_irony', 'handheld', 'eyeline_match'], tags: ['school', 'friendship'],
    checkpoints: [
      { label: 'Camera', dept: 'camera', context: 'A noisy crowd pushes at the wall.',
        step: s('What support fits the crowd?', [['a', 'Handheld, close in the crowd'], ['b', 'A locked tripod far away'], ['c', 'A slow crane']], 'a', '[[handheld]] camera feels nervous and alive in a crowd.') },
      { label: 'Edit', dept: 'editing', context: 'Mina looks up at the list.',
        step: s('What is the next shot?', [['a', 'The sky'], ['b', 'A wide of the school'], ['c', 'The list at her eye angle, her name on it']], 'c', 'Look, then what she sees: an [[eyeline_match]].') },
      { label: 'Focus', dept: 'camera', context: 'Mina in the front smiles; Dae is behind her, face falling.',
        step: s('How do you move from joy to pain in one shot?', [['a', 'Cut to black'], ['b', 'Shift focus from Mina to Dae behind her'], ['c', 'Zoom out fast'], ['d', 'Keep both soft']], 'b', 'Moving focus between planes is a [[rack_focus]].') },
      { label: 'Story', dept: 'story', context: 'Dae has not yet seen that Mina passed.',
        step: s('Who should know first?', [['a', 'The audience, before Dae'], ['b', 'Nobody until the end'], ['c', 'Only Dae']], 'a', 'We know what Dae does not: [[dramatic_irony]] makes us dread his look.') },
    ],
    outcome: 'The [[rack_focus]] puts joy and pain in one shot, and [[dramatic_irony]] makes us wait for Dae to see it.',
    ref: 'Boyhood (2014)',
  },
  {
    id: 'b1-grandma-recipe', title: 'Grandma’s recipe', genre: 'Family drama',
    setup: 'After her grandmother dies, Lin (26) tries to cook the old family dumpling recipe. There is no written recipe. She remembers how her grandmother’s hands moved.',
    goal: 'Past and present must meet through the hands.',
    terms: ['match_cut', 'flashback', 'insert', 'foley', 'motif'], tags: ['grief', 'family'],
    checkpoints: [
      { label: 'Detail', dept: 'camera', context: 'Lin folds a dumpling.',
        step: s('Which shot shows the fold?', [['a', 'A wide of the whole kitchen'], ['b', 'A tight shot of her fingers on the dough'], ['c', 'An over-the-shoulder on the window']], 'b', 'A close detail cut into the scene is an [[insert]].') },
      { label: 'Edit', dept: 'editing', context: 'Her hands fold the dough the same way as Grandma’s did.',
        step: s('How do you go to the past?', [['a', 'Cut from Lin’s hands to Grandma’s hands in the same position'], ['b', 'A long fade to white'], ['c', 'A title card “20 years ago”'], ['d', 'A spinning wipe']], 'a', 'Same shape, new time: a [[match_cut]] into the [[flashback]].') },
      { label: 'Sound', dept: 'sound', context: 'The dough is quiet on the set mic.',
        step: s('How do you make the fold feel tactile?', [['a', 'Add music only'], ['b', 'Leave it silent'], ['c', 'Record soft dough and flour sounds in a studio']], 'c', 'Small studio-made sounds are [[foley]].') },
      { label: 'Story', dept: 'story', context: 'The pleat of the dumpling appears three times in the film.',
        step: s('What is this repeated pleat?', [['a', 'A motif that comes back with new meaning'], ['b', 'A plot hole'], ['c', 'A MacGuffin']], 'a', 'A repeated image that grows in meaning is a [[motif]].') },
    ],
    outcome: 'The [[insert]] of hands, the [[match_cut]] to the past and the [[foley]] of dough turn a recipe into a [[motif]] of love.',
    ref: 'The Farewell (2019)',
  },
  {
    id: 'b1-blender-bedroom-set', title: 'A teen bedroom in Blender', genre: '3D animated drama',
    setup: 'A small team makes a 3D short about a girl who packs her childhood room. You build the bedroom in Blender. The room must feel lived in and the shot must render overnight.',
    goal: 'A warm, believable room that renders on time.',
    terms: ['kitbash', 'hdri', 'eevee', 'principled_bsdf', 'samples_noise', 'blockout'], tags: ['3D', 'Blender'],
    checkpoints: [
      { label: 'Start', dept: 'modeling', context: 'The director wants to check camera angles tomorrow.',
        step: s('What do you build first?', [['a', 'Fully detailed furniture'], ['b', 'Simple boxes for bed, desk and shelves'], ['c', 'Final textures'], ['d', 'The hair of the character']], 'b', 'Rough shapes first to test the shot: a [[blockout]].') },
      { label: 'Props', dept: 'modeling', context: 'The shelves need 60 small toys and books.',
        step: s('How do you fill them fast?', [['a', 'Model each from scratch'], ['b', 'Leave them empty'], ['c', 'Reuse and combine parts from an asset library']], 'c', 'Building from ready parts is [[kitbash]].') },
      { label: 'Material', dept: 'blender', context: 'The wooden desk looks like plastic.',
        step: s('Which shader setting helps most?', [['a', 'Raise Roughness on the Principled BSDF and add a wood texture'], ['b', 'Set Metallic to 1'], ['c', 'Set Emission strength to 50']], 'a', 'Wood is rough and not metal: tune the [[principled_bsdf]].') },
      { label: 'Light', dept: 'lighting', context: 'Late afternoon sun should fill the window.',
        step: s('What gives quick, real outdoor light?', [['a', 'An HDRI sky in the World plus a sun lamp'], ['b', 'Ten point lights'], ['c', 'Only ambient occlusion']], 'a', 'A 360° image lights the scene: an [[hdri]].') },
      { label: 'Render', dept: 'blender', context: 'Cycles at 4096 samples takes 20 minutes a frame.',
        step: s('How do you finish overnight?', [['a', 'Raise samples to 16000'], ['b', 'Lower samples and turn on the denoiser, or use EEVEE'], ['c', 'Render at 8K']], 'b', 'Fewer [[samples_noise]] plus denoise, or real-time [[eevee]], saves hours.') },
    ],
    outcome: 'A [[blockout]] locks the shot, [[kitbash]] fills the room, and an [[hdri]] with a tuned [[principled_bsdf]] makes it warm and real.',
    ref: 'Spring (2019, Blender Studio)',
  },
  {
    id: 'b1-wedding-speech', title: 'The brother’s wedding speech', genre: 'Family comedy-drama',
    setup: 'At his sister’s wedding, Omar (28) gives a speech. He jokes at first, then talks about their late mother. The room goes quiet.',
    goal: 'Move the room, and the audience, from laughter to tears.',
    terms: ['tone', 'cutaway', 'pacing', 'diegetic', 'medium_shot'], tags: ['family', 'grief'],
    checkpoints: [
      { label: 'Tone', dept: 'story', context: 'The speech must change mood in the middle.',
        step: s('How do you write the turn?', [['a', 'A joke that leads into a true memory of Mom'], ['b', 'Stop the speech and start a new scene'], ['c', 'No jokes at all']], 'a', 'A clear turn inside one speech is a shift in [[tone]].') },
      { label: 'Shot', dept: 'camera', context: 'Omar stands with a microphone.',
        step: s('Main shot for the speech?', [['a', 'An extreme long shot from the parking lot'], ['b', 'A waist-up medium shot'], ['c', 'An extreme close-up of his eye']], 'b', 'A [[medium_shot]] shows face and hands, good for a speech.') },
      { label: 'Edit', dept: 'editing', context: 'Guests laugh, then go quiet.',
        step: s('What do you cut to?', [['a', 'Short shots of guests: the bride, an old aunt, the father'], ['b', 'Nothing, only Omar for five minutes'], ['c', 'Stock footage of fireworks']], 'a', 'Short shots of the room are [[cutaway]]s that show the speech land.') },
      { label: 'Rhythm', dept: 'editing', context: 'The jokes come fast; the memory is slow.',
        step: s('How do you shape the rhythm?', [['a', 'Same cut speed all through'], ['b', 'Faster cuts during the jokes, longer holds in the memory'], ['c', 'Random cut lengths']], 'b', 'Changing cut length with the mood is [[pacing]].') },
      { label: 'Sound', dept: 'sound', context: 'A band waits on stage.',
        step: s('Where should the music come from at the end?', [['a', 'The band starts the mother’s favorite song in the room'], ['b', 'An orchestra no one can see'], ['c', 'A laugh track']], 'a', 'Music from the world of the film is [[diegetic]]; the band makes it part of the moment.') },
    ],
    outcome: 'The [[tone]] turns inside the speech, [[cutaway]]s and [[pacing]] carry the room with it, and [[diegetic]] music closes the memory.',
    ref: 'Little Miss Sunshine (2006)',
  },
  {
    id: 'b1-anime-train-window', title: 'The train window', genre: 'Anime drama',
    setup: 'In an anime film, Aoi (19) leaves her country town for a city job. On the train, she sees her reflection over the passing rice fields. Nobody speaks for a long time.',
    goal: 'A quiet pause that lets the audience breathe and feel the change.',
    terms: ['ma', 'pillow_shot', 'kishotenketsu', 'ambience', 'japanese_masters'], tags: ['anime', 'leaving home'],
    checkpoints: [
      { label: 'Structure', dept: 'story', context: 'The film has no villain and little conflict.',
        step: s('Which four-part structure fits?', [['a', 'Hero’s journey'], ['b', 'Kishōtenketsu: intro, development, twist, result'], ['c', 'Save the Cat beat sheet'], ['d', 'Five-act tragedy']], 'b', '[[kishotenketsu]] builds through a twist, not through conflict.') },
      { label: 'Pause', dept: 'director', context: 'The producer wants to cut the 15-second silence.',
        step: s('What do you defend?', [['a', 'Cut it to 2 seconds'], ['b', 'Add dialogue'], ['c', 'Keep the empty pause; it gives the scene room to breathe']], 'c', 'A meaningful pause is [[ma]].') },
      { label: 'Cutaway', dept: 'editing', context: 'Between scenes you need a short break.',
        step: s('What shot do you use?', [['a', 'A still shot of a train sign and a power line, no people'], ['b', 'A fast montage'], ['c', 'A recap of the plot']], 'a', 'An empty transition still life is a [[pillow_shot]], from Ozu and the [[japanese_masters]].') },
      { label: 'Sound', dept: 'sound', context: 'The train is quiet inside.',
        step: s('What sound bed?', [['a', 'Rails clicking, wind, a far crossing bell'], ['b', 'Loud rock music'], ['c', 'Pure silence, no room tone']], 'a', 'The steady world sound is [[ambience]]; it fills the [[ma]].') },
    ],
    outcome: '[[kishotenketsu]] lets the film move without fights, and [[ma]], a [[pillow_shot]] and soft [[ambience]] let Aoi’s change sink in.',
    ref: 'Tokyo Story (1953)',
  },
  {
    id: 'b1-locker-room-friendship', title: 'After the lost match', genre: 'Sports drama',
    setup: 'A school basketball team loses the final. In the locker room, team captain Sam (17) blames his best friend for the missed shot. Both say things they cannot take back.',
    goal: 'A fight that hurts both sides equally.',
    terms: ['shot_reverse_shot', '180_rule', 'low_key', 'conflict', 'eyeline_match', 'hard_soft'], tags: ['friendship', 'sports'],
    checkpoints: [
      { label: 'Story', dept: 'story', context: 'In the draft, only Sam is angry; his friend just takes it.',
        step: s('How do you fix the scene?', [['a', 'Give the friend his own anger and a true point'], ['b', 'Make Sam the clear villain'], ['c', 'Cut the fight']], 'a', 'Two strong sides make real [[conflict]].') },
      { label: 'Coverage', dept: 'camera', context: 'They face each other across a bench.',
        step: s('How do you cover the argument?', [['a', 'Singles of each, cut back and forth, camera on one side of them'], ['b', 'One wide shot only'], ['c', 'Cross the line for every shot']], 'a', 'Back-and-forth singles are [[shot_reverse_shot]]; keep the [[180_rule]].') },
      { label: 'Light', dept: 'lighting', context: 'One flickering tube light is on.',
        step: s('Which light quality?', [['a', 'Hard overhead light, deep eye shadows'], ['b', 'Soft, flat beauty light'], ['c', 'Pink fairy lights']], 'a', 'Hard light gives sharp shadows: [[hard_soft]], in a [[low_key]] room.') },
      { label: 'Eyelines', dept: 'editing', context: 'In one single, Sam looks left; in the other, his friend also looks left.',
        step: s('What is wrong?', [['a', 'Nothing'], ['b', 'They seem to look the same way, not at each other'], ['c', 'The color is off']], 'b', 'Their looks must meet across the cut: [[eyeline_match]].') },
    ],
    outcome: 'Real [[conflict]] on both sides, clean [[shot_reverse_shot]] and hard [[low_key]] light make the fight hurt.',
    ref: 'Friday Night Lights (2004)',
  },
  {
    id: 'b1-stop-motion-letters', title: 'Letters from Grandpa', genre: 'Stop-motion family',
    setup: 'A stop-motion short: a puppet boy reads old letters from his grandfather, a sailor. Paper boats from the letters come alive on his desk.',
    goal: 'Make paper feel alive and handmade.',
    terms: ['stop_motion', 'timing', 'squash_stretch', 'anticipation', 'arcs'], tags: ['stop motion', 'family'],
    checkpoints: [
      { label: 'Method', dept: 'anim_tech', context: 'Real paper boats on a real desk.',
        step: s('How do you animate them?', [['a', 'Move them a little, shoot one frame, repeat'], ['b', 'Film them with a fan blowing'], ['c', 'Motion capture']], 'a', 'Frame-by-frame physical posing is [[stop_motion]].') },
      { label: 'Speed', dept: 'anim_principle', context: 'A boat must cross the desk in 2 seconds at 24 fps.',
        step: s('How many frames does the move take?', [['a', '12'], ['b', '24'], ['c', '48'], ['d', '200']], 'c', '2 s × 24 fps = 48 frames: that is [[timing]].') },
      { label: 'Jump', dept: 'anim_principle', context: 'A boat hops off a book.',
        step: s('What comes before the hop?', [['a', 'Nothing; it just lifts'], ['b', 'A small dip back, as if it gathers force'], ['c', 'A camera shake']], 'b', 'A small move before the main move is [[anticipation]].') },
      { label: 'Path', dept: 'anim_principle', context: 'The boat flies from the book to a cup.',
        step: s('What path should it follow?', [['a', 'A straight line'], ['b', 'A zig-zag'], ['c', 'A curved arc']], 'c', 'Natural motion follows [[arcs]].') },
    ],
    outcome: 'Careful [[timing]], [[anticipation]] and [[arcs]] make a paper boat feel alive in [[stop_motion]].',
    ref: 'Kubo and the Two Strings (2016)',
  },
  {
    id: 'b1-night-shift-diner', title: 'Night shift at the diner', genre: 'Slice of life',
    setup: 'At 3 a.m., a tired waitress (45) and a young nurse (23) are the only two people in a roadside diner. They talk about quitting. By dawn, both decide to stay.',
    goal: 'A warm, lonely night that slowly turns to hope.',
    terms: ['practical', 'teal_orange', 'color_grading', 'two_shot', 'motivated_light'], tags: ['night', 'work'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'The diner has neon signs and hanging lamps.',
        step: s('How do you light the booth?', [['a', 'Use the hanging lamp as the key, boost it a little'], ['b', 'A big flat soft box from the front'], ['c', 'Turn all lights off']], 'a', 'Lamps in frame are [[practical]]s; build the look from them as [[motivated_light]].') },
      { label: 'Shot', dept: 'camera', context: 'They sit across a booth.',
        step: s('Which shot shows their bond?', [['a', 'Two singles only'], ['b', 'A two-shot across the table'], ['c', 'A drone shot of the roof']], 'b', 'Both in one frame shows they share the night: a [[two_shot]].') },
      { label: 'Grade', dept: 'color', context: 'Outside is blue night; inside is warm lamplight.',
        step: s('Which grade?', [['a', 'Teal night outside, orange skin inside'], ['b', 'All green'], ['c', 'Full black and white'], ['d', 'Bright pink']], 'a', 'Warm skin against cool shadow is [[teal_orange]].') },
      { label: 'Arc', dept: 'color', context: 'The night ends at dawn.',
        step: s('How does the grade change across the scene?', [['a', 'Stay the same'], ['b', 'Go darker'], ['c', 'Slowly warm and lift as dawn comes through the window']], 'c', 'A grade that changes with the story is [[color_grading]] as storytelling.') },
    ],
    outcome: '[[practical]] lamps, a [[two_shot]] and a [[teal_orange]] grade that warms with dawn turn a sad night into hope.',
    ref: 'Paterson (2016)',
  },
  {
    id: 'b1-anime-rival-piano', title: 'Rival at the piano', genre: 'Anime drama',
    setup: 'In an anime series, two music students (17) play the same piece in a contest. One is a perfect technician; the other plays with feeling. The judges, and the audience, must feel the difference.',
    goal: 'Make music visible.',
    terms: ['leitmotif', 'rotoscope', 'reference_video', 'line_of_action', 'acting_anim'], tags: ['anime', 'music'],
    checkpoints: [
      { label: 'Hands', dept: 'anim_tech', context: 'The hands must hit the right keys.',
        step: s('How do animators get real finger moves?', [['a', 'Guess from memory'], ['b', 'Film a real pianist and use the video as reference'], ['c', 'Copy a different anime']], 'b', 'Filming real action to study is [[reference_video]]; tracing it is [[rotoscope]].') },
      { label: 'Pose', dept: 'anim_principle', context: 'The feeling player leans in on a loud chord.',
        step: s('How do you draw the strong pose?', [['a', 'Stiff and straight'], ['b', 'One clear curve through the spine, from head to hands'], ['c', 'Hide the body']], 'b', 'One strong curve through the body is the [[line_of_action]].') },
      { label: 'Acting', dept: 'anim_principle', context: 'Both play the same notes.',
        step: s('How do you show the difference?', [['a', 'The same moves for both'], ['b', 'Change only the hair color'], ['c', 'The technician is still and precise; the other sways and breathes with the phrase']], 'c', 'Different body choices show inner life: [[acting_anim]].') },
      { label: 'Music', dept: 'sound', context: 'A short theme belongs to the feeling player’s lost mother.',
        step: s('How do you use it?', [['a', 'Bring the theme back when she plays it her own way'], ['b', 'Use it once only, in episode 1'], ['c', 'Replace it with a new song each time']], 'a', 'A theme tied to a person or idea is a [[leitmotif]].') },
    ],
    outcome: '[[reference_video]] keeps the hands true, [[acting_anim]] and a strong [[line_of_action]] show feeling, and the [[leitmotif]] ties it to her mother.',
    ref: 'Your Lie in April (2014)',
  },
  {
    id: 'b1-graduation-photo', title: 'The graduation photo', genre: 'Coming-of-age',
    setup: 'Five friends take one last photo after their graduation. Each plans to go a different way. One friend, Priya, is not in the photo; she left the group months ago, and now she watches from across the yard.',
    goal: 'Show who belongs and who is left out, in one image.',
    terms: ['rule_of_thirds', 'visual_weight', 'staging', 'lens_compression'], tags: ['school', 'friendship'],
    checkpoints: [
      { label: 'Staging', dept: 'director', context: 'The five friends pose; Priya stands far behind.',
        step: s('Where do you place Priya?', [['a', 'In the group'], ['b', 'Off screen'], ['c', 'Small, alone, in the gap between two friends, deep in the frame']], 'c', 'Placing actors in depth to tell the story is [[staging]].') },
      { label: 'Lens', dept: 'camera', context: 'Priya is 40 m behind the group.',
        step: s('How do you make her feel close but apart?', [['a', 'A long lens from far away, so the distance flattens'], ['b', 'A fisheye up close'], ['c', 'A 14 mm wide lens']], 'a', 'A long lens flattens depth: [[lens_compression]].') },
      { label: 'Frame', dept: 'composition', context: 'The group is bright and big; Priya is small.',
        step: s('How do you still make the eye find Priya?', [['a', 'Put her on a third line, in the only clean patch of background'], ['b', 'Center the group and hide her'], ['c', 'Make her blurred and dark']], 'a', 'A clear spot on a [[rule_of_thirds]] line gives her [[visual_weight]].') },
    ],
    outcome: '[[staging]] in depth, [[lens_compression]] and the [[rule_of_thirds]] tell the story of the one who left.',
    ref: 'The Perks of Being a Wallflower (2012)',
  },
  {
    id: 'b1-blender-anime-sunset', title: 'Anime-style sunset in Blender', genre: '3D anime romance',
    setup: 'A student team makes a short in Blender that must look like hand-drawn anime. Two characters sit on a sea wall at sunset. One shows the other a song on her phone.',
    goal: 'A 3D scene that reads as 2D anime.',
    terms: ['npr', 'shader_to_rgb', 'freestyle_lineart', 'grease_pencil', 'on_twos'], tags: ['Blender', 'anime'],
    checkpoints: [
      { label: 'Style', dept: 'modern', context: 'Realistic shading looks wrong.',
        step: s('Which approach fits?', [['a', 'Non-photorealistic, toon-style rendering'], ['b', 'Max realism with Cycles path tracing'], ['c', 'Mocap with no edits']], 'a', 'Art-style rendering is [[npr]].') },
      { label: 'Shading', dept: 'blender', context: 'You need flat light and shadow bands on the faces.',
        step: s('How in EEVEE?', [['a', 'Shader to RGB, then a Color Ramp set to Constant'], ['b', 'Raise Subsurface'], ['c', 'Use an HDRI only'], ['d', 'Add motion blur']], 'a', 'In EEVEE, [[shader_to_rgb]] plus a stepped ramp makes toon bands.') },
      { label: 'Lines', dept: 'blender', context: 'The characters need ink outlines.',
        step: s('Which tool draws lines from the 3D models?', [['a', 'The compositor blur node'], ['b', 'Freestyle or Line Art'], ['c', 'Shape keys']], 'b', 'Lines made from 3D edges come from [[freestyle_lineart]].') },
      { label: 'Motion', dept: 'anim_tech', context: 'Smooth 3D motion feels too fluid for anime.',
        step: s('How do you get the 2D feel?', [['a', 'Add more motion blur'], ['b', 'Raise to 60 fps'], ['c', 'Hold each pose for two frames, with stepped keys']], 'c', 'Stepped poses held two frames copy anime [[on_twos]].') },
    ],
    outcome: '[[npr]] shading with [[shader_to_rgb]], [[freestyle_lineart]] ink and motion [[on_twos]] make 3D look drawn.',
    ref: 'Spider-Man: Into the Spider-Verse (2018)',
  },
]
