import type { Scene, Step } from '../../shared/types'
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({ prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why })
export const SCENES_B2: Scene[] = [
  {
    id: 'b2-detective-rain-office', title: 'The client in the rain', genre: 'Noir',
    setup: 'A tired private detective sits in his office at night. A woman in a wet coat asks him to find her missing brother. She lies about one thing, and the detective must not see it yet.',
    goal: 'The audience must distrust her before the detective does.',
    terms: ['film_noir', 'chiaroscuro', 'hard_soft', 'dramatic_irony', 'dutch_angle'], tags: ['noir', 'dialogue'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'A neon sign blinks outside the window blinds.',
        step: s('How do you light the office?', [['a', 'Soft even light from the ceiling'], ['b', 'One hard light through the blinds, deep black shadows'], ['c', 'Bright light from the front on both faces']], 'b', 'Hard light and strong shadow give the [[chiaroscuro]] look of [[film_noir]].') },
      { label: 'Her face', dept: 'lighting', context: 'She tells the lie about her brother.',
        step: s('What does the light do on her face?', [['a', 'A stripe of shadow from the blinds falls across her eyes'], ['b', 'Her face gets brighter and softer'], ['c', 'Nothing changes']], 'a', 'Hard shadow that hides the eyes is [[hard_soft]] light used to show a secret.') },
      { label: 'Information', dept: 'story', context: 'You can show the audience a small clue during her story.',
        step: s('Which clue do you show?', [['a', 'None; reveal everything at the end'], ['b', 'A narrator says she lies'], ['c', 'An insert: her brother’s photo in her purse is fresh, but she says he left a year ago']], 'c', 'We know more than the detective: [[dramatic_irony]].') },
      { label: 'Angle', dept: 'camera', context: 'The detective agrees to take the case.',
        step: s('How do you frame his handshake?', [['a', 'A slight tilt of the frame, a wrong-feeling world'], ['b', 'A level wide shot with a happy tune'], ['c', 'A drone shot of the city']], 'a', 'A tilted frame is a [[dutch_angle]]: something is wrong.') },
    ],
    outcome: 'Hard light hides her eyes and one insert tells us the truth, so we watch the detective walk into a trap. That is [[film_noir]] built on [[dramatic_irony]].',
    ref: 'The Maltese Falcon (1941)',
  },
  {
    id: 'b2-vault-timer', title: 'Ninety seconds in the vault', genre: 'Heist',
    setup: 'Four thieves are inside a bank vault. The guard comes back in ninety seconds. The safecracker’s hands shake on the last lock.',
    goal: 'The audience must count the seconds with the crew.',
    terms: ['cross_cutting', 'pacing', 'insert', 'sound_design', 'tension'], tags: ['suspense', 'heist'],
    checkpoints: [
      { label: 'Structure', dept: 'editing', context: 'You have footage of the vault and of the guard in the hall.',
        step: s('How do you cut the two places?', [['a', 'Show the vault, then the guard, each one complete'], ['b', 'Cut between the vault and the walking guard, faster and faster'], ['c', 'Only show the vault']], 'b', 'Two lines of action that close in on each other: [[cross_cutting]].') },
      { label: 'Detail', dept: 'camera', context: 'The safecracker turns the dial.',
        step: s('Which shot shows the work best?', [['a', 'A wide shot of the room'], ['b', 'A shot of the ceiling'], ['c', 'A tight insert on fingers and dial numbers']], 'c', 'An [[insert]] shows the one detail that matters.') },
      { label: 'Sound', dept: 'sound', context: 'The temp track has loud action music.',
        step: s('What do you hear?', [['a', 'The dial clicks and the guard’s steps, louder each time; no music'], ['b', 'Keep the loud music'], ['c', 'Total silence for the whole scene']], 'a', 'Small real sounds pulled up build [[sound_design]] tension.') },
      { label: 'Rhythm', dept: 'editing', context: 'The last ten seconds.',
        step: s('How long are the shots now?', [['a', 'Longer and slower'], ['b', 'The same as before'], ['c', 'Shorter each cut, then one held shot as the lock opens']], 'c', 'Shot length controls [[pacing]]; a sudden hold releases it.') },
    ],
    outcome: 'Cross-cutting sets the clock, inserts show the task, and real sounds count the steps. The held last shot lets the [[tension]] break.',
    ref: 'Rififi (1955), the silent break-in',
  },
  {
    id: 'b2-trench-letter', title: 'The letter before dawn', genre: 'War',
    setup: 'A young soldier writes a letter home in a trench. At dawn his unit must attack. His older sergeant watches him and says nothing.',
    goal: 'Quiet fear before a battle we never see.',
    terms: ['silence', 'close_up', 'motivated_light', 'ambience', 'subtext'], tags: ['war', 'emotion'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'It is night in the trench.',
        step: s('What lights his face?', [['a', 'A bright film light from above'], ['b', 'A small candle stub beside the paper'], ['c', 'A green spotlight']], 'b', 'A candle in frame is a source that explains the light: [[motivated_light]].') },
      { label: 'Words', dept: 'story', context: 'The letter is read in voice-over.',
        step: s('What does the letter say?', [['a', 'He writes about his mother’s bread and asks about the dog'], ['b', 'He writes “I am afraid I will die tomorrow”'], ['c', 'He explains the battle plan']], 'a', 'Small homely words hide the fear: [[subtext]].') },
      { label: 'Sound', dept: 'sound', context: 'Far guns sound now and then.',
        step: s('How do you build the sound bed?', [['a', 'Loud music over all'], ['b', 'No sound at all'], ['c', 'Far thunder of guns, wind, pen scratch on paper']], 'c', 'A low bed of place sound is [[ambience]].') },
      { label: 'Last shot', dept: 'camera', context: 'The whistle for the attack blows.',
        step: s('What is the last image?', [['a', 'A close-up of the sergeant’s face as he folds the letter into his own pocket'], ['b', 'A wide battle shot with explosions'], ['c', 'The title card']], 'a', 'A [[close_up]] of the watcher carries the meaning.') },
    ],
    outcome: 'Candle light, small words and far guns keep the fear quiet. We never see the battle; the [[close_up]] of the sergeant tells us how it ends.',
    ref: '1917 (2019)',
  },
  {
    id: 'b2-attic-shape', title: 'The shape in the attic', genre: 'Horror',
    setup: 'A boy moves into an old house with his father. At night he looks up the attic ladder. Something might be up there.',
    goal: 'Fear from what we cannot see.',
    terms: ['negative_space', 'low_key', 'long_take', 'silence', 'pov_shot'], tags: ['horror', 'suspense'],
    checkpoints: [
      { label: 'Frame', dept: 'composition', context: 'The boy stands at the bottom of the ladder.',
        step: s('Where is the dark hatch in the frame?', [['a', 'Off screen'], ['b', 'A big black square above him with a lot of empty space'], ['c', 'Small in a corner, lit bright']], 'b', 'Large dark [[negative_space]] makes us search it.') },
      { label: 'Camera', dept: 'camera', context: 'He climbs up.',
        step: s('How do you shoot the climb?', [['a', 'Many fast cuts'], ['b', 'A drone shot'], ['c', 'His point of view, the hatch getting closer, torch shaking'], ['d', 'A shot from the attic floor looking down at him']], 'c', 'We see only what he sees: [[pov_shot]].') },
      { label: 'Duration', dept: 'director', context: 'He looks around the attic with the torch.',
        step: s('How do you hold the search?', [['a', 'One slow unbroken take with no cut'], ['b', 'Ten short shots'], ['c', 'Skip to the next morning']], 'a', 'With no cut we cannot relax: [[long_take]].') },
      { label: 'Sound', dept: 'sound', context: 'The torch finds an old chair. Nothing is there.',
        step: s('What does the sound do?', [['a', 'A loud music sting'], ['b', 'All sound drops, even the house creaks'], ['c', 'A cheerful song']], 'b', 'Sudden [[silence]] tells us to listen for something.') },
    ],
    outcome: 'Dark empty space, his point of view and an unbroken take make us hunt the frame. The sudden [[silence]] keeps the threat alive after nothing appears.',
    ref: 'The Haunting (1963)',
  },
  {
    id: 'b2-interrogation-room', title: 'Two chairs and a table', genre: 'Crime',
    setup: 'A detective questions a calm suspect in a small grey room. She has no proof. She must make him slip in ten minutes.',
    goal: 'The power moves from him to her.',
    terms: ['shot_reverse_shot', 'camera_angle', 'shot_size', 'pacing', 'blocking'], tags: ['dialogue', 'crime'],
    checkpoints: [
      { label: 'Coverage', dept: 'camera', context: 'They sit face to face.',
        step: s('What is the basic coverage?', [['a', 'One wide shot only'], ['b', 'Handheld from one side'], ['c', 'Matching singles of each, cut back and forth']], 'c', 'Talk between two faces is [[shot_reverse_shot]].') },
      { label: 'Power', dept: 'camera', context: 'At the start he is in control.',
        step: s('How do you shoot him early on?', [['a', 'A slightly low angle, so he seems bigger'], ['b', 'A high angle looking down'], ['c', 'Out of focus']], 'a', 'Low looks up, so it gives power: [[camera_angle]].') },
      { label: 'Change', dept: 'composition', context: 'She shows him a photo. He stops smiling.',
        step: s('How does the framing change?', [['a', 'Both go wider'], ['b', 'His shots get tighter and tighter; hers stay the same'], ['c', 'No change']], 'b', 'Growing closer means more pressure: [[shot_size]].') },
      { label: 'Movement', dept: 'director', context: 'She wants to press harder.',
        step: s('What does she do in the room?', [['a', 'She stands, walks behind him, and speaks from over his shoulder'], ['b', 'She sits still'], ['c', 'She leaves the room']], 'a', 'Where actors move tells the power story: [[blocking]].') },
    ],
    outcome: 'Matched singles start equal, then his frame closes in and she moves behind him. [[shot_size]] and [[blocking]] show the power change without a word about it.',
    ref: 'Memories of Murder (2003)',
  },
  {
    id: 'b2-snowbound-cabin', title: 'Last log on the fire', genre: 'Survival',
    setup: 'Two climbers are trapped in a mountain hut by a storm. One has a broken leg. The other must decide when to go down for help.',
    goal: 'Cold, time and a hard choice.',
    terms: ['color_temp', 'color_meaning', 'ambience', 'cutaway', 'stakes'], tags: ['survival'],
    checkpoints: [
      { label: 'Stakes', dept: 'story', context: 'The audience must feel the clock.',
        step: s('How do you show time running out?', [['a', 'A title says “Day 3”'], ['b', 'A character counts days aloud'], ['c', 'We see the wood pile shrink each scene, down to one log']], 'c', 'A visible thing that runs out shows the [[stakes]].') },
      { label: 'Light', dept: 'lighting', context: 'The fire is the only warm source.',
        step: s('How do you balance light colors?', [['a', 'Warm orange near the fire, cold blue from the window'], ['b', 'All neutral white'], ['c', 'All warm']], 'a', 'Warm and cool sources show [[color_temp]].') },
      { label: 'Grade', dept: 'color', context: 'The fire dies over the film.',
        step: s('How does the grade change?', [['a', 'More warm each day'], ['b', 'It stays the same'], ['c', 'It goes slowly bluer and less saturated'], ['d', 'It turns bright green']], 'c', 'Cold blue means danger and loss here: [[color_meaning]].') },
      { label: 'Sound', dept: 'sound', context: 'The friend sleeps. The other one listens.',
        step: s('What do we hear?', [['a', 'Wind against the walls, the fire ticking'], ['b', 'Upbeat music'], ['c', 'Nothing']], 'a', 'Place sound builds the world: [[ambience]].') },
    ],
    outcome: 'The wood pile is the clock and the color drains with the fire. Warm against cold [[color_temp]] shows how small their safe place is.',
    ref: 'Touching the Void (2003)',
  },
  {
    id: 'b2-blood-on-the-glass', title: 'The fingerprint', genre: 'Mystery',
    setup: 'A young inspector studies a closed room where a rich man died. The answer is in the room. The audience gets the same clues she does.',
    goal: 'A fair mystery: the clue is shown but not pointed at.',
    terms: ['setup_payoff', 'deep_focus', 'rack_focus', 'flashback', 'foreshadowing'], tags: ['mystery'],
    checkpoints: [
      { label: 'Plant', dept: 'story', context: 'The key clue is a wine glass in the wrong hand position.',
        step: s('How do you show it first?', [['a', 'Hide it until the end'], ['b', 'In the back of a normal shot, in focus but not stressed'], ['c', 'A big close-up with a music sting']], 'b', 'Show it early, use it late: [[setup_payoff]].') },
      { label: 'Lens', dept: 'camera', context: 'You want the whole room sharp in the wide shot.',
        step: s('Which choice?', [['a', 'A small aperture so near and far are sharp'], ['b', 'A wide open aperture'], ['c', 'Heavy fog filter']], 'a', 'Everything sharp is [[deep_focus]], so the clue can sit in plain sight.') },
      { label: 'Discovery', dept: 'camera', context: 'She notices the glass.',
        step: s('How does the camera show her noticing?', [['a', 'Cut to black'], ['b', 'Zoom out'], ['c', 'Focus moves from her face to the glass behind her']], 'c', 'Moving focus guides the eye: [[rack_focus]].') },
      { label: 'Reveal', dept: 'editing', context: 'She explains what really happened.',
        step: s('How do you show the past?', [['a', 'Only her words'], ['b', 'Short shots of the night of the death, in a different grade'], ['c', 'Text on screen']], 'b', 'Showing earlier events is a [[flashback]].') },
    ],
    outcome: 'The glass is in the frame from the first wide shot, sharp but quiet. The [[rack_focus]] and the [[flashback]] pay it off fairly.',
    ref: 'Knives Out (2019)',
  },
  {
    id: 'b2-parking-garage', title: 'Footsteps on level three', genre: 'Thriller',
    setup: 'A nurse walks to her car in an empty parking garage after a late shift. She thinks someone follows her. Maybe nobody is there.',
    goal: 'Doubt: real danger or her fear?',
    terms: ['foley', 'diegetic', 'wide_shot', 'practical', 'jump_cut'], tags: ['suspense'],
    checkpoints: [
      { label: 'Sound', dept: 'sound', context: 'Her heels click. Then a second set of steps.',
        step: s('How do you record the steps?', [['a', 'Library sound only'], ['b', 'Live on set only'], ['c', 'Recorded later in a studio, so you control each step']], 'c', 'Steps made in a sound studio are [[foley]].') },
      { label: 'Source', dept: 'sound', context: 'Music could start here.',
        step: s('Which music works best?', [['a', 'Only a radio from a parked car, fading as she passes'], ['b', 'A loud score'], ['c', 'Pop song']], 'a', 'Music from inside the world is [[diegetic]]; it keeps it real.') },
      { label: 'Light', dept: 'lighting', context: 'The garage has rows of ceiling tubes.',
        step: s('How do you light it?', [['a', 'Add big film lights'], ['b', 'Use the real tubes, with some broken to leave dark gaps'], ['c', 'Light only her face']], 'b', 'Lamps seen in frame are [[practical]] lights.') },
      { label: 'Frame', dept: 'composition', context: 'She turns to look behind her.',
        step: s('What do we see?', [['a', 'A wide empty row of cars, every gap a hiding place'], ['b', 'A close-up of her eye'], ['c', 'A man in full light']], 'a', 'A [[wide_shot]] full of dark gaps keeps the doubt.') },
    ],
    outcome: 'Controlled [[foley]] steps and real broken lights make a world that could hide anyone. The empty [[wide_shot]] never answers the question.',
    ref: 'Blow Out (1981)',
  },
  {
    id: 'b2-bomb-under-table', title: 'Under the table', genre: 'Thriller',
    setup: 'Two old friends meet in a cafe to make peace. A bomb with a timer is under their table. Only the audience knows.',
    goal: 'Long suspense from a small talk scene.',
    terms: ['dramatic_irony', 'insert', 'cross_cutting', 'score', 'pacing'], tags: ['suspense'],
    checkpoints: [
      { label: 'Plan', dept: 'story', context: 'When does the audience learn about the bomb?',
        step: s('Choose the moment.', [['a', 'At the explosion'], ['b', 'Never'], ['c', 'Before the friends sit down']], 'c', 'We know, they do not: [[dramatic_irony]] makes small talk tense.') },
      { label: 'Reminder', dept: 'editing', context: 'The talk goes on for three minutes.',
        step: s('How do you keep the threat alive?', [['a', 'Cut to the timer now and then'], ['b', 'Never show it again'], ['c', 'Show it every second']], 'a', 'A short [[insert]] of the timer reminds us without killing the scene.') },
      { label: 'Music', dept: 'sound', context: 'The composer asks for direction.',
        step: s('What should the music do?', [['a', 'A big theme at the start'], ['b', 'A low pulse that slowly rises in pitch'], ['c', 'Happy jazz']], 'b', 'A rising low pulse in the [[score]] tightens the scene.') },
      { label: 'End', dept: 'director', context: 'A waiter finds the bag with one second left.',
        step: s('How do you end it?', [['a', 'Cut away and never show it'], ['b', 'Hold longer on a frozen moment, then release'], ['c', 'Hurry past it']], 'b', 'Stretching time at the peak is [[pacing]].') },
    ],
    outcome: 'Because we see the bomb first, every laugh at the table hurts. Timer inserts and a rising [[score]] hold the [[dramatic_irony]] for minutes.',
    ref: 'Sabotage (1936)',
  },
  {
    id: 'b2-sniper-bell-tower', title: 'Bell tower', genre: 'War',
    setup: 'A sniper hides in a church tower in a ruined town. A patrol crosses the square below. He must decide whether to shoot and give away his place.',
    goal: 'Two points of view, one silent choice.',
    terms: ['pov_shot', 'lens_compression', 'focal_length', 'eyeline_match', 'tension'], tags: ['war', 'suspense'],
    checkpoints: [
      { label: 'Lens', dept: 'camera', context: 'You show the square through his scope.',
        step: s('Which lens?', [['a', 'A long telephoto lens'], ['b', 'A wide 18mm lens'], ['c', 'A fisheye']], 'a', 'A long [[focal_length]] makes far things look close.') },
      { label: 'Space', dept: 'camera', context: 'The soldiers walk in a line.',
        step: s('What does the long lens do to them?', [['a', 'Makes them look far apart'], ['b', 'Bends the walls'], ['c', 'Stacks them flat and close together']], 'c', 'Long lenses flatten depth: [[lens_compression]].') },
      { label: 'Link', dept: 'editing', context: 'A soldier looks up at the tower.',
        step: s('How do you cut?', [['a', 'Cut to the sniper looking down, matching the line of sight'], ['b', 'Cut to the sky'], ['c', 'Cut to another town']], 'a', 'Matching looks join two places: [[eyeline_match]].') },
      { label: 'Choice', dept: 'director', context: 'He does not shoot.',
        step: s('How does the actor show the choice?', [['a', 'He says why'], ['b', 'His finger leaves the trigger; he breathes out'], ['c', 'He shouts']], 'b', 'One small physical action ends the [[tension]].') },
    ],
    outcome: 'The scope [[pov_shot]] and long lens make the square close yet unreal. The [[eyeline_match]] links hunter and hunted.',
    ref: 'Enemy at the Gates (2001)',
  },
  {
    id: 'b2-mirror-hallway', title: 'The mirror hallway', genre: 'Horror',
    setup: 'A woman walks down a hotel hallway lined with mirrors. In one mirror her reflection is late by a second. She does not notice.',
    goal: 'A quiet wrong detail that the audience finds first.',
    terms: ['vfx', 'symmetry', 'frame_in_frame', 'compositor', 'previs'], tags: ['horror'],
    checkpoints: [
      { label: 'Plan', dept: 'preprod', context: 'The shot has a moving camera and a fake reflection.',
        step: s('What do you make before the shoot?', [['a', 'Nothing; find it on the day'], ['b', 'A rough 3D version of the move and the mirrors'], ['c', 'Only a poster']], 'b', 'Planning a hard shot in rough 3D is [[previs]].') },
      { label: 'Frame', dept: 'composition', context: 'The hallway is long and even.',
        step: s('How do you frame the hall?', [['a', 'Centered, both walls equal, mirrors in rows'], ['b', 'Tilted'], ['c', 'Off to one wall']], 'a', 'Perfect balance feels cold and makes any error stand out: [[symmetry]].') },
      { label: 'Effect', dept: 'modern', context: 'The late reflection is a second take of the actress.',
        step: s('How do you build it?', [['a', 'A real twin'], ['b', 'Paint on the mirror'], ['c', 'Shoot a second pass and place it in the mirror in post']], 'c', 'Adding images in post is [[vfx]].') },
      { label: 'Blender', dept: 'blender', context: 'You test the idea in Blender first.',
        step: s('Where do you mix the two render passes?', [['a', 'In the Shader Editor'], ['b', 'In the Compositor node tree'], ['c', 'In Edit Mode']], 'b', 'Blender joins passes after render in the [[compositor]].') },
    ],
    outcome: 'The [[symmetry]] of the hall makes one late reflection jump out. [[previs]] and clean [[vfx]] make the shot possible.',
    ref: 'The Shining (1980)',
  },
  {
    id: 'b2-getaway-car', title: 'The getaway that stalls', genre: 'Heist',
    setup: 'After a jewel heist the driver turns the key and the car will not start. Police sirens are near. The crew argues inside the car.',
    goal: 'Comic panic that is still tense.',
    terms: ['handheld', 'close_up', 'sound_bridge', 'jump_cut', 'reaction_shot'], tags: ['heist', 'suspense'],
    checkpoints: [
      { label: 'Camera', dept: 'camera', context: 'Four people in a small car, shouting.',
        step: s('How do you move the camera?', [['a', 'Locked off on a tripod'], ['b', 'A slow crane'], ['c', 'Handheld, close, pushed between faces']], 'c', 'A nervous loose camera is [[handheld]].') },
      { label: 'Time', dept: 'editing', context: 'The driver tries the key many times.',
        step: s('How do you show the many tries fast?', [['a', 'Cuts that skip time in the same framing'], ['b', 'Show every try in full'], ['c', 'Fade out']], 'a', 'Skipping time in one framing is a [[jump_cut]].') },
      { label: 'Sound', dept: 'sound', context: 'The sirens get closer.',
        step: s('How do you place the sirens?', [['a', 'Silence'], ['b', 'Start them low under the argument, rising each cut'], ['c', 'Very loud from the first frame']], 'b', 'Sound that carries over cuts is a [[sound_bridge]].') },
      { label: 'Laugh', dept: 'editing', context: 'The car starts. A police car drives past without stopping.',
        step: s('What is the best final shot?', [['a', 'The road ahead'], ['b', 'The police car'], ['c', 'The crew’s frozen faces, then one breath out']], 'c', 'The joke lands on the faces: [[reaction_shot]].') },
    ],
    outcome: 'Handheld closeness and [[jump_cut]] tries make the panic funny. The rising sirens keep it dangerous until the [[reaction_shot]].',
    ref: 'Baby Driver (2017)',
  },
  {
    id: 'b2-desert-water', title: 'Half a canteen', genre: 'Survival',
    setup: 'A guide and a tourist are lost in a desert. They have half a canteen of water. The guide must decide whether to share it.',
    goal: 'The heat and the choice must feel huge.',
    terms: ['wide_shot', 'negative_space', 'golden_hour', 'teal_orange', 'want_need'], tags: ['survival'],
    checkpoints: [
      { label: 'Scale', dept: 'composition', context: 'They walk over a dune.',
        step: s('How do you frame them?', [['a', 'Tight close-up'], ['b', 'Tiny figures in a huge empty frame of sand'], ['c', 'Medium shot']], 'b', 'Empty [[negative_space]] in a [[wide_shot]] makes them small.') },
      { label: 'Time', dept: 'lighting', context: 'You want long shadows and warm sand.',
        step: s('When do you shoot?', [['a', 'Noon'], ['b', 'Night'], ['c', 'Just after sunrise or before sunset']], 'c', 'Low warm sun is [[golden_hour]].') },
      { label: 'Grade', dept: 'color', context: 'You want hot sand and a cold shade.',
        step: s('Which grade?', [['a', 'Warm skin and sand, cool blue shadows'], ['b', 'Black and white'], ['c', 'All green']], 'a', 'Warm against cool is the [[teal_orange]] split.') },
      { label: 'Character', dept: 'story', context: 'The guide wants to survive. What does he need?',
        step: s('Which inner need fits the arc?', [['a', 'More water'], ['b', 'A map'], ['c', 'To trust a stranger']], 'c', 'Outer goal against inner lack: [[want_need]].') },
    ],
    outcome: 'The [[wide_shot]] makes the desert the enemy. The shared canteen turns his want into his [[want_need]] change.',
    ref: 'Lawrence of Arabia (1962)',
  },
  {
    id: 'b2-noir-stairs', title: 'Down the spiral stairs', genre: 'Noir',
    setup: 'A crooked lawyer runs down a spiral stair after a meeting goes wrong. A man waits at the bottom. The film is black and white.',
    goal: 'A trapped man in a world of shadow.',
    terms: ['birds_eye', 'silhouette', 'german_exp', 'value_structure', 'leading_lines'], tags: ['noir'],
    checkpoints: [
      { label: 'Angle', dept: 'camera', context: 'The stair is a tight spiral.',
        step: s('Which angle shows the trap?', [['a', 'Straight down the stairwell from the top'], ['b', 'Eye level'], ['c', 'From the street']], 'a', 'A straight-down view is a [[birds_eye]] shot.') },
      { label: 'Lines', dept: 'composition', context: 'The rails curve toward the floor.',
        step: s('How do you use the rails?', [['a', 'Hide them'], ['b', 'Let them spiral to the waiting man'], ['c', 'Blur them']], 'b', 'Lines that guide the eye are [[leading_lines]].') },
      { label: 'Shadow', dept: 'lighting', context: 'The waiting man stands by a lit doorway.',
        step: s('How do we see him?', [['a', 'Fully lit face'], ['b', 'A black shape against the bright door'], ['c', 'Soft fill on him']], 'b', 'A dark shape on a bright ground is a [[silhouette]].') },
      { label: 'History', dept: 'history', context: 'Your DP asks where this style comes from.',
        step: s('Which movement shaped noir shadows?', [['a', 'Italian Neorealism'], ['b', 'French New Wave'], ['c', 'German Expressionism of the 1920s']], 'c', 'Noir took its twisted shadows from [[german_exp]].') },
    ],
    outcome: 'The [[birds_eye]] spiral and the [[silhouette]] build a trap from light and dark alone. Strong [[value_structure]] does the work color would do.',
    ref: 'The Third Man (1949)',
  },
  {
    id: 'b2-ransom-call', title: 'The ransom call', genre: 'Crime',
    setup: 'A father gets a phone call from his son’s kidnapper. Police listen and trace the call. He must keep the man talking for one more minute.',
    goal: 'Two rooms, one clock, and a father who must not break.',
    terms: ['cross_cutting', 'close_up', 'diegetic', 'actor_direction', 'ecu'], tags: ['crime', 'suspense'],
    checkpoints: [
      { label: 'Actor', dept: 'director', context: 'The actor plays it with big tears.',
        step: s('What note do you give?', [['a', '“Cry more”'], ['b', '“Keep your voice calm for your son; let only your hand shake”'], ['c', '“Shout at him”']], 'b', 'A playable action, not a feeling, is good [[actor_direction]].') },
      { label: 'Detail', dept: 'camera', context: 'His hand grips the phone cord.',
        step: s('Which shot?', [['a', 'Wide room shot'], ['b', 'Extreme close-up of knuckles on the cord'], ['c', 'Ceiling shot']], 'b', 'A tiny detail filling the frame is an [[ecu]].') },
      { label: 'Cut', dept: 'editing', context: 'The police tech watches the trace bar fill.',
        step: s('How do you build the clock?', [['a', 'Cut between the father’s face and the trace screen'], ['b', 'Only show the father'], ['c', 'Add a title card']], 'a', 'Two linked actions cut together: [[cross_cutting]].') },
      { label: 'Voice', dept: 'sound', context: 'We hear the kidnapper.',
        step: s('How does his voice sound?', [['a', 'Thin and filtered, like a real phone line'], ['b', 'Full and clean like a narrator'], ['c', 'With music under it']], 'a', 'Sound from a source in the world is [[diegetic]]; the filter keeps it real.') },
    ],
    outcome: 'A calm voice and a shaking hand show the strain better than tears. [[cross_cutting]] to the trace screen sets the clock.',
    ref: 'High and Low (1963)',
  },
  {
    id: 'b2-forest-creature-anim', title: 'Something in the trees', genre: 'Horror (animated)',
    setup: 'An animated short: a girl walks home through a forest at dusk. A tall thin creature moves between the trees. You animate it in Blender.',
    goal: 'The creature must feel wrong, not just big.',
    terms: ['timing', 'moving_hold', 'ik', 'graph_editor', 'silhouette'], tags: ['animation', 'horror'],
    checkpoints: [
      { label: 'Design', dept: 'modeling', context: 'The creature is seen mostly from far away.',
        step: s('What must read at a distance?', [['a', 'Skin texture'], ['b', 'Eye color'], ['c', 'A clear odd outline: long arms, small head']], 'c', 'Shape must read as a dark [[silhouette]].') },
      { label: 'Motion', dept: 'anim_principle', context: 'It should feel unnatural.',
        step: s('How do you time its moves?', [['a', 'Long stillness, then very fast jerks'], ['b', 'Smooth even speed'], ['c', 'Bouncy and cartoony']], 'a', 'Odd [[timing]] makes motion feel wrong.') },
      { label: 'Feet', dept: 'rigging', context: 'Its feet must stay planted on the ground while the body leans.',
        step: s('Which leg setup?', [['a', 'FK only'], ['b', 'IK legs with a foot control'], ['c', 'No rig']], 'b', 'Planted feet need [[ik]].') },
      { label: 'Stillness', dept: 'anim_tech', context: 'It stands still behind a tree.',
        step: s('How do you keep it alive?', [['a', 'Freeze every bone'], ['b', 'Keep a tiny slow drift in the head and fingers'], ['c', 'Delete the keys']], 'b', 'Small motion in a pose is a [[moving_hold]].') },
      { label: 'Curves', dept: 'blender', context: 'The fast jerk looks soft.',
        step: s('Where do you sharpen it?', [['a', 'Make the curve handles sharp or set linear in the Graph Editor'], ['b', 'Add more lights'], ['c', 'Raise render samples']], 'a', 'Curve shape sets speed: [[graph_editor]].') },
    ],
    outcome: 'A clear [[silhouette]] and jerky [[timing]] make the creature feel wrong. [[moving_hold]] keeps it alive when it waits.',
    ref: 'Over the Garden Wall (2014)',
  },
  {
    id: 'b2-submarine-silent-run', title: 'Silent running', genre: 'War',
    setup: 'A submarine crew hides on the sea floor. A destroyer above listens for them. One sound will kill them all.',
    goal: 'The audience must hold its breath with the crew.',
    terms: ['silence', 'sound_design', 'low_key', 'color_meaning', 'eye_trace'], tags: ['war', 'suspense'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'The sub runs on emergency power.',
        step: s('How do you light the control room?', [['a', 'Bright white'], ['b', 'Dim red emergency lamps, deep shadow'], ['c', 'Daylight blue']], 'b', 'Dark frames with little fill are [[low_key]].') },
      { label: 'Color', dept: 'color', context: 'Why red?',
        step: s('What does red tell us here?', [['a', 'Romance'], ['b', 'Calm'], ['c', 'Alarm and danger']], 'c', 'Color carries a feeling: [[color_meaning]].') },
      { label: 'Sound', dept: 'sound', context: 'The destroyer passes overhead.',
        step: s('What do we hear?', [['a', 'Faint propeller thrum, ship creaks, a held breath'], ['b', 'Battle music'], ['c', 'Dialogue']], 'a', 'Tiny sounds become threats: [[sound_design]].') },
      { label: 'Frame', dept: 'composition', context: 'A sailor drops a wrench. It falls in slow motion.',
        step: s('Where does the eye go?', [['a', 'From the wrench down to the steel floor, then to the captain’s eyes'], ['b', 'To the ceiling'], ['c', 'Nowhere special']], 'a', 'Guiding the eye shot to shot is [[eye_trace]].') },
    ],
    outcome: 'Red [[low_key]] light and near [[silence]] trap us in the hull. Every tiny sound becomes a weapon.',
    ref: 'Das Boot (1981)',
  },
  {
    id: 'b2-witness-in-window', title: 'Witness at the window', genre: 'Mystery',
    setup: 'An old man with a broken hip watches his street from a window. He sees a neighbor carry a heavy rug to a van at 3 a.m. Nobody believes him.',
    goal: 'We share his limited view and his doubt.',
    terms: ['pov', 'frame_in_frame', 'focal_length', 'tension', 'plot_twist'], tags: ['mystery'],
    checkpoints: [
      { label: 'View', dept: 'story', context: 'Whose eyes tell the story?',
        step: s('Choose the view.', [['a', 'Only his; we never leave the flat'], ['b', 'Everyone’s'], ['c', 'The neighbor’s']], 'a', 'A locked narrative view is [[pov]].') },
      { label: 'Frame', dept: 'composition', context: 'He looks at the house across the street.',
        step: s('How do you frame the neighbor?', [['a', 'Full screen, no edges'], ['b', 'Inside his own window frame, small and far'], ['c', 'From inside the neighbor house']], 'b', 'A frame inside the frame is [[frame_in_frame]].') },
      { label: 'Lens', dept: 'camera', context: 'He uses old binoculars.',
        step: s('How do you shoot through them?', [['a', 'Wide lens'], ['b', 'Long lens with a soft round mask'], ['c', 'Drone']], 'b', 'Long [[focal_length]] brings far things close.') },
      { label: 'Ending', dept: 'story', context: 'The rug held only old carpet. Then he sees the neighbor bury a phone.',
        step: s('Why is this ending strong?', [['a', 'It surprises but fits clues shown earlier'], ['b', 'It comes from nowhere'], ['c', 'It explains nothing']], 'a', 'A fair surprise is a [[plot_twist]].') },
    ],
    outcome: 'We see only what he sees, framed far away. That limited [[pov]] keeps the [[tension]] until the twist.',
    ref: 'Rear Window (1954)',
  },
]
