import type { Scene, Step } from '../../shared/types'
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({ prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why })

// Batch 3: animation-heavy virtual scenes (2D TV anime, CG feature, stop motion, Blender shorts).
export const SCENES_B3: Scene[] = [
  {
    id: 'b3-rooftop-sakuga-duel', title: 'Duel above the train yard', genre: '2D anime TV / Action',
    setup: 'Episode 11 of a TV anime. Two rival swordswomen fight on the roofs of moving freight cars. The studio has a small budget for the episode, but this fight is the season’s big moment. You have one star animator for 40 seconds of it.',
    goal: 'Make the fight feel huge without breaking the budget.',
    terms: ['sakuga', 'limited_animation', 'smear', 'on_twos', 'genga', 'line_of_action'], tags: ['action', 'anime'],
    checkpoints: [
      { label: 'Budget plan', dept: 'director', context: 'The episode has 3,000 drawings in total. The fight alone could use all of them.',
        step: s('How do you spend the drawings?', [['a', 'Spread them evenly over every shot of the episode'], ['b', 'Use limited animation in the talk scenes, and give the star animator the key 40 seconds'], ['c', 'Cut the fight to a still frame with speed lines'], ['d', 'Animate everything on ones']], 'b', 'Save drawings in quiet scenes to pay for a burst of [[sakuga]].') },
      { label: 'Key drawings', dept: 'anim_principle', context: 'The star animator does the key poses. A clash pose looks stiff.',
        step: s('What makes the clash pose read as power?', [['a', 'Both bodies in one strong curved line of action, leaning into the hit'], ['b', 'Both women standing straight, swords level'], ['c', 'More detail on the costumes']], 'a', 'A clear [[line_of_action]] carries force through the whole body.') },
      { label: 'Fast swing', dept: 'anim_tech', context: 'A sword swing happens in two frames. On screen it strobes.',
        step: s('How do you fix the strobe?', [['a', 'Add more frames and slow the swing down'], ['b', 'Blur the whole frame in compositing'], ['c', 'Hold the swing for one second'], ['d', 'Draw a smear frame that stretches the blade and arm along the path']], 'd', 'A [[smear]] frame shows the motion path in one drawing.') },
      { label: 'Frame rate', dept: 'anim_tech', context: 'Most of the fight is on twos. One moment is a slow-motion leap.',
        step: s('Where do you go to ones?', [['a', 'Everywhere, to be safe'], ['b', 'Nowhere; twos are the anime standard'], ['c', 'Only on the fastest moves, like the final draw of the sword'], ['d', 'Only in the slow-motion leap']], 'c', 'Animating [[on_twos]] by default and ones for fast action gives snap and saves drawings.') },
      { label: 'Sound', dept: 'sound', context: 'The score is loud all through the fight.',
        step: s('What happens at the final hit?', [['a', 'Cut the music for one beat; play only the steel ring and the train'], ['b', 'Make the music louder'], ['c', 'Add a crowd cheer']], 'a', 'A sudden [[silence]] makes the hit land.') },
    ],
    outcome: 'The quiet scenes pay for the fight. Strong [[line_of_action]] keys, [[smear]] frames and a mix of twos and ones turn a small budget into real [[sakuga]].',
    ref: 'Mob Psycho 100 (2016), any big fight episode',
  },
  {
    id: 'b3-starlight-transformation', title: 'The first transformation', genre: '2D anime TV / Magical girl',
    setup: 'A shy girl, Hana, finds a star-shaped brooch in a rain gutter. In episode 1 she transforms for the first time to save her little brother. The studio will reuse this sequence in every later episode.',
    goal: 'A transformation that thrills once and still works the fortieth time.',
    terms: ['cycle', 'anticipation', 'appeal', 'color_script', 'exaggeration', 'leitmotif'], tags: ['anime', 'character'],
    checkpoints: [
      { label: 'Reuse', dept: 'preprod', context: 'The sequence will play in 40 episodes.',
        step: s('How do you plan it?', [['a', 'Animate it new every episode'], ['b', 'Make it once as a stock sequence, with short new shots before and after'], ['c', 'Skip it after episode 2']], 'b', 'Stock footage is classic [[limited_animation]] economy.') },
      { label: 'Start', dept: 'anim_principle', context: 'Hana raises the brooch. The flash comes at once.',
        step: s('What do you add before the flash?', [['a', 'Nothing; speed is good'], ['b', 'A small crouch and a held breath, then the arms go up'], ['c', 'A long title card'], ['d', 'A camera shake']], 'b', '[[anticipation]] prepares the eye for the big action.') },
      { label: 'Hair', dept: 'anim_tech', context: 'Her hair floats in a loop while the costume forms.',
        step: s('How do you build the floating hair?', [['a', 'A short seamless cycle that loops under the costume changes'], ['b', 'New drawings for every frame of 30 seconds'], ['c', 'A still drawing']], 'a', 'A [[cycle]] gives endless motion from a few drawings.') },
      { label: 'Color', dept: 'color', context: 'Hana’s normal life is grey-blue rain.',
        step: s('What colors does the transformation use?', [['a', 'The same grey-blue'], ['b', 'Pure black and white'], ['c', 'Warm pinks and gold that break the rain palette'], ['d', 'Random colors each shot']], 'c', 'Plan the change in a [[color_script]] so the new world pops.') },
      { label: 'Music', dept: 'sound', context: 'The composer asks for a theme.',
        step: s('What does the theme do?', [['a', 'A short melody that returns each time she transforms'], ['b', 'Different music every episode'], ['c', 'No music, only effects']], 'a', 'A [[leitmotif]] ties the moment to Hana every time.') },
    ],
    outcome: 'One strong stock sequence, with [[anticipation]], a hair [[cycle]] and its own [[leitmotif]], becomes the signature of the show.',
    ref: 'Puella Magi Madoka Magica (2011), episode 3',
  },
  {
    id: 'b3-mecha-hangar-launch', title: 'Launch from Hangar 7', genre: '2D anime TV / Mecha',
    setup: 'A rookie pilot is in a giant robot for the first time. The base is under attack. The launch rail fires the robot up a long tunnel into the sky. The robot is a CG model that must match the hand-drawn pilot.',
    goal: 'Weight and scale: the robot must feel 30 meters tall.',
    terms: ['npr', 'shader_to_rgb', 'slow_in_out', 'camera_angle', 'parallax', 'moving_hold'], tags: ['mecha', 'action'],
    checkpoints: [
      { label: 'Look', dept: 'blender', context: 'The CG robot looks plastic next to the 2D characters.',
        step: s('How do you match the styles in Blender?', [['a', 'Use Cycles with realistic glossy metal'], ['b', 'Use a toon shader: Shader to RGB into a Color Ramp with hard steps, plus line art'], ['c', 'Render it in wireframe'], ['d', 'Turn off all lights']], 'b', '[[shader_to_rgb]] (in EEVEE) gives flat cel shading for an [[npr]] look.') },
      { label: 'Scale', dept: 'camera', context: 'The robot stands on the rail.',
        step: s('Which angle shows its size?', [['a', 'Low angle from the deck crew’s feet, looking up'], ['b', 'High angle from above'], ['c', 'Eye level from its chest']], 'a', 'A low [[camera_angle]] makes a subject feel huge.') },
      { label: 'Weight', dept: 'anim_principle', context: 'The rail fires. The robot jumps to full speed in one frame.',
        step: s('How should the speed change?', [['a', 'Instant full speed'], ['b', 'Constant speed the whole way'], ['c', 'A slow, heavy start, then build to a blur'], ['d', 'Fast start, then slow down']], 'c', 'Heavy objects need time to start: [[slow_in_out]].') },
      { label: 'Tunnel', dept: 'anim_tech', context: 'The tunnel is long. Lights pass by.',
        step: s('How do you sell the speed cheaply?', [['a', 'Layers of tunnel lights sliding past at different speeds'], ['b', 'Animate the robot’s legs running'], ['c', 'One still background']], 'a', 'Layers at different speeds create [[parallax]] and depth.') },
    ],
    outcome: 'Toon shading with [[shader_to_rgb]] blends the CG robot into the 2D world. A low angle, a slow heavy start and [[parallax]] give it scale and weight.',
    ref: 'Neon Genesis Evangelion (1995), the first launch',
  },
  {
    id: 'b3-lantern-fox-short', title: 'The lantern fox', genre: 'Blender short / Fable',
    setup: 'A three-minute Blender short. A small fox carries a paper lantern through a winter forest to find her lost cub. There is no dialogue. You have a team of two and eight weeks.',
    goal: 'Finish a clear, warm short on time.',
    terms: ['animatic', 'blockout', 'eevee', 'acting_anim', 'volumetric', 'rigify'], tags: ['blender', 'short'],
    checkpoints: [
      { label: 'Plan', dept: 'preprod', context: 'Your partner wants to start modeling the fox at once.',
        step: s('What comes first?', [['a', 'Final fox model with fur'], ['b', 'An animatic with timing and temp sound'], ['c', 'Render tests'], ['d', 'The poster']], 'b', 'An [[animatic]] finds story and timing problems before costly work.') },
      { label: 'Set', dept: 'modeling', context: 'The forest needs to be ready for layout in week 2.',
        step: s('How do you build it first?', [['a', 'Simple shapes for trees and rocks to test camera and scale'], ['b', 'Sculpt every tree in detail'], ['c', 'Download a huge forest asset and hope']], 'a', 'A [[blockout]] lets you test layout before detail.') },
      { label: 'Rig', dept: 'rigging', context: 'Two people, no rigging expert.',
        step: s('How do you rig the fox?', [['a', 'Write a custom rig from scratch'], ['b', 'No rig; move the mesh in Edit Mode'], ['c', 'Start from a Rigify metarig, adjust bones to fit, then generate'], ['d', 'Use shape keys for the whole body']], 'c', '[[rigify]] builds a full control rig from a metarig.') },
      { label: 'Render', dept: 'blender', context: 'You have 4,300 frames and one GPU.',
        step: s('Which render engine?', [['a', 'EEVEE, for fast frames with good real-time lighting'], ['b', 'Cycles at 4,096 samples'], ['c', 'Workbench']], 'a', '[[eevee]] renders fast enough for a small team.') },
      { label: 'Light', dept: 'lighting', context: 'The lantern is the only warm light in a blue forest.',
        step: s('How do you make its glow feel real?', [['a', 'Remove the lantern light'], ['b', 'Light everything evenly'], ['c', 'Make the forest red'], ['d', 'A point light in the lantern and soft volumetric fog so the glow has shape']], 'd', '[[volumetric]] fog shows light in the air.') },
    ],
    outcome: 'An [[animatic]] and a [[blockout]] lock the plan early. [[rigify]] and [[eevee]] keep two people on schedule.',
    ref: 'Spring (Blender Studio, 2019)',
  },
  {
    id: 'b3-clay-breakfast', title: 'Breakfast for one', genre: 'Stop motion / Comedy',
    setup: 'A stop-motion short with clay puppets. An old man cooks breakfast for his late wife out of habit, then laughs at himself. The set is a small kitchen on a table. You shoot at 12 frames per second.',
    goal: 'Gentle comedy with real feeling, made by hand.',
    terms: ['stop_motion', 'on_twos', 'secondary_action', 'timing', 'practical'], tags: ['stop_motion', 'emotion'],
    checkpoints: [
      { label: 'Frame rate', dept: 'anim_tech', context: 'The producer asks why not shoot at 24 frames.',
        step: s('Why 12 frames per second?', [['a', 'It is a law for clay'], ['b', 'Shooting on twos halves the work and gives the hand-made feel'], ['c', 'Cameras cannot do 24']], 'b', 'Stop motion often plays [[on_twos]] for speed and style.') },
      { label: 'Gag', dept: 'anim_principle', context: 'He sets two plates and stops.',
        step: s('How long do you hold on him?', [['a', 'One frame'], ['b', 'No hold; cut away'], ['c', 'A long beat, with small blinks so the puppet stays alive'], ['d', 'Ten seconds frozen still']], 'c', 'Good [[timing]] gives the joke and the sadness room.') },
      { label: 'Detail', dept: 'anim_principle', context: 'He stirs the eggs. The shot feels flat.',
        step: s('What do you add?', [['a', 'His slippers tap a small rhythm while he stirs'], ['b', 'A camera spin'], ['c', 'Nothing']], 'a', '[[secondary_action]] adds life under the main action.') },
      { label: 'Light', dept: 'lighting', context: 'Studio lights flicker frame to frame.',
        step: s('What do you fix?', [['a', 'Use daylight from a real window'], ['b', 'Use stable lights, block outside light, and use a lamp on set as a practical'], ['c', 'Fix it later with a filter'], ['d', 'Shoot faster']], 'b', 'Controlled light and a [[practical]] lamp stop flicker in [[stop_motion]].') },
    ],
    outcome: '[[stop_motion]] at twelve frames, patient [[timing]] and small [[secondary_action]] make a clay man laugh and grieve.',
    ref: 'Wallace & Gromit: A Grand Day Out (1989)',
  },
  {
    id: 'b3-cg-feature-hero-walk', title: 'The walk to the gate', genre: 'CG feature / Adventure',
    setup: 'A CG feature. A young baker, Tomas, walks to the city gate to leave home for the first time. His mother watches from the bakery door. This shot must show he is scared but proud.',
    goal: 'A walk that tells the audience how he feels.',
    terms: ['walk_cycle', 'acting_anim', 'reference_video', 'blocking_anim', 'spline_pass', 'graph_editor'], tags: ['character', 'cg'],
    checkpoints: [
      { label: 'Reference', dept: 'anim_tech', context: 'The animator wants to start keys at once.',
        step: s('What first?', [['a', 'Film yourself doing the walk, scared then proud'], ['b', 'Copy a generic walk from a library'], ['c', 'Use mocap of a soldier'], ['d', 'Skip reference; trust instinct']], 'a', '[[reference_video]] gives real timing and detail.') },
      { label: 'Walk', dept: 'anim_principle', context: 'The walk is a clean, even loop.',
        step: s('How do you make it act?', [['a', 'Keep the clean loop'], ['b', 'Start with a hesitant step, then lift the chest and lengthen the stride'], ['c', 'Make him run']], 'b', 'A [[walk_cycle]] is a base; [[acting_anim]] changes it to show thought.') },
      { label: 'Stage', dept: 'anim_tech', context: 'The director wants to review early.',
        step: s('What do you show first?', [['a', 'Fully polished frames'], ['b', 'Only the face'], ['c', 'Stepped key poses with no interpolation'], ['d', 'Lighting tests']], 'c', '[[blocking_anim]] in stepped keys is fast to review and change.') },
      { label: 'Polish', dept: 'blender', context: 'After spline, his hips float.',
        step: s('Where do you fix it?', [['a', 'In the Graph Editor, adjust the hip curves so they dip on each contact'], ['b', 'Delete all keys'], ['c', 'Add a cloth simulation']], 'a', 'The [[graph_editor]] shows and fixes motion curves after the [[spline_pass]].') },
      { label: 'Camera', dept: 'camera', context: 'The mother watches.',
        step: s('Where is the camera?', [['a', 'Above the city'], ['b', 'Behind the mother, over her shoulder, Tomas getting small'], ['c', 'In front of Tomas, close']], 'b', 'An [[ots]] from her side lets us feel both of them.') },
    ],
    outcome: '[[reference_video]], stepped [[blocking_anim]] and a careful [[spline_pass]] turn a plain [[walk_cycle]] into a goodbye.',
    ref: 'Ratatouille (2007), the walk through Paris',
  },
  {
    id: 'b3-mascot-cereal-spot', title: 'Mascot for a cereal ad', genre: 'Commercial / Mascot',
    setup: 'A 15-second TV spot. The client wants a new mascot: a round honey bee who loves oats. It must read on phone screens and on a cereal box. Kids must love it in two seconds.',
    goal: 'A mascot with instant appeal and clear motion.',
    terms: ['appeal', 'shape_language', 'squash_stretch', 'model_sheet', 'staging_clarity'], tags: ['mascot', 'character'],
    checkpoints: [
      { label: 'Design', dept: 'modeling', context: 'The first design has sharp wings and a pointed face.',
        step: s('Which shapes?', [['a', 'Triangles everywhere'], ['b', 'Squares for strength'], ['c', 'Round body and big round eyes, small soft wings'], ['d', 'Thin lines only']], 'c', 'Round [[shape_language]] reads as friendly.') },
      { label: 'Consistency', dept: 'preprod', context: 'Three studios will draw the bee for print and web.',
        step: s('What do you give them?', [['a', 'A model sheet with turnarounds, expressions and proportions'], ['b', 'One photo'], ['c', 'Nothing; trust them']], 'a', 'A [[model_sheet]] keeps the character on model.') },
      { label: 'Motion', dept: 'anim_principle', context: 'The bee lands on the bowl. It looks stiff.',
        step: s('What helps?', [['a', 'Keep its shape rigid'], ['b', 'Squash on landing and stretch on the bounce up, with the same volume'], ['c', 'Add a motion blur only']], 'b', '[[squash_stretch]] shows weight and flexibility.') },
      { label: 'Read', dept: 'composition', context: 'The product, the bee and the logo fight in one frame.',
        step: s('How do you stage it?', [['a', 'All three same size'], ['b', 'Put the bee behind the box'], ['c', 'Fill the frame with oats'], ['d', 'One idea per shot: bee, then bowl, then logo, each clear in silhouette']], 'd', '[[staging_clarity]] means one clear idea at a time.') },
    ],
    outcome: 'Round [[shape_language]] gives [[appeal]], a [[model_sheet]] keeps it on model, and [[squash_stretch]] makes the bee feel alive.',
    ref: 'Kiki’s Delivery Service (1989), for Jiji’s simple appeal',
  },
  {
    id: 'b3-swamp-creature-reveal', title: 'Something in the reeds', genre: 'CG feature / Creature',
    setup: 'A CG fantasy feature. Two kids on a raft see a huge creature rise from a swamp. It turns out to be gentle, but the first look must scare. The creature has six legs and a long neck.',
    goal: 'A believable creature, scary first, gentle later.',
    terms: ['sculpting', 'retopology', 'ik', 'follow_through', 'reference_image', 'silhouette'], tags: ['creature', 'cg'],
    checkpoints: [
      { label: 'Design', dept: 'modeling', context: 'The sculptor wants to start with no reference.',
        step: s('What do you give them?', [['a', 'Nothing'], ['b', 'Photos of real animals: moose, heron, hippo'], ['c', 'Screenshots from other monster films'], ['d', 'A random noise texture']], 'b', '[[reference_image]] from real animals makes a creature believable.') },
      { label: 'Mesh', dept: 'modeling', context: 'The sculpt has 20 million faces. Riggers cannot use it.',
        step: s('What next?', [['a', 'Rig the sculpt directly'], ['b', 'Decimate it to random triangles'], ['c', 'Build a clean low-poly mesh over it with good edge loops, then bake details'], ['d', 'Start over']], 'c', '[[retopology]] makes an animatable mesh from a [[sculpting]] pass.') },
      { label: 'Legs', dept: 'rigging', context: 'Six feet must stay planted on the mud while the body moves.',
        step: s('Which leg setup?', [['a', 'IK legs with foot controls'], ['b', 'FK only'], ['c', 'No rig; sculpt each frame']], 'a', '[[ik]] keeps feet locked while the body moves.') },
      { label: 'Neck', dept: 'anim_principle', context: 'The head stops, and the long neck stops at the same time.',
        step: s('How should the neck move?', [['a', 'Stop all at once'], ['b', 'Shake randomly'], ['c', 'Move faster than the head'], ['d', 'Let the neck settle after the head stops, in a wave']], 'd', '[[follow_through]] makes long parts settle after the main action.') },
      { label: 'Reveal', dept: 'lighting', context: 'First look at the creature in fog.',
        step: s('How do you reveal it?', [['a', 'Backlit dark shape in fog, details hidden'], ['b', 'Bright flat front light'], ['c', 'Close-up of its teeth']], 'a', 'A [[silhouette]] lets the audience imagine the worst.') },
    ],
    outcome: 'Real [[reference_image]], clean [[retopology]], [[ik]] legs and [[follow_through]] build a creature we believe. A fog [[silhouette]] makes the first look scary.',
    ref: 'How to Train Your Dragon (2010), the first Toothless meeting',
  },
  {
    id: 'b3-robot-lip-sync', title: 'The robot learns to lie', genre: 'Blender short / Sci-fi drama',
    setup: 'A small kitchen robot with a soft rubber face must tell its owner that the cake did not burn. It did. The robot has never lied before. The scene is a single close-up of 12 seconds.',
    goal: 'The audience sees the lie on the face before the owner does.',
    terms: ['lip_sync', 'shape_keys', 'facial_rig', 'drivers', 'subtext', 'moving_hold'], tags: ['character', 'blender'],
    checkpoints: [
      { label: 'Mouth', dept: 'rigging', context: 'The face needs mouth shapes for speech.',
        step: s('How do you build them in Blender?', [['a', 'Shape keys for each mouth shape, controlled by a facial rig'], ['b', 'Move vertices every frame'], ['c', 'A new mesh per frame'], ['d', 'A texture with painted mouths']], 'a', '[[shape_keys]] store mesh poses for a [[facial_rig]].') },
      { label: 'Controls', dept: 'rigging', context: 'The animator wants one slider for “nervous smile”.',
        step: s('How do you build it?', [['a', 'Ask the animator to move six keys at once'], ['b', 'A driver links one bone to several shape keys'], ['c', 'Make another mesh']], 'b', '[[drivers]] let one control move many values.') },
      { label: 'Speech', dept: 'anim_tech', context: 'The robot says “The cake is perfect.”',
        step: s('How do you time the mouth?', [['a', 'Open and close on every letter'], ['b', 'Ignore the audio'], ['c', 'Key the main vowel and consonant shapes, a frame or two before the sound']], 'c', 'Good [[lip_sync]] hits shapes slightly early and skips small sounds.') },
      { label: 'The lie', dept: 'story', context: 'How does the audience see the lie?',
        step: s('What does the robot do?', [['a', 'Says “I am lying”'], ['b', 'Its eyes flick to the oven for two frames while it smiles'], ['c', 'Its face turns red'], ['d', 'Nothing']], 'b', 'The truth under the words is [[subtext]].') },
    ],
    outcome: '[[shape_keys]] and [[drivers]] give a clean [[facial_rig]]. Early [[lip_sync]] and a two-frame glance carry the [[subtext]].',
    ref: 'WALL-E (2008), the first scenes',
  },
  {
    id: 'b3-paper-boat-fight', title: 'Kitchen-sink storm', genre: 'Stop motion / Adventure',
    setup: 'A stop-motion short. A tiny paper boat with a mouse captain fights a storm in a kitchen sink. The tap is the storm. The water must look wild but the boat is a puppet.',
    goal: 'A storm at tiny scale that feels epic.',
    terms: ['stop_motion', 'dof', 'compositor', 'arcs', 'exaggeration', 'vfx'], tags: ['stop_motion', 'action'],
    checkpoints: [
      { label: 'Water', dept: 'anim_tech', context: 'Real water ruins clay and paper.',
        step: s('How do you make the water?', [['a', 'Pour real water on the set'], ['b', 'Animate shaped clear resin or gel waves frame by frame, or add water in post'], ['c', 'Leave water out']], 'b', 'In [[stop_motion]], water is usually a sculpted prop or [[vfx]].') },
      { label: 'Scale', dept: 'camera', context: 'The shots look like a toy on a table.',
        step: s('What sells a big storm?', [['a', 'Very shallow focus'], ['b', 'A wide high shot'], ['c', 'Deeper focus with a small aperture, and a low camera near the water'], ['d', 'A zoom lens at its longest']], 'c', 'Shallow [[dof]] shouts “miniature”. Deep focus makes small sets look big.') },
      { label: 'Boat', dept: 'anim_principle', context: 'The boat tips in a straight line on each wave.',
        step: s('How should it move?', [['a', 'In curved arcs, rising and falling'], ['b', 'Straight up and down'], ['c', 'Hold still']], 'a', 'Natural motion follows [[arcs]].') },
      { label: 'Post', dept: 'blender', context: 'You need rain and spray over the puppet frames.',
        step: s('Where do you combine them?', [['a', 'In the Video Sequencer only'], ['b', 'Paint each frame in Photoshop'], ['c', 'Skip it'], ['d', 'In the Compositor: puppet plate plus rain and spray layers']], 'd', 'Blender’s [[compositor]] layers images with nodes.') },
    ],
    outcome: 'Sculpted water, deep [[dof]], boat [[arcs]] and [[compositor]] rain make a sink into an ocean.',
    ref: 'Fantastic Mr. Fox (2009)',
  },
  {
    id: 'b3-ghost-cat-blender', title: 'The ghost cat', genre: 'Blender short / Cozy horror',
    setup: 'A girl moves into an old house. A see-through ghost cat follows her and knocks things off shelves. The tone is spooky but cute. The cat glows and has no clear outline.',
    goal: 'A ghost that feels soft, cute and a little strange.',
    terms: ['principled_bsdf', 'eevee', 'view_layer', 'compositor', 'appeal', 'anticipation'], tags: ['blender', 'creature'],
    checkpoints: [
      { label: 'Shader', dept: 'blender', context: 'The cat must be see-through and glow.',
        step: s('How do you set the material?', [['a', 'A Principled BSDF with transmission and alpha, plus an emission color'], ['b', 'A black diffuse material'], ['c', 'A mirror material'], ['d', 'An image of a cat on a plane']], 'a', 'The [[principled_bsdf]] mixes transparency and emission in one node.') },
      { label: 'Glow', dept: 'blender', context: 'You want a soft halo only on the cat.',
        step: s('How do you do it?', [['a', 'Glow on the whole frame'], ['b', 'Render the cat on its own view layer and add glare only to it in the Compositor'], ['c', 'Turn up all lights']], 'b', 'A [[view_layer]] lets you treat one object alone in the [[compositor]].') },
      { label: 'Gag', dept: 'anim_principle', context: 'The cat pushes a cup off the shelf.',
        step: s('How do you build the joke?', [['a', 'The cup just falls'], ['b', 'Show the shelf after'], ['c', 'Cat stares at the girl, slowly pushes the cup to the edge, waits, then flicks it'], ['d', 'Speed up the shot']], 'c', 'A slow build is [[anticipation]]; the wait makes the joke.') },
      { label: 'Cute', dept: 'modeling', context: 'The first model looks like a real thin cat.',
        step: s('How do you make it cute?', [['a', 'Bigger head, round body, short legs'], ['b', 'Add realistic fur and bones'], ['c', 'Make it bigger than the girl']], 'a', 'Soft round proportions give [[appeal]].') },
    ],
    outcome: 'A [[principled_bsdf]] glow, a separate [[view_layer]] and slow [[anticipation]] make a ghost that scares and charms.',
    ref: 'My Neighbor Totoro (1988)',
  },
  {
    id: 'b3-bouncing-ball-exam', title: 'The ball exam', genre: 'Animation school / Exercise',
    setup: 'First week at an animation school. The teacher says: “A rubber ball and a bowling ball fall off the same table. Make me know which is which with no texture.” Both are grey spheres.',
    goal: 'Show weight with motion alone.',
    terms: ['bouncing_ball', 'spacing', 'squash_stretch', 'graph_editor', 'timing', 'interpolation'], tags: ['basics', 'blender'],
    checkpoints: [
      { label: 'Rubber', dept: 'anim_principle', context: 'The rubber ball.',
        step: s('How does it bounce?', [['a', 'One bounce, then stops dead'], ['b', 'Many bounces, each lower, with squash on contact'], ['c', 'Floats down slowly'], ['d', 'No squash, one bounce']], 'b', 'The [[bouncing_ball]] loses height on each bounce; [[squash_stretch]] shows it is soft.') },
      { label: 'Bowling', dept: 'anim_principle', context: 'The bowling ball.',
        step: s('How does it land?', [['a', 'Big bounce with stretch'], ['b', 'Same as the rubber ball'], ['c', 'Slow fall'], ['d', 'Hits hard, almost no bounce, no squash']], 'd', 'Heavy and rigid: different [[timing]] and no squash.') },
      { label: 'Spacing', dept: 'anim_principle', context: 'The falls look floaty.',
        step: s('How should the frames be spaced?', [['a', 'Even spacing all the way'], ['b', 'Close at the top, wide near the ground'], ['c', 'Wide at the top, close at the ground']], 'b', 'Gravity speeds things up: wider [[spacing]] near the floor.') },
      { label: 'Curves', dept: 'blender', context: 'In Blender the ball slows down before each contact.',
        step: s('What is wrong?', [['a', 'Default Bezier ease on contact keys; make the curve sharp at contact in the Graph Editor'], ['b', 'The frame rate'], ['c', 'The ball radius'], ['d', 'The render engine']], 'a', 'Default [[interpolation]] eases in; fix contact handles in the [[graph_editor]].') },
    ],
    outcome: '[[spacing]], [[timing]] and [[squash_stretch]] tell weight without texture. The [[graph_editor]] fixes Blender’s default ease.',
    ref: 'The Animator’s Survival Kit (book), then watch Luxo Jr. (1986)',
  },
  {
    id: 'b3-grease-pencil-memory', title: 'Pencil memories', genre: 'Blender short / 2D drama',
    setup: 'A woman finds her father’s old sketchbook. As she turns pages, his drawings come alive in pencil lines over the real 3D room. The short mixes a 3D room with hand-drawn 2D lines.',
    goal: 'Make the drawings feel hand-made and alive inside a 3D space.',
    terms: ['grease_pencil', 'npr', 'camera_blender', 'straight_pose'], tags: ['blender', '2d'],
    checkpoints: [
      { label: 'Tool', dept: 'blender', context: 'You want 2D drawing directly in the 3D scene.',
        step: s('Which Blender tool?', [['a', 'Grease Pencil objects, drawn in the viewport'], ['b', 'Sculpt Mode'], ['c', 'The Video Sequencer'], ['d', 'Geometry Nodes only']], 'a', '[[grease_pencil]] draws 2D strokes that live in 3D space.') },
      { label: 'Method', dept: 'anim_principle', context: 'The father’s drawings should feel loose and alive.',
        step: s('How do you animate them?', [['a', 'Strict pose-to-pose with perfect inbetweens'], ['b', 'Mostly straight ahead, drawing frame after frame'], ['c', 'Interpolate everything']], 'b', '[[straight_pose]]: straight ahead gives loose, organic motion.') },
      { label: 'Line', dept: 'anim_tech', context: 'The lines look too clean, like vectors.',
        step: s('How do you make them feel like pencil?', [['a', 'Thicker solid lines'], ['b', 'Add a glow'], ['c', 'Use a textured pencil brush and redraw slightly each frame so lines “boil”'], ['d', 'Hide the lines']], 'c', 'Line boil is a classic [[npr]] hand-made look.') },
      { label: 'Camera', dept: 'camera', context: 'The camera moves through the room past the drawings.',
        step: s('What must you watch?', [['a', 'Nothing'], ['b', 'Use only a static camera'], ['c', 'Keep drawings on flat layers facing the camera, or they look thin from the side'], ['d', 'Use a fisheye lens']], 'c', 'Plan the [[camera_blender]] path: 2D strokes are flat in 3D.') },
    ],
    outcome: '[[grease_pencil]] and [[straight_pose]] drawing bring loose [[npr]] lines into a 3D room.',
    ref: 'Hero (Blender Studio, 2018)',
  },
  {
    id: 'b3-anime-ep-opening', title: 'The opening credits', genre: '2D anime TV / Opening',
    setup: 'A new sports anime about a girls’ rowing team. You direct the 90-second opening credits. The song is fixed. The studio asks for “energy and team spirit”.',
    goal: 'An opening that sells the show in 90 seconds.',
    terms: ['animatic', 'match_cut', 'pacing', 'sakuga', 'anime_history', 'multiplane'], tags: ['anime', 'editing'],
    checkpoints: [
      { label: 'Timing', dept: 'preprod', context: 'The song is locked.',
        step: s('How do you plan the shots?', [['a', 'Draw first, fit music later'], ['b', 'Cut an animatic to the song, beat by beat'], ['c', 'Random shots'], ['d', 'Only a title card']], 'b', 'An [[animatic]] to the music locks timing before drawing.') },
      { label: 'Team', dept: 'editing', context: 'Each of six girls gets a short shot.',
        step: s('How do you link them?', [['a', 'Fade to black between each'], ['b', 'Match cuts: one girl’s oar stroke becomes the next girl’s oar stroke'], ['c', 'Hard cuts with no link']], 'b', 'A [[match_cut]] ties the team together in motion.') },
      { label: 'Chorus', dept: 'director', context: 'The chorus hits at 0:50.',
        step: s('What plays on the chorus?', [['a', 'The best-animated shot: the whole boat surging, full sakuga'], ['b', 'A still logo'], ['c', 'A slow pan of the sky'], ['d', 'Text credits only']], 'a', 'Put the [[sakuga]] peak where the music peaks.') },
      { label: 'Depth', dept: 'camera', context: 'A shot of the river feels flat.',
        step: s('How do you add depth?', [['a', 'One painted layer'], ['b', 'Zoom in'], ['c', 'Separate foreground reeds, the boat and far hills, each moving at its own speed'], ['d', 'Blur it']], 'c', 'Layered art moving apart is the [[multiplane]] effect.') },
    ],
    outcome: 'An [[animatic]] cut to the song, [[match_cut]] links and a [[sakuga]] chorus make the opening sing.',
    ref: 'Haikyu!! (2014), first opening',
  },
  {
    id: 'b3-dragon-flight-cycle', title: 'Dragon over the harbor', genre: 'CG feature / Fantasy',
    setup: 'A young dragon carries a messenger across a harbor at dawn. The shot is 20 seconds and must loop into a longer flight for a game trailer later. The wings are huge and leathery.',
    goal: 'Powerful flight that can loop.',
    terms: ['cycle', 'drag', 'nla', 'follow_through', 'golden_hour', 'arcs'], tags: ['creature', 'cg'],
    checkpoints: [
      { label: 'Loop', dept: 'anim_tech', context: 'The flap must repeat forever.',
        step: s('How do you build it?', [['a', 'A flap cycle where the last frame matches the first'], ['b', 'Key each flap by hand for 20 seconds'], ['c', 'Use physics only']], 'a', 'A [[cycle]] loops when the first and last poses match.') },
      { label: 'Wings', dept: 'anim_principle', context: 'The wing tips move with the shoulders, like boards.',
        step: s('What do the tips do?', [['a', 'Move first'], ['b', 'Lag behind the shoulder, then whip through'], ['c', 'Stay still'], ['d', 'Move in straight lines']], 'b', '[[drag]]: end parts trail the main part.') },
      { label: 'Layers', dept: 'blender', context: 'You need the flap cycle plus a long banking turn on top.',
        step: s('How do you combine them in Blender?', [['a', 'Bake all into one action by hand'], ['b', 'Render twice'], ['c', 'Delete the cycle'], ['d', 'Put the cycle and the turn as strips in the NLA editor']], 'd', 'The [[nla]] layers and repeats actions as strips.') },
      { label: 'Light', dept: 'lighting', context: 'Dawn over the sea.',
        step: s('What light?', [['a', 'Low warm sun through the wing membrane'], ['b', 'Hard noon sun'], ['c', 'Flat grey']], 'a', '[[golden_hour]] light makes the wings glow.') },
    ],
    outcome: 'A clean [[cycle]] with wing [[drag]], layered in the [[nla]], flies at [[golden_hour]].',
    ref: 'How to Train Your Dragon 2 (2014)',
  },
  {
    id: 'b3-crowd-festival-cg', title: 'Lantern festival crowd', genre: 'CG feature / Musical',
    setup: 'A CG musical. The heroine sings in a night market full of 2,000 people. Your team can animate only 15 hero characters by hand. The rest must still feel alive.',
    goal: 'A big living crowd without 2,000 animators.',
    terms: ['geometry_nodes', 'lod', 'cycle', 'asset_library', 'staging_clarity', 'procedural'], tags: ['cg', 'crowd'],
    checkpoints: [
      { label: 'Crowd', dept: 'blender', context: 'You need 2,000 people.',
        step: s('How do you fill the market?', [['a', 'Instance a few animated people with Geometry Nodes, with random offsets'], ['b', 'Animate all 2,000 by hand'], ['c', 'A painted backdrop only'], ['d', 'Copy one person 2,000 times, same timing']], 'a', '[[geometry_nodes]] can scatter instances with random variation.') },
      { label: 'Detail', dept: 'modeling', context: 'Renders are too slow.',
        step: s('What do you do with far people?', [['a', 'Full detail for all'], ['b', 'Use simpler, lower-poly versions far from camera'], ['c', 'Delete them']], 'b', '[[lod]]: less detail where the eye cannot see it.') },
      { label: 'Motion', dept: 'anim_tech', context: 'Background people need motion.',
        step: s('What do they play?', [['a', 'Nothing; stand still'], ['b', 'Full hand animation'], ['c', 'Short cycles: clapping, eating, chatting, offset in time']], 'c', 'Offset [[cycle]] clips make crowds feel alive.') },
      { label: 'Focus', dept: 'composition', context: 'The heroine gets lost in the crowd.',
        step: s('How do you keep her clear?', [['a', 'Make the crowd louder'], ['b', 'Same lights for all'], ['c', 'More people near her'], ['d', 'Light her brighter, give the crowd darker values, and keep space around her']], 'd', '[[staging_clarity]] guides the eye in a busy frame.') },
    ],
    outcome: '[[geometry_nodes]] instances, [[lod]] and offset [[cycle]] clips fill the market, and [[staging_clarity]] keeps the heroine first.',
    ref: 'Coco (2017), the Land of the Dead bridge',
  },
  {
    id: 'b3-hard-surface-ship', title: 'The courier ship', genre: 'Blender short / Sci-fi',
    setup: 'A Blender short about a lone courier in a battered spaceship. The ship is the second star of the film. The camera will go very close to its hull.',
    goal: 'A hero ship that holds up in close-up.',
    terms: ['hard_surface', 'bevel', 'support_loop', 'boolean', 'normals', 'kitbash'], tags: ['modeling', 'blender'],
    checkpoints: [
      { label: 'Edges', dept: 'modeling', context: 'The hull edges look razor sharp and fake.',
        step: s('What fixes it?', [['a', 'Add a Bevel modifier so edges catch light'], ['b', 'More texture'], ['c', 'A blur in post'], ['d', 'Scale it up']], 'a', 'Real edges are never perfect: a [[bevel]] catches highlights.') },
      { label: 'Subdivision', dept: 'modeling', context: 'With Subdivision Surface, the hull turns into a blob.',
        step: s('How do you keep shape?', [['a', 'Remove all edges'], ['b', 'Add support loops close to the hard edges'], ['c', 'Add more subdivision levels'], ['d', 'Use a Mirror modifier']], 'b', '[[support_loop]] edges hold corners under subdivision.') },
      { label: 'Vents', dept: 'modeling', context: 'You need cut-in vents and hatches.',
        step: s('Fast way?', [['a', 'Boolean cutters, then clean shading'], ['b', 'Paint them on'], ['c', 'Sculpt them'], ['d', 'Skip them']], 'a', 'A [[boolean]] cuts one shape from another.') },
      { label: 'Shading', dept: 'blender', context: 'Dark smudges appear across flat panels after the cuts.',
        step: s('What do you check?', [['a', 'The render samples'], ['b', 'The world color'], ['c', 'The normals: use Auto Smooth or weighted normals'], ['d', 'The camera lens']], 'c', 'Bad [[normals]] cause shading smudges on hard surfaces.') },
      { label: 'Story', dept: 'story', context: 'The ship looks brand new.',
        step: s('What tells its story?', [['a', 'Clean white paint'], ['b', 'Patched plates, scorch marks, one mismatched part'], ['c', 'A giant logo']], 'b', 'Wear and patches are [[visual_storytelling]].') },
    ],
    outcome: '[[bevel]], [[support_loop]] edges, [[boolean]] cuts and clean [[normals]] give a [[hard_surface]] hero ship with a past.',
    ref: 'Sprite Fright (Blender Studio, 2021), for production files',
  },
  {
    id: 'b3-old-man-rotoscope', title: 'Grandfather’s dance', genre: '2D short / Character acting',
    setup: 'A 2D short. A boy films his grandfather doing an old folk dance. Years later the boy is an animator and turns the dance into animation. The motion must feel true to one real man.',
    goal: 'Honest, specific human motion in 2D.',
    terms: ['rotoscope', 'reference_video', 'exaggeration', 'solid_drawing', 'contact_pose', 'appeal'], tags: ['character', '2d'],
    checkpoints: [
      { label: 'Method', dept: 'anim_tech', context: 'You have the old home video.',
        step: s('How do you use it?', [['a', 'Ignore it'], ['b', 'Trace it frame by frame, then redraw to push the poses'], ['c', 'Only listen to the audio'], ['d', 'Use it as a background']], 'b', '[[rotoscope]] traces live action; redrawing makes it animation.') },
      { label: 'Push', dept: 'anim_principle', context: 'The traced motion looks floaty and dull.',
        step: s('What do you add?', [['a', 'Nothing; tracing is truth'], ['b', 'Push the key poses: deeper bends, bigger kicks'], ['c', 'More frames']], 'b', '[[exaggeration]] makes real motion read as strong animation.') },
      { label: 'Feet', dept: 'anim_principle', context: 'His feet slide on the floor.',
        step: s('What do you lock?', [['a', 'The contact poses, where each foot meets the floor'], ['b', 'The hands'], ['c', 'The head'], ['d', 'The background']], 'a', 'A clean [[contact_pose]] plants the feet.') },
      { label: 'Volume', dept: 'anim_principle', context: 'His body changes size between drawings.',
        step: s('What skill do you need?', [['a', 'Faster drawing'], ['b', 'Thicker lines'], ['c', 'Drawing form in 3D: keep weight, volume and balance'], ['d', 'More colors']], 'c', '[[solid_drawing]] keeps the body solid in every frame.') },
    ],
    outcome: '[[rotoscope]] gives truth, [[exaggeration]] gives life, and [[contact_pose]] and [[solid_drawing]] keep the old man real.',
    ref: 'Tower (2016)',
  },
]
