import type { Scene, Step } from '../../shared/types'
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({ prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why })
export const SCENES_B4: Scene[] = [
  {
    id: 'b4-market-chase', title: 'Chase through the fish market', genre: 'Action',
    setup: 'A courier runs through a crowded morning fish market with a stolen key card. Two guards chase her. Stalls, ice and crates block every path.',
    goal: 'The audience must always know where she is and where the guards are.',
    terms: ['screen_direction', 'action_choreo', 'wide_shot', 'pacing', 'foley'], tags: ['action', 'chase'],
    checkpoints: [
      { label: 'Geography', dept: 'director', context: 'The chase has twenty shots. Test viewers get lost.',
        step: s('What fixes the confusion?', [['a', 'More shaky close-ups'], ['b', 'Keep her running left to right in every shot'], ['c', 'Cut faster'], ['d', 'Add a map graphic']], 'b', 'Constant [[screen_direction]] tells us she keeps going the same way.') },
      { label: 'Frame size', dept: 'camera', context: 'She vaults a crate of ice.',
        step: s('How do you shoot the vault?', [['a', 'A wide shot that shows her whole body and the crate'], ['b', 'An extreme close-up of her eye'], ['c', 'An insert of the key card']], 'a', 'A [[wide_shot]] lets the audience read the full stunt.') },
      { label: 'Rhythm', dept: 'editing', context: 'The whole chase is cut at the same speed.',
        step: s('How do you shape the pace?', [['a', 'Same length for every shot'], ['b', 'Slow everything down'], ['c', 'Short shots in the run, one held shot when she hides under a stall']], 'c', 'A change of rhythm is [[pacing]]; the pause makes the next burst hit harder.') },
      { label: 'Sound', dept: 'sound', context: 'The location sound is only crowd noise.',
        step: s('What do you add?', [['a', 'Only music'], ['b', 'Nothing'], ['c', 'A narrator'], ['d', 'Wet footsteps, sliding ice, crates hitting the floor']], 'd', 'Recorded detail sounds are [[foley]]; they make each hit physical.') },
    ],
    outcome: 'Clear [[screen_direction]] and wide frames keep the geography. The [[pacing]] and [[foley]] give the chase weight and breath.',
    ref: 'Casino Royale (2006), the opening parkour chase',
  },
  {
    id: 'b4-wedding-cake', title: 'The cake falls', genre: 'Comedy',
    setup: 'A nervous best man carries a five-layer wedding cake across the hall. Everyone watches. The audience already saw the loose floor tile.',
    goal: 'Build a big laugh from one fall.',
    terms: ['setup_payoff', 'wide_shot', 'reaction_shot', 'timing', 'silence'], tags: ['comedy', 'physical'],
    checkpoints: [
      { label: 'Plant', dept: 'story', context: 'The fall comes as a total surprise now.',
        step: s('What do you add earlier?', [['a', 'A waiter trips on the loose tile and nobody fixes it'], ['b', 'Nothing; surprise is better'], ['c', 'A title card: “Danger”']], 'a', 'Plant it early, pay it off later: [[setup_payoff]].') },
      { label: 'Frame', dept: 'camera', context: 'The fall is physical comedy.',
        step: s('Which frame for the fall?', [['a', 'Fast close-ups of his feet'], ['b', 'A wide shot, held, with his whole body and the cake'], ['c', 'Handheld chaos']], 'b', 'Physical comedy plays best in a [[wide_shot]] where we see all of it.') },
      { label: 'Beat', dept: 'editing', context: 'The cake lands.',
        step: s('What comes right after?', [['a', 'Cut away to the next scene'], ['b', 'Slow motion replay'], ['c', 'Hold a beat, then cut to the bride’s frozen face']], 'c', 'The laugh doubles on the [[reaction_shot]].') },
      { label: 'Sound', dept: 'sound', context: 'Music plays under the walk.',
        step: s('What happens to the music at the landing?', [['a', 'It stops dead with the splat, then pure silence'], ['b', 'It gets louder'], ['c', 'It stays the same']], 'a', 'A sudden [[silence]] gives the audience room to laugh.') },
    ],
    outcome: 'The loose tile is a clean [[setup_payoff]]. The wide frame, the held [[timing]] and the bride’s reaction finish the joke.',
    ref: 'Playtime (1967), the restaurant sequence',
  },
  {
    id: 'b4-laundromat-dance', title: 'Dance in the laundromat', genre: 'Musical',
    setup: 'A shy night-shift worker is alone in a laundromat. The washers start a rhythm. She begins to dance between the machines.',
    goal: 'Let the dance feel like one free, joyful breath.',
    terms: ['long_take', 'steadicam', 'diegetic', 'practical', 'staging'], tags: ['dance', 'joy'],
    checkpoints: [
      { label: 'Music source', dept: 'sound', context: 'The song must grow out of the room.',
        step: s('How does the music start?', [['a', 'The washer thumps become the beat, then the score joins'], ['b', 'Full orchestra from frame one'], ['c', 'No music at all']], 'a', 'Start [[diegetic]] in the room, then move to score: the world sings with her.') },
      { label: 'Shot plan', dept: 'director', context: 'The dancer can do the full routine in one go.',
        step: s('How do you cover it?', [['a', 'Thirty short cuts'], ['b', 'Only close-ups of her feet'], ['c', 'A static wide from the door'], ['d', 'One long take that moves with her']], 'd', 'A [[long_take]] proves the dance is real and keeps the flow.') },
      { label: 'Rig', dept: 'camera', context: 'The camera must glide between narrow rows.',
        step: s('Which rig?', [['a', 'A crane'], ['b', 'Steadicam'], ['c', 'Tripod']], 'b', 'A [[steadicam]] moves smoothly through tight spaces.') },
      { label: 'Light', dept: 'lighting', context: 'Overhead tubes look flat.',
        step: s('What do you change?', [['a', 'Add colored light from the washer windows and a neon sign'], ['b', 'One big softbox overhead'], ['c', 'Remove all light']], 'a', 'Lamps inside the set are [[practical]] lights; they make the room feel magic but real.') },
    ],
    outcome: 'The [[diegetic]] beat turns into a song, and a [[long_take]] on [[steadicam]] lets the joy flow without a cut.',
    ref: 'La La Land (2016), the opening number',
  },
  {
    id: 'b4-final-penalty', title: 'The last penalty', genre: 'Sports',
    setup: 'A 16-year-old goalkeeper faces the last penalty of the final. Her team lost last year on the same kick. The stadium is loud.',
    goal: 'Stretch five seconds into the longest moment of her life.',
    terms: ['close_up', 'lens_compression', 'sound_design', 'cross_cutting', 'stakes'], tags: ['sports', 'tension'],
    checkpoints: [
      { label: 'Stakes', dept: 'story', context: 'The audience does not care yet.',
        step: s('What makes this kick matter?', [['a', 'Show the score board'], ['b', 'A flashback line: her coach told her last year’s loss was her fault'], ['c', 'Add more players']], 'b', 'Personal [[stakes]] make a game into a story.') },
      { label: 'Lens', dept: 'camera', context: 'The shot from behind the goal looks flat.',
        step: s('Which lens choice?', [['a', 'A long lens, so the kicker looks close and huge'], ['b', 'A fisheye'], ['c', 'A wide lens far from the goal']], 'a', 'A long lens gives [[lens_compression]]: the kicker seems right on top of her.') },
      { label: 'Sound', dept: 'sound', context: 'The crowd is a wall of noise.',
        step: s('What do we hear before the kick?', [['a', 'Crowd at full level'], ['b', 'A pop song'], ['c', 'The crowd fades; only her breath and heartbeat']], 'c', 'Subjective [[sound_design]] puts us inside her head.') },
      { label: 'Edit', dept: 'editing', context: 'You have the kicker, the keeper and her mother in the stands.',
        step: s('How do you build the run-up?', [['a', 'Cross-cut between the three, shots getting shorter'], ['b', 'One wide shot'], ['c', 'Only the mother']], 'a', '[[cross_cutting]] with shorter shots builds tension to the kick.') },
    ],
    outcome: 'Clear [[stakes]], [[lens_compression]] and subjective sound stretch time. The [[cross_cutting]] squeezes it until the kick.',
    ref: 'Raging Bull (1980), the fight sound design',
  },
  {
    id: 'b4-rope-bridge', title: 'The rope bridge', genre: 'Adventure',
    setup: 'Two explorers must cross an old rope bridge over a deep gorge. A plank breaks under the younger one. The older one must go back for him.',
    goal: 'Make the drop feel real and huge.',
    terms: ['birds_eye', 'high_key', 'scale_units', 'drone', 'tension'], tags: ['adventure', 'height'],
    checkpoints: [
      { label: 'Height', dept: 'camera', context: 'The gorge does not look deep in the shots.',
        step: s('Which shot shows the depth?', [['a', 'A medium shot of their faces'], ['b', 'A low angle at the sky'], ['c', 'A straight-down top shot past their feet to the river'], ['d', 'An insert of the rope knot']], 'c', 'A [[birds_eye]] view down the drop shows the danger at once.') },
      { label: 'Establish', dept: 'director', context: 'The scene opens on the bridge.',
        step: s('How do you open?', [['a', 'A drone shot that pulls back to show the tiny bridge in the huge gorge'], ['b', 'A close-up on the rope'], ['c', 'Black screen']], 'a', 'A [[drone]] wide sets scale before we go close.') },
      { label: 'Blender set', dept: 'blender', context: 'The gorge is a 3D set. The bridge looks like a toy.',
        step: s('What is the likely mistake?', [['a', 'The render engine'], ['b', 'Objects are not built at real-world size'], ['c', 'Too many lights']], 'b', 'Correct [[scale_units]] make lens, depth of field and physics behave right.') },
      { label: 'Story', dept: 'story', context: 'He crosses back at once without trouble.',
        step: s('What adds pressure?', [['a', 'A second plank cracks while he reaches out'], ['b', 'A joke'], ['c', 'He gets there quickly']], 'a', 'Add a new obstacle to keep [[tension]] rising.') },
    ],
    outcome: 'A [[drone]] wide and a [[birds_eye]] drop give scale. Real [[scale_units]] and a second crack keep the [[tension]] high.',
    ref: 'Indiana Jones and the Temple of Doom (1984), the bridge climax',
  },
  {
    id: 'b4-dragon-egg', title: 'The egg in the hay', genre: 'Fantasy',
    setup: 'A farm boy finds a warm, glowing egg in the hay loft. It cracks. A tiny dragon looks at him for the first time.',
    goal: 'Make the creature feel alive and lovable.',
    terms: ['appeal', 'shape_language', 'motivated_light', 'anticipation'], tags: ['creature', 'wonder'],
    checkpoints: [
      { label: 'Design', dept: 'modeling', context: 'The dragon looks sharp and scary.',
        step: s('How do you make it cute?', [['a', 'Add more spikes'], ['b', 'Use round shapes, a big head and big eyes'], ['c', 'Make it grey'], ['d', 'Make it bigger']], 'b', 'Round forms read as friendly: [[shape_language]].') },
      { label: 'Light', dept: 'lighting', context: 'The loft is dark. The egg glows.',
        step: s('What is the key light?', [['a', 'The egg itself, warm and from below on his face'], ['b', 'A flat front light'], ['c', 'Blue daylight']], 'a', 'The glow is the source: [[motivated_light]].') },
      { label: 'Hatch', dept: 'anim_principle', context: 'The shell just pops open.',
        step: s('How do you animate the hatch?', [['a', 'Faster'], ['b', 'Linear motion'], ['c', 'Shake, pause, push, pause, then crack open']], 'c', 'Small moves before the big one are [[anticipation]].') },
      { label: 'Character', dept: 'anim_principle', context: 'Its first look at the boy feels empty.',
        step: s('What gives it charm?', [['a', 'A slow blink and a head tilt'], ['b', 'A roar'], ['c', 'No motion']], 'a', 'Small, readable acting gives [[appeal]].') },
    ],
    outcome: 'Round [[shape_language]], an egg glow and good [[anticipation]] make the dragon one we love from the first blink.',
    ref: 'How to Train Your Dragon (2010), the forest meeting',
  },
  {
    id: 'b4-airlock', title: 'Silence at the airlock', genre: 'Sci-fi',
    setup: 'An engineer repairs an antenna outside a small station. Her tether snaps. She drifts away while her partner watches from the window.',
    goal: 'Make space feel empty and real.',
    terms: ['silence', 'negative_space', 'diegetic', 'volumetric', 'pov_shot'], tags: ['space', 'tension'],
    checkpoints: [
      { label: 'Sound', dept: 'sound', context: 'The temp mix has a loud snap and an explosion.',
        step: s('What does space sound like?', [['a', 'A loud bang'], ['b', 'Echo'], ['c', 'Only her breath and radio inside the helmet']], 'c', 'There is no sound in a vacuum; keep only [[diegetic]] helmet sound.') },
      { label: 'Frame', dept: 'composition', context: 'She drifts away.',
        step: s('How do you frame her?', [['a', 'Fill the frame with her'], ['b', 'Tiny figure, huge dark space around her'], ['c', 'Split screen']], 'b', 'Empty [[negative_space]] shows how alone she is.') },
      { label: 'Light', dept: 'lighting', context: 'The crew adds visible light beams outside.',
        step: s('Is that correct?', [['a', 'Yes, always add beams'], ['b', 'Only in blue'], ['c', 'Yes, at sunset'], ['d', 'No; beams need dust or air, so keep space light hard and clean']], 'd', '[[volumetric]] light needs particles to scatter; a vacuum has none.') },
      { label: 'Partner', dept: 'camera', context: 'Her partner watches.',
        step: s('Which shot puts us with him?', [['a', 'His view through the round window as she gets smaller'], ['b', 'A drone shot'], ['c', 'A wide of the station']], 'a', 'A [[pov_shot]] makes us share his helplessness.') },
    ],
    outcome: 'True [[silence]], hard light and wide [[negative_space]] make space empty. His [[pov_shot]] makes it personal.',
    ref: 'Gravity (2013), the opening debris scene',
  },
  {
    id: 'b4-first-flight', title: 'First flight', genre: 'Superhero',
    setup: 'A teen with new powers jumps off a water tower at night. She falls, then rises above the city for the first time.',
    goal: 'Turn fear into wonder in one move.',
    terms: ['crane', 'score', 'low_key', 'camera_angle', 'character_arc'], tags: ['superhero', 'wonder'],
    checkpoints: [
      { label: 'Angle', dept: 'camera', context: 'At the start she is afraid; at the end she is strong.',
        step: s('How do the angles change?', [['a', 'High angle on her at the start, low angle when she rises'], ['b', 'Always eye level'], ['c', 'Always top shot']], 'a', 'The [[camera_angle]] tells us who has power.') },
      { label: 'Move', dept: 'camera', context: 'She rises over the roofs.',
        step: s('How does the camera follow?', [['a', 'Static'], ['b', 'Zoom in'], ['c', 'Pan only'], ['d', 'A rising crane/drone move with her, revealing the city']], 'd', 'A rising [[crane]] move shares her lift and reveals the world.') },
      { label: 'Music', dept: 'sound', context: 'During the fall there is music.',
        step: s('How do you use the score?', [['a', 'Loud the whole time'], ['b', 'Silent in the fall, the theme bursts in when she rises'], ['c', 'Comedy music']], 'b', 'Holding the [[score]] back makes the theme land.') },
      { label: 'Story', dept: 'story', context: 'Why does this moment matter?',
        step: s('What does it show?', [['a', 'The first step of her change from scared kid to hero'], ['b', 'Nothing; it is just cool'], ['c', 'The villain plan']], 'a', 'A visible turn point in her [[character_arc]].') },
    ],
    outcome: 'Shifting [[camera_angle]], a rising [[crane]] and a held-back [[score]] make the flight a step in her [[character_arc]].',
    ref: 'Spider-Man: Into the Spider-Verse (2018), the leap of faith',
  },
  {
    id: 'b4-desert-car', title: 'Two brothers, one car', genre: 'Road movie',
    setup: 'Two estranged brothers drive their late father’s old car across the desert to scatter his ashes. They have not spoken for an hour.',
    goal: 'Show the distance between them, then the first crack in it.',
    terms: ['two_shot', 'golden_hour', 'ambience', 'wide_shot', 'subtext'], tags: ['road', 'family'],
    checkpoints: [
      { label: 'Frame', dept: 'composition', context: 'Inside the car.',
        step: s('How do you frame them?', [['a', 'A frontal two-shot through the windshield, both staring ahead'], ['b', 'Only close-ups'], ['c', 'From the roof']], 'a', 'A [[two_shot]] holds both men and the space between them.') },
      { label: 'World', dept: 'camera', context: 'Between car scenes.',
        step: s('What is the cutaway?', [['a', 'A close-up of the radio'], ['b', 'A wide shot of the tiny car on an endless road'], ['c', 'A map']], 'b', 'A [[wide_shot]] shows them small and alone together.') },
      { label: 'Time', dept: 'lighting', context: 'One brother finally laughs at an old memory.',
        step: s('When do you shoot it?', [['a', 'Noon'], ['b', 'Midnight'], ['c', 'Golden hour, warm low sun in the car']], 'c', 'Warm [[golden_hour]] light matches the warm moment.') },
      { label: 'Sound', dept: 'sound', context: 'The long silence feels dead.',
        step: s('What fills it?', [['a', 'Engine hum, wind, a ticking indicator'], ['b', 'Constant music'], ['c', 'Voice-over']], 'a', 'Rich [[ambience]] makes silence feel full and awkward.') },
    ],
    outcome: 'The [[two_shot]] and endless wides show the gap. [[golden_hour]] warmth arrives with the first laugh.',
    ref: 'Paris, Texas (1984)',
  },
  {
    id: 'b4-ballroom-letter', title: 'The letter at the ball', genre: 'Period drama',
    setup: 'England, 1820s. At a candlelit ball, a governess hands a secret letter to a lord while they dance. Everyone watches the dancers.',
    goal: 'Hide the exchange from the guests, not from us.',
    terms: ['practical', 'insert', 'production_design', 'dramatic_irony', 'continuity'], tags: ['period', 'secret'],
    checkpoints: [
      { label: 'Light', dept: 'lighting', context: 'The room is lit by hundreds of candles.',
        step: s('How do you light it?', [['a', 'Modern LED panels in shot'], ['b', 'Real candles as practicals, boosted by warm soft light from the same direction'], ['c', 'Blue moonlight']], 'b', 'Candles in frame are [[practical]] sources; extra light must match them.') },
      { label: 'Detail', dept: 'camera', context: 'The letter passes between hands.',
        step: s('How do we see it?', [['a', 'A quick insert of gloved hands and folded paper'], ['b', 'A wide of the hall'], ['c', 'Her face only']], 'a', 'An [[insert]] shows the small key action clearly.') },
      { label: 'Period', dept: 'preprod', context: 'A scout finds a hall with plastic chairs and electric sockets.',
        step: s('Who solves it?', [['a', 'The sound team'], ['b', 'The editor'], ['c', 'Nobody; audiences will not notice'], ['d', 'The production design team dresses and hides them']], 'd', '[[production_design]] builds the believable period world.') },
      { label: 'Story', dept: 'story', context: 'A jealous rival is near them.',
        step: s('How do you use her?', [['a', 'Show her moving closer while we know about the letter'], ['b', 'Cut her'], ['c', 'Show her after the dance']], 'a', 'We know the secret, she does not: [[dramatic_irony]].') },
    ],
    outcome: 'Candle [[practical]] light, careful [[production_design]] and one [[insert]] carry the secret, and the rival adds [[dramatic_irony]].',
    ref: 'Barry Lyndon (1975), the candlelit scenes',
  },
  {
    id: 'b4-kitchen-brawl', title: 'Fight in a tiny kitchen', genre: 'Action',
    setup: 'A retired cook fights two thugs in her restaurant kitchen. She uses pans, a towel and a fridge door. There is very little room.',
    goal: 'A fight that is clear, fun and shows her character.',
    terms: ['action_choreo', 'medium_shot', 'match_cut', 'rehearsal', 'hk_wuxia'], tags: ['action', 'fight'],
    checkpoints: [
      { label: 'Prep', dept: 'preprod', context: 'The actors meet the stunt team on the shoot day.',
        step: s('What is missing?', [['a', 'More cameras'], ['b', 'Weeks of rehearsal of the moves'], ['c', 'Better catering']], 'b', 'Safe, sharp fights need [[rehearsal]].') },
      { label: 'Style', dept: 'history', context: 'She fights with everyday objects.',
        step: s('Which tradition is the model?', [['a', 'Hong Kong action, with props and clear full-body moves'], ['b', 'Film noir'], ['c', 'Italian neorealism']], 'a', '[[hk_wuxia]] and HK action made prop fights an art.') },
      { label: 'Frame', dept: 'camera', context: 'Fast close-ups hide the moves.',
        step: s('Which size shows the fight best?', [['a', 'Extreme close-up'], ['b', 'Bird’s-eye'], ['c', 'Medium and wider shots that hold hits and reactions']], 'c', 'A [[medium_shot]] keeps the [[action_choreo]] readable.') },
      { label: 'Cut', dept: 'editing', context: 'She swings a pan from left; it hits in the next shot.',
        step: s('Where do you cut?', [['a', 'Cut on the action, mid-swing, so it flows'], ['b', 'Before she moves'], ['c', 'Long after the hit']], 'a', 'Cutting on the move hides the cut, like a [[match_cut]] of motion.') },
    ],
    outcome: '[[rehearsal]] and HK-style [[action_choreo]] give clear moves. Wider frames and cuts on action keep it readable and fun.',
    ref: 'Police Story (1985), the mall fight',
  },
  {
    id: 'b4-wrong-funeral', title: 'Wrong funeral', genre: 'Comedy',
    setup: 'A man arrives late to his uncle’s funeral and gives a long, tearful speech. Halfway through, he sees a stranger’s photo on the coffin. He keeps talking.',
    goal: 'Make the awkward moment grow and grow.',
    terms: ['dramatic_irony', 'reaction_shot', 'long_take', 'tone', 'insert'], tags: ['comedy', 'cringe'],
    checkpoints: [
      { label: 'Reveal', dept: 'story', context: 'When should the audience learn it is the wrong funeral?',
        step: s('When?', [['a', 'At the end'], ['b', 'Never'], ['c', 'Before he does, through a background detail']], 'c', 'We know first, so every line hurts: [[dramatic_irony]].') },
      { label: 'Discovery', dept: 'camera', context: 'He notices the photo.',
        step: s('How do we show it?', [['a', 'An insert of the photo, then back to his face'], ['b', 'A drone shot'], ['c', 'Nothing']], 'a', 'An [[insert]] makes the key detail impossible to miss.') },
      { label: 'Guests', dept: 'editing', context: 'You shot all the mourners.',
        step: s('Where does the comedy live?', [['a', 'Only on him'], ['b', 'In short cuts to confused mourner faces'], ['c', 'On the coffin']], 'b', 'Each [[reaction_shot]] adds a new laugh.') },
      { label: 'Tone', dept: 'director', context: 'The actor plays it big and silly.',
        step: s('Your note?', [['a', 'Play it fully serious and sincere'], ['b', 'Wink at the camera'], ['c', 'Shout more'], ['d', 'Laugh at himself']], 'a', 'A straight performance keeps the [[tone]]; the situation is the joke.') },
    ],
    outcome: 'Early [[dramatic_irony]], one [[insert]] and many [[reaction_shot]]s let a sincere performance become very funny.',
    ref: 'Death at a Funeral (2007)',
  },
  {
    id: 'b4-robot-tango', title: 'The robot learns to tango', genre: 'Musical (animation)',
    setup: 'A clumsy cleaning robot watches an old couple dance in the park. Alone at night, it tries the steps with a broom.',
    goal: 'Its stiff body slowly becomes graceful.',
    terms: ['timing', 'follow_through', 'rigging', 'walk_cycle', 'arcs'], tags: ['animation', 'dance'],
    checkpoints: [
      { label: 'Rig', dept: 'rigging', context: 'The robot needs to bend and lean like a dancer.',
        step: s('What must the rig give?', [['a', 'One bone only'], ['b', 'No rig, animate the mesh'], ['c', 'A spine and arms with controls for lean and twist']], 'c', 'Good [[rigging]] decides what poses the animator can make.') },
      { label: 'Early moves', dept: 'anim_principle', context: 'At first it should look mechanical.',
        step: s('How?', [['a', 'Straight lines, even spacing, sudden stops'], ['b', 'Smooth arcs'], ['c', 'Squash and stretch']], 'a', 'Remove [[arcs]] and easing to read as machine.') },
      { label: 'Later moves', dept: 'anim_principle', context: 'By the end it dances well.',
        step: s('What do you add?', [['a', 'More speed'], ['b', 'Curved paths and an antenna that keeps swinging after it stops'], ['c', 'Nothing']], 'b', 'Parts that keep moving after a stop are [[follow_through]].') },
      { label: 'Beat', dept: 'anim_tech', context: 'The steps drift off the music.',
        step: s('How do you fix it?', [['a', 'Speed up the song'], ['b', 'Add more frames everywhere'], ['c', 'Mark the beats on the timeline and key steps on them'], ['d', 'Cut the music']], 'c', 'Musical [[timing]] needs keys placed on the beats.') },
    ],
    outcome: 'The [[rigging]] allows the poses. Straight paths become [[arcs]] with [[follow_through]], so the robot changes in its body.',
    ref: 'WALL-E (2008), the space dance',
  },
  {
    id: 'b4-relay-anchor', title: 'The anchor leg', genre: 'Sports',
    setup: 'A school relay team is in last place. The slowest runner gets the baton for the last leg. She has trained alone every morning for a year.',
    goal: 'Make the comeback feel earned.',
    terms: ['montage', 'setup_payoff', 'frame_rate', 'dolly'], tags: ['sports', 'underdog'],
    checkpoints: [
      { label: 'Earn it', dept: 'story', context: 'Her win feels like luck.',
        step: s('What do you add earlier?', [['a', 'A short training sequence of cold dawn runs'], ['b', 'A rival who cheats'], ['c', 'Nothing']], 'a', 'A training [[montage]] plants her effort, so the win pays off.') },
      { label: 'Move', dept: 'camera', context: 'She runs down the straight.',
        step: s('How do you shoot her run?', [['a', 'Tripod, pan only'], ['b', 'Handheld from the stands'], ['c', 'Static wide'], ['d', 'A camera car or track running beside her at her speed']], 'd', 'A side [[dolly]] / tracking move keeps her in frame and shows speed.') },
      { label: 'Slow motion', dept: 'camera', context: 'You want the finish in slow motion.',
        step: s('How do you shoot it?', [['a', 'At a higher frame rate, played back at 24 fps'], ['b', 'Slow it in edit only'], ['c', 'Lower shutter speed']], 'a', 'Shooting a high [[frame_rate]] gives smooth slow motion.') },
      { label: 'Payoff', dept: 'editing', context: 'She crosses the line.',
        step: s('What image follows?', [['a', 'Credits'], ['b', 'A cut to the dawn track from the training scenes, now empty and lit by sun'], ['c', 'The score board']], 'b', 'Echo the early image for [[setup_payoff]].') },
    ],
    outcome: 'The [[montage]] earns the win, a [[dolly]] move gives speed, and high [[frame_rate]] slow motion makes the finish land.',
    ref: 'Chariots of Fire (1981), the beach run',
  },
  {
    id: 'b4-glacier-map', title: 'The map in the ice', genre: 'Adventure',
    setup: 'A young cartographer finds an old map frozen inside a glacier wall. Her guide wants to leave before a storm. She starts to chip the ice.',
    goal: 'Make the find feel like a discovery, then a race.',
    terms: ['macguffin', 'rack_focus', 'color_temp', 'cross_cutting'], tags: ['adventure', 'discovery'],
    checkpoints: [
      { label: 'Object', dept: 'story', context: 'We never learn what the map leads to in this film.',
        step: s('Is that a problem?', [['a', 'Yes; explain it fully'], ['b', 'No; it is a MacGuffin that drives the chase'], ['c', 'Yes; cut the map']], 'b', 'A [[macguffin]] matters to the characters, not to the plot logic.') },
      { label: 'Find', dept: 'camera', context: 'She sees a shape behind the ice.',
        step: s('How do you reveal it?', [['a', 'Focus shifts from her face to the map in the ice'], ['b', 'Zoom out'], ['c', 'A title card']], 'a', 'A [[rack_focus]] moves our eye to the discovery.') },
      { label: 'Light', dept: 'color', context: 'The ice should feel cold; her lantern warm.',
        step: s('How do you set it?', [['a', 'All neutral'], ['b', 'All warm'], ['c', 'Blue ambient light, a warm orange lantern']], 'c', 'Mixed [[color_temp]] separates cold world and warm human.') },
      { label: 'Race', dept: 'editing', context: 'The storm comes closer as she works.',
        step: s('How do you build the race?', [['a', 'Cross-cut her chipping with the storm front moving in'], ['b', 'One long shot'], ['c', 'Show the storm after she finishes'], ['d', 'Add a narrator']], 'a', '[[cross_cutting]] two threads creates a ticking clock.') },
    ],
    outcome: 'The [[macguffin]] gives the goal, a [[rack_focus]] gives the find, and [[cross_cutting]] with the storm makes the race.',
    ref: 'Raiders of the Lost Ark (1981), the opening temple',
  },
  {
    id: 'b4-fairy-forest', title: 'The forest wakes', genre: 'Fantasy (animation)',
    setup: 'A girl lost in a dark forest whistles a tune. One by one, glowing spirits come out of the trees. The forest turns from scary to friendly.',
    goal: 'Change the mood of the place without words.',
    terms: ['color_script', 'volumetric', 'eevee', 'secondary_action', 'color_meaning'], tags: ['animation', 'mood'],
    checkpoints: [
      { label: 'Plan color', dept: 'preprod', context: 'The mood must change across the scene.',
        step: s('What do you make first?', [['a', 'The final render'], ['b', 'A color script: cold dark frames shifting to warm green-gold'], ['c', 'The sound mix']], 'b', 'A [[color_script]] plans the mood shift before production.') },
      { label: 'Meaning', dept: 'color', context: 'What colors for the spirits?',
        step: s('Which choice fits?', [['a', 'Red and black'], ['b', 'Grey'], ['c', 'Soft warm yellow and green']], 'c', 'Warm soft hues read as safe: [[color_meaning]].') },
      { label: 'Light', dept: 'blender', context: 'You want visible beams through the trees.',
        step: s('What do you add in Blender?', [['a', 'A volume scatter in the world or a volume cube'], ['b', 'More bevel'], ['c', 'A UV map'], ['d', 'A mirror modifier']], 'a', 'A volume medium gives [[volumetric]] light shafts.') },
      { label: 'Life', dept: 'anim_principle', context: 'The spirits float but feel dead.',
        step: s('What adds life?', [['a', 'Freeze them'], ['b', 'Small tail wiggles and glows that pulse while they float'], ['c', 'Make them bigger']], 'b', 'Small extra motion is [[secondary_action]].') },
    ],
    outcome: 'The [[color_script]] plans the change, [[volumetric]] beams and warm [[color_meaning]] carry it, and [[secondary_action]] makes the spirits live.',
    ref: 'Princess Mononoke (1997), the kodama in the forest',
  },
  {
    id: 'b4-hologram-call', title: 'Call from the future', genre: 'Sci-fi',
    setup: 'A woman gets a hologram call from her older self, ten years ahead. The future self begs her not to take a job tomorrow. Both roles are played by one actor.',
    goal: 'Make the two selves share one believable room.',
    terms: ['chroma_key', 'twinning', 'eyeline_match', 'vfx', 'shot_reverse_shot'], tags: ['scifi', 'vfx'],
    checkpoints: [
      { label: 'Twin', dept: 'modern', context: 'One actor plays both women in the same shot.' ,
        step: s('Simplest method?', [['a', 'Lock the camera, shoot each side, join the halves in comp'], ['b', 'Hire a twin'], ['c', 'Handheld and hope']], 'a', 'A locked-off split screen is classic [[vfx]] for one actor twice.') },
      { label: 'Eyes', dept: 'director', context: 'She talks to empty air. The eyes miss.',
        step: s('What do you do?', [['a', 'Nothing'], ['b', 'Close her eyes'], ['c', 'Put a tape mark or stand-in where the other self will be']], 'c', 'A marked target keeps the [[eyeline_match]] true.') },
      { label: 'Hologram', dept: 'blender', context: 'The hologram needs a clean edge.',
        step: s('How do you shoot the future self?', [['a', 'In front of an even green screen, then add a blue glow in comp'], ['b', 'In a dark room'], ['c', 'With a white wall']], 'a', 'Even green allows a clean [[chroma_key]].') },
      { label: 'Edit', dept: 'editing', context: 'The argument is long.',
        step: s('How do you cover most of it?', [['a', 'A static wide'], ['b', 'Only inserts'], ['c', 'Fast zooms'], ['d', 'Shot-reverse-shot between the two selves']], 'd', '[[shot_reverse_shot]] keeps a dialogue clear and lets the actor play each side fully.') },
    ],
    outcome: 'Locked-off [[vfx]], a true [[eyeline_match]] and a clean [[chroma_key]] let one actor argue with herself.',
    ref: 'Moon (2009)',
  },
  {
    id: 'b4-villain-entrance', title: 'The villain arrives', genre: 'Superhero',
    setup: 'A quiet city council meeting. The doors open. A calm, well-dressed villain walks in and sits down without a word.',
    goal: 'Make him frightening without any action.',
    terms: ['leitmotif', 'low_key', 'symmetry', 'headroom', 'blocking'], tags: ['villain', 'menace'],
    checkpoints: [
      { label: 'Blocking', dept: 'director', context: 'Everyone sits at a long table.',
        step: s('Where does he sit?', [['a', 'At the far end, at the head, facing the camera'], ['b', 'In the crowd'], ['c', 'Behind a plant']], 'a', 'Strong [[blocking]] puts power in a position.') },
      { label: 'Frame', dept: 'composition', context: 'The wide shot of the table.',
        step: s('How do you compose it?', [['a', 'Off-balance handheld'], ['b', 'A perfect centered, symmetrical frame with him at the center'], ['c', 'A dutch angle']], 'b', 'Cold, controlled [[symmetry]] makes him feel in charge.') },
      { label: 'Light', dept: 'lighting', context: 'The room is bright.',
        step: s('What changes when he enters?', [['a', 'Even brighter'], ['b', 'Pink light'], ['c', 'Nothing can change'], ['d', 'He sits in a darker zone, top-lit, eyes in shadow']], 'd', '[[low_key]] top light hides his eyes and adds threat.') },
      { label: 'Music', dept: 'sound', context: 'He will appear again later.',
        step: s('What do you give him?', [['a', 'A short theme of low notes that returns each time'], ['b', 'Random music each time'], ['c', 'Pop music']], 'a', 'A recurring theme is a [[leitmotif]].') },
    ],
    outcome: 'Power [[blocking]], cold [[symmetry]], [[low_key]] top light and a [[leitmotif]] make stillness scary.',
    ref: 'The Dark Knight (2008), the interrogation room',
  },
]
