import type { Scene, Step } from '../../shared/types'
const s = (prompt: string, choices: [string, string][], answer: string, why: string): Step => ({ prompt, choices: choices.map(([id, label]) => ({ id, label })), answer, why })
export const SCENES_B5: Scene[] = [
  {
    id: 'b5-fisherman-doc', title: 'The last fisherman', genre: 'Documentary',
    setup: 'You film an old fisherman in a village that is losing its harbor. He is shy in front of the camera. You have five days and one small crew.',
    goal: 'Let his life speak without forcing it.',
    terms: ['handheld', 'ambience', 'cutaway', 'golden_hour', 'visual_storytelling'], tags: ['documentary', 'observational'],
    checkpoints: [
      { label: 'Approach', dept: 'director', context: 'On day one he freezes every time the lens points at him.',
        step: s('What do you do first?', [['a', 'Ask him to repeat his morning routine for the camera'], ['b', 'Spend the day with him with the camera off, then film small tasks'], ['c', 'Give him a script to read'], ['d', 'Hide the camera in a bag']], 'b', 'Trust comes before footage; then [[visual_storytelling]] can happen naturally.') },
      { label: 'Camera', dept: 'camera', context: 'He moves fast on a small rocking boat.',
        step: s('How do you shoot on the boat?', [['a', 'Tripod locked to the deck'], ['b', 'Long dolly track on the pier'], ['c', 'Shoulder rig, wide lens, stay close and move with him']], 'c', 'A close [[handheld]] camera follows life it cannot control.') },
      { label: 'Sound', dept: 'sound', context: 'Back home, the edit feels empty between interviews.',
        step: s('What did you forget to record?', [['a', 'Room tone and long takes of gulls, ropes and waves'], ['b', 'A narrator'], ['c', 'Stock music'], ['d', 'A second interview']], 'a', 'Clean [[ambience]] glues documentary scenes together.') },
      { label: 'Edit', dept: 'editing', context: 'He says “The harbor was full once.” Your shot is only his face.',
        step: s('What do you cut to?', [['a', 'A title card'], ['b', 'Your own face nodding'], ['c', 'A slow wide of the empty harbor at dawn']], 'c', 'A [[cutaway]] shows what the words mean.') },
    ],
    outcome: 'Patience gave you honest moments. [[cutaway]] shots and [[ambience]] let the place tell the story with him.',
    ref: 'Honeyland (2019)',
  },
  {
    id: 'b5-juice-ad', title: 'Thirty seconds of orange', genre: 'Commercial',
    setup: 'A small juice brand pays for one 30-second ad. The client wants the bottle to look fresh and cold. The shoot is one day in a studio.',
    goal: 'Make the product the hero in 30 seconds.',
    terms: ['insert', 'hard_soft', 'rim_light', 'pacing', 'match_cut', 'shot_list'], tags: ['commercial', 'product'],
    checkpoints: [
      { label: 'Plan', dept: 'preprod', context: 'The client keeps adding ideas by email.',
        step: s('How do you control the day?', [['a', 'Lock a shot list with the client before the shoot'], ['b', 'Shoot everything they ask on the day'], ['c', 'Ignore the emails']], 'a', 'A signed [[shot_list]] protects time and money.') },
      { label: 'Light', dept: 'lighting', context: 'The glass bottle looks flat and grey.',
        step: s('How do you make the glass glow?', [['a', 'One hard light from the front'], ['b', 'Ceiling lights only'], ['c', 'Green light under the table'], ['d', 'A bright light behind and two strip lights at the edges']], 'd', 'Glass shows its shape with [[rim_light]] edges, not front light.') },
      { label: 'Shots', dept: 'camera', context: 'You need the cold feel.',
        step: s('Which shot sells “cold”?', [['a', 'A wide of the studio'], ['b', 'A macro insert of a drop running down the glass'], ['c', 'The actor’s back']], 'b', 'A tight [[insert]] puts the detail in the viewer’s hand.') },
      { label: 'Edit', dept: 'editing', context: 'An orange spins, then the bottle spins.',
        step: s('How do you join them?', [['a', 'Cut on the same spin and the same position in frame'], ['b', 'Fade to black between'], ['c', 'Cross dissolve for two seconds']], 'a', 'Same shape and motion make a [[match_cut]].') },
    ],
    outcome: 'Clear planning and edge light made the bottle shine. A [[match_cut]] linked fruit to product in one beat.',
    ref: 'Apple “Shot on iPhone” macro ads, for product inserts',
  },
  {
    id: 'b5-neon-music-video', title: 'Neon chorus', genre: 'Music video',
    setup: 'A synth-pop band has one night in a parking garage. The song is 3:40. The singer must lip-sync in every setup.',
    goal: 'Cut to the beat and keep sync perfect.',
    terms: ['lip_sync', 'practical', 'jump_cut', 'frame_rate', 'teal_orange'], tags: ['music video', 'rhythm'],
    checkpoints: [
      { label: 'Playback', dept: 'sound', context: 'The singer sings along with the song for each take.',
        step: s('What is the sync rule?', [['a', 'Record new vocals live each take'], ['b', 'Play the track from the start of a section and slate each take with timecode'], ['c', 'Fix sync later by stretching clips']], 'b', 'Playback with timecode keeps [[lip_sync]] exact in the edit.') },
      { label: 'Slow motion', dept: 'camera', context: 'You want slow, dreamy hair in the chorus, but with sync.',
        step: s('How do you shoot it?', [['a', 'Shoot at 24 fps and slow it in the edit'], ['b', 'Shoot at 48 fps with the song played at double speed'], ['c', 'Shoot at 12 fps']], 'b', 'Double-speed playback at double [[frame_rate]] gives slow motion with lips in sync.') },
      { label: 'Light', dept: 'lighting', context: 'The garage has dull grey tubes.',
        step: s('How do you light it?', [['a', 'Swap in colored LED tubes that can appear in frame'], ['b', 'Turn on car headlights only'], ['c', 'One big soft box from above'], ['d', 'Leave the grey tubes']], 'a', 'Lights you can see in frame are [[practical]] lights.') },
      { label: 'Edit', dept: 'editing', context: 'The verse feels slow.',
        step: s('What style helps the energy?', [['a', 'Long dissolves'], ['b', 'One unbroken wide'], ['c', 'Jump cuts on the snare between angles of the same lyric']], 'c', 'On-beat [[jump_cut]] edits add rhythm.') },
    ],
    outcome: 'Playback discipline kept [[lip_sync]] right at every speed. [[practical]] neon made the garage a set.',
    ref: 'Michel Gondry music videos, for in-camera ideas',
  },
  {
    id: 'b5-wedding-oner', title: 'One take through the wedding', genre: 'Drama',
    setup: 'A groom runs from the kitchen, through the hall, to the stage to stop his sister’s speech. You want it in one unbroken shot. You have forty extras.',
    goal: 'A clean oner that feels urgent.',
    terms: ['long_take', 'steadicam', 'blocking', 'rehearsal', 'rack_focus'], tags: ['oner', 'staging'],
    checkpoints: [
      { label: 'Plan', dept: 'director', context: 'Every attempt so far fails at a different spot.',
        step: s('What fixes it?', [['a', 'Mark every position on the floor and rehearse with stand-ins first'], ['b', 'Shoot more takes faster'], ['c', 'Shout cues during the take']], 'a', 'A [[long_take]] lives or dies by [[blocking]] marks.') },
      { label: 'Rig', dept: 'camera', context: 'The path has stairs and tight doors.',
        step: s('Which rig?', [['a', 'Dolly on track'], ['b', 'Crane'], ['c', 'Tripod with a long pan'], ['d', 'Steadicam with an operator who walked the route']], 'd', 'A [[steadicam]] glides through doors and stairs.') },
      { label: 'Focus', dept: 'camera', context: 'At the end the sister is far, the groom near.',
        step: s('How do you shift attention?', [['a', 'Cut'], ['b', 'Pull focus from groom to sister as he calls her name'], ['c', 'Zoom in fast']], 'b', 'A [[rack_focus]] is an edit inside the shot.') },
      { label: 'Extras', dept: 'preprod', context: 'Extras walk into the lens.',
        step: s('What do you do?', [['a', 'Give each extra one action and a cue, and run a full rehearsal'], ['b', 'Remove all extras'], ['c', 'Let them improvise']], 'a', 'A full [[rehearsal]] makes the crowd part of the plan.') },
    ],
    outcome: 'Marks, cues and rehearsal turned chaos into one breath. The [[long_take]] felt live because it was planned.',
    ref: '1917 (2019)',
  },
  {
    id: 'b5-green-spill', title: 'Green on her hair', genre: 'Sci-fi',
    setup: 'An actress in a spacesuit stands in front of a green screen. The plate will be a red Mars sky. The first test key shows green edges in her hair.',
    goal: 'A clean key that sits in the Mars plate.',
    terms: ['chroma_key', 'vfx', 'motivated_light', 'color_temp', 'compositor'], tags: ['vfx', 'green screen'],
    checkpoints: [
      { label: 'Distance', dept: 'lighting', context: 'She stands one meter from the screen.',
        step: s('How do you reduce spill?', [['a', 'Light her harder from the front'], ['b', 'Move her three meters forward and light the screen evenly'], ['c', 'Add more green paint']], 'b', 'Distance and even screen light make a clean [[chroma_key]].') },
      { label: 'Match', dept: 'lighting', context: 'Mars light is warm and low.',
        step: s('How do you light her?', [['a', 'Cool top light'], ['b', 'Flat even light'], ['c', 'Warm low key from the side the plate sun is on']], 'c', 'Light that matches the plate is [[motivated_light]].') },
      { label: 'Blender key', dept: 'blender', context: 'You key the plate in Blender.',
        step: s('Where do you build the key?', [['a', 'In the Compositing workspace, with a Keying node after the image'], ['b', 'In the Shader Editor on the world'], ['c', 'In Edit Mode'], ['d', 'In the Graph Editor']], 'a', 'Keys live in the [[compositor]] node tree.') },
      { label: 'Color', dept: 'color', context: 'The key is clean but she looks pasted on.',
        step: s('What final step helps?', [['a', 'Add a white border'], ['b', 'Grade her toward the plate’s warm color and match black levels'], ['c', 'Sharpen her']], 'b', 'Matching [[color_temp]] and blacks sells the [[vfx]].') },
    ],
    outcome: 'Good stage work made the [[chroma_key]] easy. Matched light and grade put her on Mars.',
    ref: 'The Martian (2015), studio scenes',
  },
  {
    id: 'b5-led-volume', title: 'Desert inside a wall', genre: 'Adventure',
    setup: 'You shoot a desert car scene on an LED volume. The game-engine desert plays on the wall behind a real car. The producer wants to save money on location travel.',
    goal: 'Make the wall look like real distance.',
    terms: ['virtual_production', 'realtime_engine', 'parallax', 'dof', 'practical'], tags: ['virtual production'],
    checkpoints: [
      { label: 'Tracking', dept: 'modern', context: 'When the camera moves, the dunes stay flat.',
        step: s('What is missing?', [['a', 'A higher wall resolution'], ['b', 'More dunes'], ['c', 'Camera tracking that moves the engine view with the lens']], 'c', 'Tracked camera views in a [[realtime_engine]] create [[parallax]].') },
      { label: 'Focus', dept: 'camera', context: 'You see the LED pixels in the wide shot.',
        step: s('How do you hide them?', [['a', 'Shallow focus on the car so the wall is soft'], ['b', 'Stop down to f/16'], ['c', 'Move the camera closer to the wall']], 'a', 'Shallow [[dof]] hides the screen and moiré.') },
      { label: 'Light', dept: 'lighting', context: 'The wall lights the car nicely, but there is no hard sun.',
        step: s('What do you add?', [['a', 'Nothing'], ['b', 'A hard real light matched to the sun on the wall'], ['c', 'A green fill'], ['d', 'A soft box above']], 'b', 'LED walls give soft light; add real hard sun for [[virtual_production]].') },
      { label: 'Sets', dept: 'preprod', context: 'The floor ends sharply at the wall.',
        step: s('How do you blend it?', [['a', 'Real sand and rocks on the floor that match the screen'], ['b', 'Black floor'], ['c', 'Shoot only close-ups']], 'a', 'Real set pieces bridge the join, like a [[practical]] element.') },
    ],
    outcome: 'Tracking gave true [[parallax]] and soft focus hid the wall. Real sun and sand finished the trick.',
    ref: 'The Mandalorian (2019), making-of',
  },
  {
    id: 'b5-ai-previs', title: 'Pitch with machine frames', genre: 'Fantasy',
    setup: 'You pitch a dragon chase to a studio in one week. You use AI image tools to draft key frames. Each frame shows a different dragon.',
    goal: 'A clear previs that sells the sequence.',
    terms: ['ai_video', 'consistency', 'prompt_shot', 'animatic', 'previs', 'storyboard'], tags: ['ai', 'previs'],
    checkpoints: [
      { label: 'Order', dept: 'preprod', context: 'You start by generating pretty images.',
        step: s('What should come first?', [['a', 'Sound mix'], ['b', 'Final renders'], ['c', 'A rough storyboard of the shots and story beats']], 'c', 'A [[storyboard]] sets the beats; AI only fills them.') },
      { label: 'Prompts', dept: 'modern', context: 'Your prompts say only “epic dragon chase”.',
        step: s('How do you prompt each frame?', [['a', 'Add shot size, lens, angle and light, like a shot list line'], ['b', 'Add more adjectives'], ['c', 'Use the same prompt for all']], 'a', 'A good [[prompt_shot]] speaks camera language.') },
      { label: 'Dragon', dept: 'modern', context: 'The dragon changes color every frame.',
        step: s('How do you keep it the same?', [['a', 'Accept it'], ['b', 'Generate 200 more and pick'], ['c', 'Ask for a different style'], ['d', 'Use a fixed reference sheet image and the same seed or character tool']], 'd', 'Reference images keep [[consistency]].') },
      { label: 'Timing', dept: 'editing', context: 'The studio wants to feel the pace.',
        step: s('What do you deliver?', [['a', 'A PDF of frames'], ['b', 'An animatic with temp sound and real shot lengths'], ['c', 'A long email']], 'b', 'An [[animatic]] turns frames into time.') },
    ],
    outcome: 'Story first, AI second. The [[animatic]] showed pace, and [[consistency]] kept one dragon.',
    ref: 'Corridor Crew videos on AI workflows',
  },
  {
    id: 'b5-student-bus', title: 'No money, one bus stop', genre: 'Drama',
    setup: 'Your student film has a budget of 300 dollars. The script has a crowd scene in a train station. You have friends, a phone camera and two weekends.',
    goal: 'Make it look bigger than the budget.',
    terms: ['budget_triangle', 'script_breakdown', 'close_up', 'sound_design', 'schedule'], tags: ['student', 'low budget'],
    checkpoints: [
      { label: 'Rewrite', dept: 'story', context: 'A train station costs too much.',
        step: s('What do you change?', [['a', 'Fake a station with paper signs'], ['b', 'Move the scene to a quiet bus stop that keeps the same emotion'], ['c', 'Cut the scene'], ['d', 'Shoot in the station without permission']], 'b', 'Cheap, fast, good: pick two. That is the [[budget_triangle]].') },
      { label: 'Breakdown', dept: 'preprod', context: 'Props keep being forgotten.',
        step: s('What fixes this?', [['a', 'A breakdown that lists every prop, costume and location per scene'], ['b', 'Bring everything every day'], ['c', 'Memory']], 'a', 'A [[script_breakdown]] catches it all.') },
      { label: 'Shots', dept: 'camera', context: 'You have only three extras.',
        step: s('How do you shoot the crowd moment?', [['a', 'Wide shots'], ['b', 'Drone'], ['c', 'Tight shots, extras passing close to the lens']], 'c', 'A [[close_up]] hides how small the crowd is.') },
      { label: 'Sound', dept: 'sound', context: 'The stop feels empty.',
        step: s('How do you fill it?', [['a', 'Layers of distant traffic, voices and a bus engine'], ['b', 'Louder music'], ['c', 'Silence']], 'a', '[[sound_design]] builds the world the camera cannot afford.') },
    ],
    outcome: 'You traded scale for emotion. Tight framing and [[sound_design]] made the small world feel full.',
    ref: 'Tangerine (2015), shot on phones',
  },
  {
    id: 'b5-fireflies', title: 'White dots in the night', genre: 'Animation',
    setup: 'Your Blender short has a candle-lit room rendered in Cycles. The render is full of bright white dots. The deadline is in two days.',
    goal: 'A clean frame without long renders.',
    terms: ['cycles', 'samples_noise', 'noise', 'render_engine', 'light_types'], tags: ['blender', 'render'],
    checkpoints: [
      { label: 'Diagnose', dept: 'blender', context: 'The dots come from glossy bounces of a tiny light.',
        step: s('Where do you limit them?', [['a', 'Render Properties > Light Paths > Clamping, Indirect Light'], ['b', 'Output Properties > Frame Rate'], ['c', 'Object Properties > Visibility'], ['d', 'Scene Properties > Units']], 'a', 'Clamping indirect light kills fireflies in [[cycles]].') },
      { label: 'Denoise', dept: 'blender', context: 'Grain stays in the dark corners.',
        step: s('What do you turn on?', [['a', 'More bevel'], ['b', 'Render Properties > Sampling > Render > Denoise'], ['c', 'Motion blur']], 'b', 'Denoise trades a few [[samples_noise]] for clean dark areas.') },
      { label: 'Light size', dept: 'lighting', context: 'The candle is a Point light with radius 0.',
        step: s('What helps the noise?', [['a', 'Make the light radius a little larger'], ['b', 'Set strength to 10,000'], ['c', 'Delete the light'], ['d', 'Use a Sun light']], 'a', 'Bigger [[light_types]] sources sample with less [[noise]].') },
      { label: 'Engine', dept: 'blender', context: 'One shot is a wide with no glass.',
        step: s('Could you switch engine?', [['a', 'Never'], ['b', 'Use Workbench'], ['c', 'Test EEVEE for that shot if it looks close enough']], 'c', 'Pick the [[render_engine]] per need.') },
    ],
    outcome: 'Clamping, denoise and a softer light cleaned the frame. You saved time by choosing the [[render_engine]] per shot.',
    ref: 'Blender Manual: Cycles Light Paths',
  },
  {
    id: 'b5-washed-render', title: 'The grey sunset', genre: 'Animation',
    setup: 'A Blender artist renders a sunset scene. In the render, colors look grey and the sky is clipped white. The artist changed many settings and is lost.',
    goal: 'Strong color without clipping.',
    terms: ['view_transform', 'dynamic_range', 'exposure_triangle', 'hdri', 'output_settings'], tags: ['blender', 'color management'],
    checkpoints: [
      { label: 'Transform', dept: 'blender', context: 'Color Management shows View Transform: Standard.',
        step: s('What do you pick for high range?', [['a', 'Raw'], ['b', 'AgX (or Filmic)'], ['c', 'Standard with higher exposure']], 'b', 'AgX maps bright light softly: the [[view_transform]].') },
      { label: 'Look', dept: 'color', context: 'AgX looks a little flat.',
        step: s('How do you add punch?', [['a', 'Set Look to a higher contrast option under Color Management'], ['b', 'Raise every light'], ['c', 'Use Standard again'], ['d', 'Change the file format']], 'a', 'Contrast looks shape [[dynamic_range]] without clipping.') },
      { label: 'Sky', dept: 'lighting', context: 'The world is a flat orange color.',
        step: s('What gives real sky light?', [['a', 'A sunset HDRI in the World shader'], ['b', 'Ten point lights'], ['c', 'An orange plane']], 'a', 'An [[hdri]] gives true sky range.') },
      { label: 'Save', dept: 'blender', context: 'You will grade later in another tool.',
        step: s('How do you save frames?', [['a', '8-bit JPEG'], ['b', 'MP4'], ['c', 'OpenEXR in Output Properties']], 'c', 'EXR in [[output_settings]] keeps full range for the grade.') },
    ],
    outcome: 'AgX and an HDRI gave the sunset its range. EXR output kept it safe for grading.',
    ref: 'Blender Manual: Color Management',
  },
  {
    id: 'b5-comp-passes', title: 'Fix the glow, not the render', genre: 'Animation',
    setup: 'A director asks for a brighter glow on a robot eye in a finished Blender shot. Re-rendering takes ten hours. You rendered with no extra passes.',
    goal: 'Change it in compositing next time without a re-render.',
    terms: ['view_layer', 'compositor', 'render_farm', 'post_pipeline'], tags: ['blender', 'compositing'],
    checkpoints: [
      { label: 'Passes', dept: 'blender', context: 'You prepare the next shot.',
        step: s('What do you enable?', [['a', 'More samples'], ['b', 'Emission and Cryptomatte passes in View Layer Properties > Passes'], ['c', 'A higher frame rate'], ['d', 'Simplify']], 'b', 'Passes are set per [[view_layer]].') },
      { label: 'Glow', dept: 'blender', context: 'The Emission pass is in the compositor.',
        step: s('Which node adds glow?', [['a', 'Glare node on the emission, then mix back'], ['b', 'Normal Map node'], ['c', 'Subdivision modifier']], 'a', 'The [[compositor]] Glare node adds bloom after render.') },
      { label: 'Flow', dept: 'preprod', context: 'Other notes may come.',
        step: s('What is the lesson?', [['a', 'Bake everything into the beauty pass'], ['b', 'Never accept notes'], ['c', 'Plan passes in the post pipeline before final render']], 'c', 'A planned [[post_pipeline]] makes notes cheap.') },
      { label: 'Time', dept: 'blender', context: 'A full re-render is still needed for one shot.',
        step: s('How do you speed it?', [['a', 'Split the frames across several machines'], ['b', 'Render at 10 % size'], ['c', 'Wait']], 'a', 'A [[render_farm]] shares the frames.') },
    ],
    outcome: 'Passes moved the fix from render to [[compositor]]. Notes became minutes, not hours.',
    ref: 'Blender Studio: Sprite Fright compositing',
  },
  {
    id: 'b5-night-grade', title: 'Day for night', genre: 'Thriller',
    setup: 'You shot a forest chase in daylight because night was too expensive. Now it must look like moonlit night. The faces must still read.',
    goal: 'A believable night in the grade.',
    terms: ['color_grading', 'lut', 'value_structure', 'white_balance', 'contrast'], tags: ['color', 'grading'],
    checkpoints: [
      { label: 'Exposure', dept: 'color', context: 'The sky is bright.',
        step: s('First step?', [['a', 'Add blue only'], ['b', 'Pull exposure down two stops and crush the sky with a mask'], ['c', 'Raise saturation']], 'b', 'Night is first about [[value_structure]]: dark areas, few lights.') },
      { label: 'Balance', dept: 'color', context: 'Skin looks purple.',
        step: s('How do you fix it?', [['a', 'Warm all'], ['b', 'Remove all color'], ['c', 'Keep the blue cast in shadows, protect skin with a qualifier'], ['d', 'Add a LUT twice']], 'c', 'Shift the overall [[white_balance]] cool but keep skin readable.') },
      { label: 'LUT', dept: 'color', context: 'A friend sends a “night” LUT.',
        step: s('How do you use it?', [['a', 'After a normalized base grade, at low strength'], ['b', 'On raw log footage at 100 %'], ['c', 'Never']], 'a', 'A [[lut]] is a starting look, not the whole [[color_grading]].') },
      { label: 'Eyes', dept: 'color', context: 'The faces sink into the dark.',
        step: s('What helps?', [['a', 'Lift everything'], ['b', 'Small power windows that lift faces and eye glints'], ['c', 'Add grain']], 'b', 'Local [[contrast]] guides the eye in the dark.') },
    ],
    outcome: 'Dark values first, cool balance second, faces last. The [[color_grading]] made day into night.',
    ref: 'Mad Max: Fury Road (2015), night scenes',
  },
  {
    id: 'b5-dead-mic', title: 'The wind ate the dialogue', genre: 'Drama',
    setup: 'A key scene on a cliff has heavy wind noise. The lead’s big line is unusable. The actor is free for one hour next week.',
    goal: 'Save the line and keep the place alive.',
    terms: ['adr', 'foley', 'ambience', 'mix', 'double_system'], tags: ['sound', 'post'],
    checkpoints: [
      { label: 'Record', dept: 'sound', context: 'You book the actor.',
        step: s('How do you re-record?', [['a', 'Have them shout in a hallway'], ['b', 'Read the line over a phone'], ['c', 'Record in a quiet booth, watching the picture, many takes for sync']], 'c', 'Replacing dialogue in post is [[adr]].') },
      { label: 'Place', dept: 'sound', context: 'The clean ADR sounds like a studio.',
        step: s('How do you place it on the cliff?', [['a', 'Add light wind ambience and a touch of outdoor room reverb'], ['b', 'Leave it dry'], ['c', 'Add a big echo']], 'a', '[[ambience]] puts the voice back in the space.') },
      { label: 'Body', dept: 'sound', context: 'His jacket moves, but makes no sound now.',
        step: s('What do you add?', [['a', 'Music'], ['b', 'Foley of cloth and steps on gravel'], ['c', 'Nothing']], 'b', 'Small body sounds are [[foley]].') },
      { label: 'Next time', dept: 'preprod', context: 'How do you avoid this?',
        step: s('Best prevention?', [['a', 'Separate sound recorder with a blimped boom and a lav as backup'], ['b', 'Camera mic only'], ['c', 'Shoot indoors only'], ['d', 'Turn gain up']], 'a', 'A [[double_system]] setup with backup mics saves scenes.') },
    ],
    outcome: '[[adr]], [[ambience]] and [[foley]] rebuilt the cliff. The final [[mix]] hid the repair.',
    ref: 'Ben Burtt interviews on sound in post',
  },
  {
    id: 'b5-edit-rescue', title: 'The cut that runs too long', genre: 'Comedy',
    setup: 'Your 20-minute comedy short tests badly. People laugh in the first five minutes, then go quiet. The director loves every scene.',
    goal: 'Find the film inside the footage.',
    terms: ['pacing', 'assembly', 'murch_rule', 'cross_cutting', 'reaction_shot'], tags: ['editing', 'rescue'],
    checkpoints: [
      { label: 'Diagnose', dept: 'editing', context: 'The middle has three scenes that say the same joke.',
        step: s('What do you do?', [['a', 'Keep all three'], ['b', 'Add music'], ['c', 'Speed up the footage'], ['d', 'Keep the best one and cut the others']], 'd', 'Repeated beats kill [[pacing]].') },
      { label: 'Join', dept: 'editing', context: 'Two plot lines move slowly one after another.',
        step: s('How do you speed them?', [['a', 'Cut between them so each shows less'], ['b', 'Play them back to back'], ['c', 'Split screen for 10 minutes']], 'a', '[[cross_cutting]] compresses time.') },
      { label: 'Jokes', dept: 'editing', context: 'Jokes land flat.',
        step: s('What often helps?', [['a', 'Cut on the line'], ['b', 'Hold a beat on a listener’s reaction'], ['c', 'Add a laugh track']], 'b', 'Comedy often lives in the [[reaction_shot]].') },
      { label: 'Choose', dept: 'director', context: 'Two takes: one perfect in continuity, one funnier.',
        step: s('Which do you use?', [['a', 'The perfect continuity take'], ['b', 'Neither'], ['c', 'The funnier one; emotion comes first']], 'c', 'The [[murch_rule]] puts emotion above continuity.') },
    ],
    outcome: 'The first [[assembly]] became a 12-minute film. Cutting repeats and trusting [[reaction_shot]] timing brought the laughs back.',
    ref: 'In the Blink of an Eye, Walter Murch (book)',
  },
  {
    id: 'b5-motion-blur-sim', title: 'Stutter in the spin', genre: 'Animation',
    setup: 'A Blender animation has a fast spinning top. On playback the spin looks like it jumps. The render settings are default.',
    goal: 'Smooth motion that feels filmed.',
    terms: ['motion_blur', 'shutter', 'frame_rate', 'eevee', 'graph_editor'], tags: ['blender', 'motion'],
    checkpoints: [
      { label: 'Blur', dept: 'blender', context: 'Motion blur is off.',
        step: s('Where do you turn it on?', [['a', 'Render Properties > Motion Blur'], ['b', 'Object Data > Normals'], ['c', 'World Properties'], ['d', 'Modifier panel']], 'a', 'Render [[motion_blur]] smears fast movement.') },
      { label: 'Shutter', dept: 'camera', context: 'You want a film look.',
        step: s('What shutter value?', [['a', '0.1'], ['b', '0.5, like a 180-degree shutter'], ['c', '2.0']], 'b', 'A half-frame [[shutter]] matches film cameras.') },
      { label: 'Curve', dept: 'anim_tech', context: 'The spin slows at each key.',
        step: s('How do you fix steady spin?', [['a', 'Add more keys'], ['b', 'Use a smaller frame rate'], ['c', 'Set the keys to Linear interpolation in the Graph Editor (T)']], 'c', 'Linear keys in the [[graph_editor]] give constant speed.') },
      { label: 'Rate', dept: 'camera', context: 'The client wants 24 fps.',
        step: s('Where is that set?', [['a', 'Output Properties > Format > Frame Rate'], ['b', 'Render Properties > Sampling'], ['c', 'Scene Properties > Gravity']], 'a', 'The [[frame_rate]] lives in Output Properties.') },
    ],
    outcome: 'Linear keys gave steady speed and [[motion_blur]] with a 0.5 [[shutter]] made it smooth.',
    ref: 'Blender Manual: Motion Blur',
  },
  {
    id: 'b5-shadow-catcher', title: 'A robot on a real street', genre: 'Sci-fi',
    setup: 'You filmed an empty street with a phone. You must place a Blender robot in it. It floats because it casts no shadow on the road.',
    goal: 'Ground the CG robot in the plate.',
    terms: ['vfx', 'hdri', 'camera_blender', 'cycles', 'compositor', 'focal_length'], tags: ['blender', 'vfx'],
    checkpoints: [
      { label: 'Lens', dept: 'camera', context: 'The perspective feels wrong.',
        step: s('What do you match first?', [['a', 'Color'], ['b', 'Focal length and sensor of the phone in the Blender camera'], ['c', 'Robot size']], 'b', 'Same [[focal_length]] gives same perspective.') },
      { label: 'Shadow', dept: 'blender', context: 'You add a ground plane.',
        step: s('How do you make it show only shadows?', [['a', 'Delete it after render'], ['b', 'Make it black'], ['c', 'Hide it in viewport'], ['d', 'Object Properties > Visibility > Shadow Catcher, in Cycles']], 'd', 'Shadow Catcher works in [[cycles]].') },
      { label: 'Light', dept: 'lighting', context: 'You took a 360 photo on set.',
        step: s('How do you use it?', [['a', 'As an HDRI in the World to light the robot'], ['b', 'As a texture on the robot'], ['c', 'Ignore it']], 'a', 'An on-set [[hdri]] matches real light.') },
      { label: 'Merge', dept: 'blender', context: 'Film Transparent is on.',
        step: s('How do you combine?', [['a', 'In the VSE as two tracks with no alpha'], ['b', 'Alpha Over node with the plate in the compositor'], ['c', 'Paint it']], 'b', 'Alpha Over in the [[compositor]] lays CG over the plate.') },
    ],
    outcome: 'Matched lens, real light and a shadow catcher stuck the robot to the street. That is the core of [[vfx]] integration.',
    ref: 'District 9 (2009)',
  },
  {
    id: 'b5-podcast-to-doc', title: 'Talking heads that sleep', genre: 'Documentary',
    setup: 'A science documentary has six expert interviews. Every shot is a medium shot on a grey wall. Test viewers get bored after ten minutes.',
    goal: 'Give the interviews life and shape.',
    terms: ['shot_size', 'lighting_three_point', 'insert', 'three_act', 'jump_cut'], tags: ['documentary', 'interview'],
    checkpoints: [
      { label: 'Structure', dept: 'story', context: 'The film plays interviews one by one.',
        step: s('How do you reorder?', [['a', 'Alphabetical by name'], ['b', 'Longest first'], ['c', 'Shape a question, a struggle and an answer across all experts']], 'c', 'Even a documentary needs [[three_act]] shape.') },
      { label: 'Frame', dept: 'camera', context: 'For new pickups you have two cameras.',
        step: s('How do you use them?', [['a', 'One medium, one tighter close-up on another angle'], ['b', 'Both the same'], ['c', 'One on the floor']], 'a', 'Two [[shot_size]] options let you cut without a jump.') },
      { label: 'Light', dept: 'lighting', context: 'The faces look flat.',
        step: s('What setup?', [['a', 'Ceiling lights'], ['b', 'Soft key at 45 degrees, low fill, a back light'], ['c', 'Window behind them only'], ['d', 'Camera flash']], 'b', 'Classic [[lighting_three_point]] gives shape.') },
      { label: 'Cut', dept: 'editing', context: 'You shorten a long answer.',
        step: s('How do you hide cuts?', [['a', 'Cover them with inserts of the experiment, or accept a jump cut'], ['b', 'Fade to black each time'], ['c', 'Never shorten']], 'a', 'An [[insert]] covers the edit; a [[jump_cut]] can be honest too.') },
    ],
    outcome: 'Story shape and two angles woke up the talking heads. Inserts turned talk into pictures.',
    ref: 'The Fog of War (2003)',
  },
  {
    id: 'b5-lineart-ad', title: 'Ink lines for a bank ad', genre: 'Commercial',
    setup: 'A bank wants a 15-second ad in a hand-drawn ink style. Your team works in 3D in Blender. The deadline is one week.',
    goal: 'A 2D ink look from 3D scenes.',
    terms: ['npr', 'freestyle_lineart', 'shader_to_rgb', 'eevee', 'on_twos'], tags: ['blender', 'stylized'],
    checkpoints: [
      { label: 'Lines', dept: 'blender', context: 'You need outlines on all objects.',
        step: s('What is a fast option?', [['a', 'A Line Art modifier on a Grease Pencil object, or Freestyle in Render Properties'], ['b', 'Model every line by hand'], ['c', 'Use Wireframe mode']], 'a', 'Line Art and Freestyle are [[freestyle_lineart]] tools.') },
      { label: 'Shading', dept: 'blender', context: 'Smooth shading looks too 3D.',
        step: s('How do you get flat tones in EEVEE?', [['a', 'More samples'], ['b', 'Use Cycles'], ['c', 'Shader to RGB into a Color Ramp set to Constant']], 'c', '[[shader_to_rgb]] lets you step light into bands.') },
      { label: 'Motion', dept: 'anim_principle', context: 'The motion feels too smooth for ink.',
        step: s('What helps the hand-drawn feel?', [['a', 'Animate on twos with stepped keys'], ['b', '60 fps'], ['c', 'More motion blur'], ['d', 'Slow it down']], 'a', 'Holding each pose two frames is [[on_twos]].') },
      { label: 'Engine', dept: 'blender', context: 'Render time is tight.',
        step: s('Which engine?', [['a', 'Cycles at 4096 samples'], ['b', 'EEVEE'], ['c', 'Workbench only']], 'b', '[[eevee]] renders this [[npr]] look fast.') },
    ],
    outcome: 'Line Art, toon bands and stepped motion made 3D read as ink. [[npr]] saved the week.',
    ref: 'Spider-Man: Into the Spider-Verse (2018)',
  },
]
